// Imaginary places and illustrative facts, never real-world logistics or live data.
export const FIXTURE_SOURCE_ID = "cmg00000000000000000000200";
export const FIXTURE_SEGMENT_ID = "cmg00000000000000000000011";
export const FIXTURE_RETRIEVED_AT = "2026-09-22T00:00:00.000Z";

export const DISCOVER_FIXTURES = [
  { interestTags: ["SIGHTSEEING_LANDMARKS"], name: "Riverside Observation Deck", category: "Viewpoint", summary: "An imaginary open-air deck overlooking a river bend.", durationMinutes: 45, cost: "Illustrative fixture: no admission charge.", logistics: "Fixture layout includes a stepped approach; accessibility is not verified." },
  { interestTags: ["FOOD_DRINK"], name: "Old Market Food Hall", category: "Food", summary: "An imaginary covered hall with several food counters and shared seating.", durationMinutes: 60, cost: "Illustrative fixture: food purchased separately.", logistics: "No real menus, opening hours or dietary information are available." },
  { interestTags: ["ARCHITECTURE_DESIGN","CULTURE_HISTORY"], name: "Contemporary Design Museum", category: "Museum", summary: "An imaginary indoor collection of furniture and graphic design.", durationMinutes: 90, cost: "Illustrative fixture: paid admission; no real price quoted.", logistics: "No tickets or availability are offered by this development catalog." },
  { interestTags: ["CULTURE_HISTORY","NIGHTLIFE"], name: "Lantern District Walk", category: "Walking", summary: "An imaginary walking circuit through a lantern-lined neighborhood.", durationMinutes: 75, cost: "Illustrative fixture: self-guided walk.", logistics: "Route conditions, distance and safety have not been checked." },
  { interestTags: ["NATURE_OUTDOORS","WELLNESS_RELAXATION"], name: "City Garden Pavilion", category: "Garden", summary: "An imaginary pavilion within a landscaped public garden.", durationMinutes: 45, cost: "Illustrative fixture: no admission charge.", logistics: "No current access or seasonal conditions are known." },
  { interestTags: ["CULTURE_HISTORY"], name: "Railway History Gallery", category: "Museum", summary: "An imaginary gallery of railway models and historical displays.", durationMinutes: 60, cost: "Illustrative fixture: admission cost unknown.", logistics: "No real opening hours or reservation requirements are asserted." },
  { interestTags: ["SHOPPING"], name: "Craft Street Arcade", category: "Shopping", summary: "An imaginary covered arcade of small craft shops.", durationMinutes: 60, cost: "Illustrative fixture: purchases optional.", logistics: "Individual shop schedules and stock are not provided." },
  { interestTags: ["NATURE_OUTDOORS"], name: "Canal Evening Promenade", category: "Walking", summary: "An imaginary waterside path with seating beside a canal.", durationMinutes: 50, cost: "Illustrative fixture: no admission charge.", logistics: "Lighting, access and weather suitability are not verified." },
  { interestTags: ["ARCHITECTURE_DESIGN", "CULTURE_HISTORY"], name: "Brickwork Design Studio", category: "Design", summary: "An imaginary exhibition of brickwork and building models.", durationMinutes: 60, cost: "Illustrative fixture: admission cost unknown.", logistics: "No live access details or availability are supplied." },
  { interestTags: ["FOOD_DRINK", "NIGHTLIFE"], name: "Twilight Food Court", category: "Food", summary: "An imaginary evening courtyard with shared food counters.", durationMinutes: 60, cost: "Illustrative fixture: food purchased separately.", logistics: "No real menus, operating hours or dietary information are supplied." },
  { interestTags: ["ARCHITECTURE_DESIGN"], name: "Courtyard Architecture Gallery", category: "Architecture", summary: "An imaginary gallery of courtyard layouts and architectural models.", durationMinutes: 75, cost: "Illustrative fixture: admission cost unknown.", logistics: "No real tickets or opening hours are asserted." },
  { interestTags: ["ENTERTAINMENT", "WELLNESS_RELAXATION"], name: "Listening Room Pavilion", category: "Entertainment", summary: "An imaginary listening room with recorded instrumental music and seating.", durationMinutes: 45, cost: "Illustrative fixture: admission cost unknown.", logistics: "No real performances, booking or accessibility details are available." },
] as const;
