import type { CatalogPlace } from "./catalog";
import type { ExperienceSource } from "../experiences/types";
export type { EventOccurrence, ExperienceSource } from "../experiences/types";
export type SourceRole = ExperienceSource["role"];
const observedAt = "2026-09-23";
function place(slug: string, name: string, category: string, group: string, interests: CatalogPlace["interests"], summary: string, location: string, url: string, durationMinutes: number, kind: "VENUE" | "NEIGHBORHOOD" = "VENUE"): CatalogPlace {
  return { id: "curated-" + slug, city: "Tokyo", name, category, diversityGroup: group, interests, summary, location, url, checkedAt: observedAt, durationMinutes, kind };
}
export const TOKYO_ADDITIONS: CatalogPlace[] = [
  place("imperial-east-gardens", "Imperial Palace East Gardens", "Castle grounds & garden", "heritage", ["CULTURE_HISTORY", "NATURE_OUTDOORS"], "Walk the former Edo Castle grounds, stone foundations and Ninomaru garden. This is the East Gardens visit, not entry to the Imperial Palace’s inner grounds.", "Chiyoda", "https://www.japan.travel/en/spot/1726/", 90),
  place("pokemon-shibuya", "Pokémon Center SHIBUYA", "Pokémon shop", "pop-culture", ["ENTERTAINMENT", "SHOPPING"], "Browse Pokémon merchandise at the Shibuya PARCO branch on the sixth floor. This is a shop visit; particular products and stock are not guaranteed.", "Shibuya PARCO 6F, Udagawacho", "https://shop.pokemon.co.jp/en/shop/pokemoncenter-shibuya/", 45),
  place("pokemon-mega-tokyo", "Pokémon Center MEGA TOKYO", "Pokémon shop", "pop-culture", ["ENTERTAINMENT", "SHOPPING"], "Explore the Pokémon store inside Sunshine City alpa in Ikebukuro. This is the MEGA TOKYO branch, separate from SHIBUYA; merchandise availability varies.", "Sunshine City alpa 2F, Higashi-Ikebukuro", "https://shop.pokemon.co.jp/en/shop/pokemoncenter-megatokyo/", 45),
  place("shibuya-crossing", "Shibuya Crossing walk", "City crossing", "city-sights", ["SIGHTSEEING_LANDMARKS"], "Cross the diagonal pedestrian lanes outside Shibuya Station and watch the changing street scene from surrounding sidewalks. Rooftop access at SHIBUYA SKY is a separate experience.", "Shibuya Station, Hachiko side", "https://www.gotokyo.org/en/destinations/western-tokyo/shibuya/index.html", 30, "NEIGHBORHOOD"),
  place("shibuya-sky", "SHIBUYA SKY", "Observation deck", "city-sights", ["SIGHTSEEING_LANDMARKS", "ARCHITECTURE_DESIGN"], "Look across Tokyo from Shibuya Scramble Square’s rooftop and indoor observation corridor. Check the operator’s admission and rooftop conditions before visiting.", "Shibuya Scramble Square", "https://www.shibuya-scramble-square.com/en/", 75),
  place("akihabara", "Akihabara shops and arcades walk", "Anime & gaming walk", "pop-culture", ["ENTERTAINMENT", "SHOPPING"], "Browse anime figures, game shops and electronics around Akihabara’s main streets. Choose your own optional arcade or shop stops; they are not separate scheduled activities.", "Akihabara, Chiyoda", "https://www.gotokyo.org/en/destinations/central-tokyo/akihabara/index.html", 120, "NEIGHBORHOOD"),
  place("ginza", "Ginza window-shopping walk", "Shopping & architecture walk", "shopping", ["SHOPPING", "ARCHITECTURE_DESIGN"], "Walk Ginza’s shopping streets and compare department-store facades, design shops and window displays. Browsing a store or stopping for food is optional.", "Ginza, Chuo", "https://www.gotokyo.org/en/destinations/central-tokyo/ginza/index.html", 90, "NEIGHBORHOOD"),
  place("teamlab-planets", "teamLab Planets TOKYO", "Immersive art", "immersive-art", ["ENTERTAINMENT", "ARCHITECTURE_DESIGN"], "Move through body-scale digital artworks at the Toyosu museum. Water areas require bare feet and can reach adult knee height; review access guidance. This is Planets, not Borderless.", "6-1-16 Toyosu, Koto", "https://www.teamlab.art/e/planets/", 120),
  place("hamarikyu", "Hama-rikyu garden and matcha stop", "Garden & tea", "food-drink", ["FOOD_DRINK", "NATURE_OUTDOORS", "CULTURE_HISTORY"], "Follow paths around the tidal pond, then consider matcha and a sweet at Nakajima-no-ochaya on its island. Tea service is an optional purchase, separate from garden admission.", "Hama-rikyu Gardens, Chuo", "https://www.tokyo-park.or.jp/park/hama-rikyu/", 90),
  place("tsukiji", "Tsukiji Outer Market browsing", "Food market walk", "food-drink", ["FOOD_DRINK", "SHOPPING"], "Browse seafood counters, produce and kitchen goods in the outer-market lanes. Choose food stops as you go; this is not a visit to the wholesale tuna auction.", "Tsukiji, Chuo", "https://www.tsukiji.or.jp/english/", 90, "NEIGHBORHOOD"),
  place("yanaka", "Yanaka shopping-lane walk", "Neighborhood exploration", "neighborhood", ["CULTURE_HISTORY", "SHOPPING"], "Browse small shops along Yanaka Ginza, then explore nearby lanes toward Sendagi. Snack counters and craft shops are optional stops on this self-directed walk.", "Yanaka and Sendagi", "https://www.gotokyo.org/en/destinations/northern-tokyo/yanaka-and-nezu/index.html", 90, "NEIGHBORHOOD"),
  place("shimokitazawa", "Shimokitazawa vintage-shop walk", "Vintage shopping walk", "shopping", ["SHOPPING", "ENTERTAINMENT"], "Explore the lanes around Shimokitazawa Station and browse secondhand clothing and record shops. Choose an optional cafe stop; a concert or club admission is not included.", "Shimokitazawa, Setagaya", "https://www.gotokyo.org/en/destinations/western-tokyo/shimokitazawa/index.html", 120, "NEIGHBORHOOD"),
  place("kappabashi", "Kappabashi kitchenware browsing", "Kitchenware & crafts walk", "shopping", ["SHOPPING", "FOOD_DRINK"], "Browse cooking tools, tableware and display-food shops along Kitchen Town. Individual shops are optional stops; this suggestion does not include a booked craft workshop.", "Kappabashi-dori, Taito", "https://www.gotokyo.org/en/see-and-do/shopping/index.html", 90, "NEIGHBORHOOD"),
  place("nezu", "Nezu-jinja Shrine", "Shrine", "heritage", ["CULTURE_HISTORY"], "Walk through the shrine precinct and the compact path of red torii gates. The azalea garden is seasonal; flowers are not promised for your travel dates.", "Nezu, Bunkyo", "https://www.gotokyo.org/en/spot/70/index.html", 45),
  place("kiyosumi", "Kiyosumi Gardens", "Landscape garden", "nature", ["NATURE_OUTDOORS"], "Circle the pond to see landscape stones, pines and waterside views. The stepping-stone sections offer a closer look at the water and need careful footing.", "Kiyosumi, Koto", "https://www.gotokyo.org/en/spot/25/index.html", 60),
  place("korakuen", "Koishikawa Korakuen", "Landscape garden", "nature", ["NATURE_OUTDOORS", "CULTURE_HISTORY"], "Follow paths between ponds, bridges and miniature landscapes inspired by Japanese and Chinese scenery. Seasonal colors vary with the date and weather.", "Koraku, Bunkyo", "https://www.gotokyo.org/en/spot/24/index.html", 75),
];
TOKYO_ADDITIONS.push(
  { ...place("tea-ceremony-2026", "Tokyo Grand Tea Ceremony 2026 · Hama-rikyu", "Dated tea event", "food-drink", ["FOOD_DRINK", "CULTURE_HISTORY"], "Join a tea-ceremony program in Hama-rikyu Gardens during this published two-day event. Individual sessions and tickets need an organizer check; a dated listing is not a reservation.", "Hama-rikyu Gardens, Chuo", "https://2026.tokyo-grand-tea-ceremony.jp/eng/index.html", 90), kind: "EVENT", event: { startDate: "2026-10-31", endDate: "2026-11-01", timeZone: "Asia/Tokyo", status: "PUBLISHED", observedAt, recheckAfter: "2026-10-07" }, sources: [{role:"official",url:"https://www.gotokyo.org/en/spot/ev044/index.html",observedAt,summary:"Tokyo’s official calendar lists the Hama-rikyu occurrence on October 31 and November 1, 2026, separate from the Koganei dates."}] },
  { ...place("roppongi-art-2026", "Roppongi Art Night 2026", "Dated art event", "immersive-art", ["ENTERTAINMENT", "CULTURE_HISTORY"], "Explore art installations and performances across Roppongi during the published event. Venues and individual programs have separate access conditions; no ticket availability is confirmed.", "Roppongi district, Minato", "https://www.roppongiartnight.com/2026/", 120), kind: "EVENT", event: { startDate: "2026-10-31", endDate: "2026-11-01", timeZone: "Asia/Tokyo", status: "PUBLISHED", observedAt, recheckAfter: "2026-10-07", timeNote: "Core overnight program: Oct 31 17:00–Nov 1 06:00 (Asia/Tokyo); individual programs vary." }, sources: [{role:"official",url:"https://www.mori.art.museum/en/news/2026/08/9015/index.html",observedAt,summary:"The participating Mori Art Museum announces the 2026 overnight program. Individual exhibition access remains separate."}] },
);
const source = (role: SourceRole, url: string, summary: string): ExperienceSource => ({ role, url, summary, observedAt });
export const LOCAL_CONTEXT: Record<string, ExperienceSource[]> = {
  "curated-hamarikyu": [source("local publication", "https://www.timeout.com/tokyo/restaurants/nakajima-no-ochaya-hama-rikyu-gardens", "Time Out Tokyo describes matcha and sweets at Nakajima-no-ochaya inside the garden. Garden admission is separate; current service and prices need checking.")],
  "curated-yanaka": [source("local publication", "https://whenin.tokyo/Yanaka-Area-Guide", "WHEN IN TOKYO’s neighborhood guide points beyond busy Yanaka Ginza to smaller art and cafe stops. This is editorial context, not a promise of an uncrowded visit.")],
  "curated-teamlab-planets": [source("traveler account", "https://www.reddit.com/r/JapanTravelTips/comments/1wl7xa5/teamlab_planets_2026_need_specifics_on_what/", "A September 2026 traveler discussion highlights barefoot access concerns for people with foot pain. Reports conflict about which areas permit shoes; consult the operator’s guidance.")],
  "curated-pokemon-shibuya": [source("community", "https://www.reddit.com/r/pokeplush/comments/1j205om", "A plush-shopping discussion compares Shibuya, MEGA TOKYO and Tokyo DX and mentions similar stock. This limited public search observation does not verify current inventory.")],
  "curated-pokemon-mega-tokyo": [source("community", "https://www.reddit.com/r/pokeplush/comments/1j205om", "A plush-shopping discussion includes this Ikebukuro branch alongside other Tokyo branches. This limited public search observation is anecdotal, not current inventory.")],
  "curated-shibuya-sky": [source("traveler account", "https://www.reddit.com/r/JapanTravelTips/comments/1vuj5o4/shibuya_sky_rooftop/", "Travelers discuss rooftop closures in wind or bad weather. Confirm conditions with the operator; this is a caution, not a current closure report.")],
};
export const PILOT_FIRST = ["curated-sensoji", "curated-pokemon-shibuya", "curated-hamarikyu", "curated-shibuya-crossing", "curated-teamlab-planets", "curated-yanaka"];
export function catalogRank(id: string, fallback: number) { const i = PILOT_FIRST.indexOf(id); return i < 0 ? fallback + PILOT_FIRST.length : i; }
export function groupFor(place: CatalogPlace) {
  if (place.diversityGroup) return place.diversityGroup;
  if (/Temple|Shrine|Museum|museum|Castle/.test(place.category)) return "heritage";
  if (/Garden|park|garden/.test(place.category)) return "nature";
  return place.category;
}
