import { describe, expect, it } from "vitest";
import { emptyDetails, materialDetailsChange, parseItemDetails } from "./details-domain";
const base={...emptyDetails,title:"Synthetic walk",startMinute:540,durationMinutes:30,locationLabel:"Demo gate",referenceUrl:"https://example.com/",notes:"Bring water"};
describe("Narrow itinerary details",()=>{
 it("keeps omitted fields and deliberately clears null/empty optional fields",()=>{expect(parseItemDetails({title:"Renamed",notes:undefined},base,"ACTIVITY")).toEqual({...base,title:"Renamed"});expect(parseItemDetails({startMinute:null,durationMinutes:null,locationLabel:"",referenceUrl:null,notes:""},base,"ACTIVITY")).toEqual({...base,startMinute:null,durationMinutes:null,locationLabel:null,referenceUrl:null,notes:null});});
 it.each(["", "   ", "x".repeat(161), 123])("rejects invalid title %s",title=>expect(typeof parseItemDetails({title},base,"ACTIVITY")).toBe("string"));
 it.each([0,-1,1.5,"20",NaN,2147483648])("rejects invalid duration %s",durationMinutes=>expect(typeof parseItemDetails({durationMinutes},base,"ACTIVITY")).toBe("string"));
 it.each([-1,1440,1.5,"09:00"])("rejects invalid minute %s",startMinute=>expect(typeof parseItemDetails({startMinute},base,"ACTIVITY")).toBe("string"));
 it("keeps unknowns distinct from explicit zero time and requires positive Free Time duration",()=>{expect(parseItemDetails({startMinute:0,durationMinutes:null},base,"ACTIVITY")).toMatchObject({startMinute:0,durationMinutes:null});expect(typeof parseItemDetails({durationMinutes:null},base,"FREE_TIME")).toBe("string");expect(parseItemDetails({durationMinutes:1},base,"FREE_TIME")).toMatchObject({durationMinutes:1});});
 it.each(["javascript:alert(1)","https://user:secret@example.com","https://example.com/\npath","file:///tmp/test","https://example.com/"+"x".repeat(2048)])("rejects unsafe reference %s",referenceUrl=>expect(typeof parseItemDetails({referenceUrl},base,"ACTIVITY")).toBe("string"));
 it("accepts a safe URL without fetching it and bounds entered text",()=>{expect(parseItemDetails({referenceUrl:"https://example.com/test",locationLabel:" Demo station "},base,"ACTIVITY")).toMatchObject({locationLabel:"Demo station"});for(const patch of [{notes:"x".repeat(2001)},{locationLabel:"x".repeat(301)},{flexibility:"MAYBE"}])expect(typeof parseItemDetails(patch,base,"ACTIVITY")).toBe("string");});
 it.each([{dayId:"other"},{type:"HOTEL_REST"},{progress:"PENDING"},{sourceRecommendationId:null}])("rejects generic field editing %s",patch=>expect(typeof parseItemDetails(patch,base,"ACTIVITY")).toBe("string"));
 it("does not offer Activity-specific fields to other types",()=>expect(typeof parseItemDetails({locationLabel:"New station"},base,"TRANSPORTATION")).toBe("string"));
 it("distinguishes material changes from title/note/reference corrections",()=>{for(const patch of [{startMinute:600},{durationMinutes:40},{locationLabel:"South gate"},{flexibility:"FIXED" as const}])expect(materialDetailsChange(base,{...base,...patch})).toBe(true);for(const patch of [{title:"Typo fixed"},{notes:"Corrected"},{referenceUrl:"https://example.com/new"}])expect(materialDetailsChange(base,{...base,...patch})).toBe(false);});
});
