import { expect, test, type Page } from "@playwright/test";
import { getPrismaClient } from "@/src/lib/prisma";
import { seedDemoTrip, DEMO_TRIP_ID } from "../../prisma/seed-data";
import { seedDiscoverFixtures } from "../../prisma/discover-seed";
import { decideRecommendation } from "@/src/modules/discover/service";
import { scheduleAcceptedRecommendation } from "@/src/modules/itinerary/service";
import { createActivityReservation, markReservationBooked } from "@/src/modules/reservations/service";
import { getTravelPlanning, saveTravelPlan } from "@/src/modules/itinerary/travel/service";
const db=getPrismaClient();let ownedTrip:string|null=null;
function ok<T>(r:{ok:true;data:T}|{ok:false;error:unknown}):T{if(!r.ok)throw Error(JSON.stringify(r.error));return r.data;}
async function capture(page:Page,path:string){expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false);await page.screenshot({path,fullPage:true,style:".brand-bar { visibility: hidden; }"});}
test.afterEach(async()=>{if(ownedTrip)await db.trip.deleteMany({where:{id:ownedTrip}});ownedTrip=null;});
test.afterAll(async()=>{await db.$disconnect();});
for(const [device,width,height] of [["desktop",1280,900],["phone",390,844]] as const){
 test(device+" fresh Trip supports manual add/edit/move without Discover or seed",async({page},testInfo)=>{
  test.setTimeout(120_000);await page.setViewportSize({width,height});let visitedDiscover=false;page.on("framenavigated",frame=>{if(frame===page.mainFrame() && new URL(frame.url()).pathname.endsWith("/discover"))visitedDiscover=true;});
  await page.goto("/");await page.getByLabel("Destination",{exact:true}).fill("Synthetic coast");await page.locator('select[name="destinationScope"]').selectOption("COUNTRY_REGION");await page.getByLabel("Start date").fill("2031-06-01");await page.getByLabel("End date").fill("2031-06-02");await page.getByRole("button",{name:"Create trip",exact:true}).click();await expect(page).toHaveURL(/\/trips\/[^/?]+$/);ownedTrip=new URL(page.url()).pathname.split("/")[2];
  const tripId=ownedTrip;expect(await db.recommendation.count({where:{tripId}})).toBe(0);expect(await db.itineraryItem.count({where:{tripId}})).toBe(0);
  const nav=page.getByRole("navigation",{name:"Trip navigation"});await nav.getByRole("link",{name:"Itinerary",exact:true}).click();await expect(page.getByRole("heading",{name:"Your day timeline.",exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"Add activity",exact:true})).toBeVisible();await capture(page,testInfo.outputPath(device+"-fresh-empty.png"));
  const days=await db.day.findMany({where:{tripId},orderBy:{position:"asc"}}),add=page.getByRole("form",{name:"Add activity",exact:true});
  await page.getByRole("button",{name:"Add activity",exact:true}).focus();await page.keyboard.press("Enter");await expect(add.getByLabel("Item name",{exact:true})).toBeFocused();await expect(add.getByLabel("Activity day",{exact:true}).locator("option")).toHaveText(["2031-06-01 · Unassigned","2031-06-02 · Unassigned"]);
  await add.getByLabel("Item name",{exact:true}).fill("Synthetic river walk");await add.getByLabel("Planned start — optional",{exact:true}).fill("09:00");await add.getByLabel("Duration in minutes — optional",{exact:true}).fill("45");await add.getByLabel("Location / address — optional",{exact:true}).fill("Demo north gate");await add.getByLabel("Item notes — optional",{exact:true}).fill("Synthetic organizer note");await capture(page,testInfo.outputPath(device+"-manual-form.png"));await add.getByRole("button",{name:"Save activity",exact:true}).click();
  await expect(page.getByRole("heading",{name:"Synthetic river walk",exact:true})).toBeVisible();const firstId=(await db.itineraryItem.findFirstOrThrow({where:{tripId,title:"Synthetic river walk"}})).id,first=page.locator('article[aria-labelledby="item-'+firstId+'"]');await expect(first.getByRole("heading")).toBeFocused();await expect(first).toContainText("Manually entered activity");
  await page.getByRole("button",{name:"Add activity",exact:true}).click();await add.getByLabel("Item name",{exact:true}).fill("Synthetic quiet hour");await add.getByRole("button",{name:"Save activity",exact:true}).click();const second=page.getByRole("article",{name:"Synthetic quiet hour",exact:true});await expect(second).toContainText("Time not set");await expect(second).toContainText("Duration not set");await expect(second).toContainText("Location not entered");
  const secondId=(await db.itineraryItem.findFirstOrThrow({where:{tripId,title:"Synthetic quiet hour"}})).id;
  await first.getByRole("button",{name:"Edit Synthetic river walk",exact:true}).click();const edit=first.getByRole("form",{name:"Edit Synthetic river walk",exact:true});await edit.getByLabel("Item name",{exact:true}).fill("Synthetic riverside stroll");await edit.getByLabel("Planned start — optional",{exact:true}).fill("10:00");await edit.getByLabel("Duration in minutes — optional",{exact:true}).fill("60");await edit.getByLabel("Location / address — optional",{exact:true}).fill("Demo south gate");await edit.getByLabel("Item notes — optional",{exact:true}).fill("Updated synthetic note");await edit.getByLabel("Reference URL — optional",{exact:true}).fill("javascript:alert(1)");await edit.getByRole("button",{name:"Save changes",exact:true}).click();await expect(edit.getByRole("alert")).toContainText("HTTP or HTTPS");await expect(edit.getByRole("alert")).toBeFocused();await expect(edit.getByLabel("Item name",{exact:true})).toHaveValue("Synthetic riverside stroll");await expect(edit.getByLabel("Location / address — optional",{exact:true})).toHaveValue("Demo south gate");
  await edit.getByLabel("Reference URL — optional",{exact:true}).fill("https://example.com/synthetic-walk");await edit.getByRole("button",{name:"Save changes",exact:true}).click();await expect(first.getByRole("heading")).toHaveText("Synthetic riverside stroll");await expect(first.getByRole("heading")).toBeFocused();await page.reload();await expect(first.locator(".item-time")).toHaveText("10:00");await expect(first).toContainText("60 minutes");await expect(first).toContainText("Entered location: Demo south gate");await first.getByText("Notes and reference",{exact:true}).click();await expect(first).toContainText("Updated synthetic note");await expect(first.getByRole("link",{name:"Open entered reference"})).toHaveAttribute("href","https://example.com/synthetic-walk");
  expect(await db.itineraryItem.findUniqueOrThrow({where:{id:firstId}})).toMatchObject({title:"Synthetic riverside stroll",startMinute:600,durationMinutes:60,locationLabel:"Demo south gate",notes:"Updated synthetic note",sourceRecommendationId:null,progress:"PENDING"});
  await first.getByRole("button",{name:"Edit Synthetic riverside stroll",exact:true}).click();await first.getByRole("form",{name:"Edit Synthetic riverside stroll",exact:true}).getByLabel("Item name",{exact:true}).fill("Discard this draft");await first.getByRole("button",{name:"Cancel edit",exact:true}).click();await expect(first.getByRole("button",{name:"Edit Synthetic riverside stroll",exact:true})).toBeFocused();expect((await db.itineraryItem.findUniqueOrThrow({where:{id:firstId}})).title).toBe("Synthetic riverside stroll");
  await first.getByRole("button",{name:"Move Synthetic riverside stroll later",exact:true}).click();await expect.poll(async()=> (await db.itineraryItem.findUniqueOrThrow({where:{id:firstId}})).position).toBe(1);expect((await db.itineraryItem.findUniqueOrThrow({where:{id:secondId}})).position).toBe(0);
  await first.getByLabel("Move Synthetic riverside stroll to another day",{exact:true}).click();await first.getByLabel("Target day for Synthetic riverside stroll",{exact:true}).selectOption(days[1].id);await first.getByRole("button",{name:"Preview move",exact:true}).click();await first.getByRole("button",{name:"Confirm move",exact:true}).click();await expect.poll(async()=> (await db.itineraryItem.findUniqueOrThrow({where:{id:firstId}})).dayId).toBe(days[1].id);
  await nav.getByRole("link",{name:"Home",exact:true}).click();await expect(page).toHaveURL("/trips/"+tripId);await page.goBack();await expect(page.getByRole("heading",{name:"Your day timeline.",exact:true})).toBeVisible();await page.reload();await expect(first).toContainText("Synthetic riverside stroll");await expect(second).toContainText("Time not set");await expect(nav.getByRole("link")).toHaveText(["Home","Itinerary","Discover"]);await capture(page,testInfo.outputPath(device+"-manual-built.png"));
  expect(visitedDiscover).toBe(false);expect(await db.recommendation.count({where:{tripId}})).toBe(0);expect(await db.reservation.count({where:{tripId}})).toBe(0);expect(await db.itineraryItem.count({where:{tripId}})).toBe(2);
 });
 test(device+" Booked recommendation edit previews and preserves booking, source and travel inputs",async({page},testInfo)=>{
  test.setTimeout(120_000);await page.setViewportSize({width,height});await seedDemoTrip(db);await seedDiscoverFixtures(db);ownedTrip=DEMO_TRIP_ID;const tripId=ownedTrip;
  const day=await db.day.findFirstOrThrow({where:{tripId},orderBy:{position:"asc"}}),rec=await db.recommendation.findFirstOrThrow({where:{tripId},orderBy:{displayRank:"asc"}});ok(await decideRecommendation({tripId,tripSegmentId:rec.tripSegmentId,recommendationId:rec.id,outcome:"ACCEPTED"}));
  const itemId=ok(await scheduleAcceptedRecommendation({tripId,recommendationId:rec.id,dayId:day.id,startMinute:600,flexibility:"FIXED"})).id,rid=ok(await createActivityReservation({tripId,itineraryItemId:itemId,state:"CHECK_BACK",desiredDate:"2030-04-01",desiredStartMinute:600})).id;ok(await markReservationBooked({tripId,reservationId:rid,confirmedDate:"2030-04-01",confirmedStartMinute:600,confirmationReference:"SYNTHETIC-REFINEMENT"}));const t=ok(await getTravelPlanning(tripId)).find(t=>t.itemId===itemId)!;ok(await saveTravelPlan({tripId,itemId,token:t.token,originKind:"ENTERED",originLabel:"Demo starting point",travelMinutes:25,bufferMinutes:10,basis:"PLANNED",clockContext:"SAME_LOCAL_CLOCK"}));
  const beforeItem=await db.itineraryItem.findUniqueOrThrow({where:{id:itemId}}),beforeBooking=await db.reservation.findUniqueOrThrow({where:{id:rid}}),beforeDecision=await db.recommendationDecision.findUniqueOrThrow({where:{recommendationId:rec.id}}),beforeTravel=await db.itineraryTravelPlan.findUniqueOrThrow({where:{itemId}}),beforePlace=await db.place.findUniqueOrThrow({where:{id:rec.placeId}});
  await page.goto("/trips/"+tripId+"/itinerary?homeView=day&homeDay="+day.id);const item=page.locator('article[aria-labelledby="item-'+itemId+'"]');await expect(item.locator(".item-booking")).not.toHaveAttribute("open");await item.getByRole("button",{name:"Edit "+beforeItem.title,exact:true}).click();const form=item.getByRole("form",{name:"Edit "+beforeItem.title,exact:true});await form.getByLabel("Planned start — optional",{exact:true}).fill("10:30");await form.getByLabel("Duration in minutes — optional",{exact:true}).fill("75");await form.getByLabel("Location / address — optional",{exact:true}).fill("Synthetic new entrance");await form.getByRole("button",{name:"Save changes",exact:true}).click();const preview=form.getByRole("region",{name:"Review item changes",exact:true});await expect(preview).toBeFocused();await expect(preview).toContainText("This changes your plan, not your booking.");await expect(preview).toContainText("Before: 10:00");await expect(preview).toContainText("After: 10:30");expect(await db.itineraryItem.findUniqueOrThrow({where:{id:itemId}})).toEqual(beforeItem);await capture(page,testInfo.outputPath(device+"-protected-preview.png"));await form.getByRole("button",{name:"Cancel edit",exact:true}).click();expect(await db.itineraryItem.findUniqueOrThrow({where:{id:itemId}})).toEqual(beforeItem);
  await item.getByRole("button",{name:"Edit "+beforeItem.title,exact:true}).click();await form.getByLabel("Planned start — optional",{exact:true}).fill("10:30");await form.getByLabel("Duration in minutes — optional",{exact:true}).fill("75");await form.getByLabel("Location / address — optional",{exact:true}).fill("Synthetic new entrance");await form.getByRole("button",{name:"Save changes",exact:true}).click();await form.getByRole("button",{name:"Confirm changes",exact:true}).focus();await page.keyboard.press("Enter");await expect(item.locator(".item-time")).toHaveText("10:30");await expect(item.locator(".reservation-attention")).toContainText("Confirmed time differs");await expect(item.locator(".reservation-state")).toHaveText("Reservation: Booked");await item.locator(".travel-planning > summary").click();await expect(item.getByText("Travel estimate needs review",{exact:true})).toBeVisible();await expect(item.locator(".leave-by")).toHaveCount(0);await capture(page,testInfo.outputPath(device+"-booked-edited.png"));await page.reload();await expect(item.locator(".item-time")).toHaveText("10:30");
  expect(await db.reservation.findUniqueOrThrow({where:{id:rid}})).toEqual(beforeBooking);expect(await db.recommendationDecision.findUniqueOrThrow({where:{recommendationId:rec.id}})).toEqual(beforeDecision);expect(await db.place.findUniqueOrThrow({where:{id:rec.placeId}})).toEqual(beforePlace);expect(await db.itineraryTravelPlan.findUniqueOrThrow({where:{itemId}})).toEqual(beforeTravel);expect(await db.itineraryItem.findUniqueOrThrow({where:{id:itemId}})).toMatchObject({id:itemId,sourceRecommendationId:rec.id,progress:beforeItem.progress,dayId:beforeItem.dayId,position:beforeItem.position});
 });
}
