import { expect, test } from "@playwright/test";
import { getPrismaClient } from "@/src/lib/prisma";
import { DEMO_TRIP_ID, seedDemoTrip } from "../../prisma/seed-data";
import { seedDiscoverFixtures } from "../../prisma/discover-seed";
const prisma = getPrismaClient();
test.beforeEach(async () => {
  await seedDemoTrip(prisma);
  await seedDiscoverFixtures(prisma);
});
test.afterAll(async () => {
  await prisma.trip.deleteMany({ where: { id: DEMO_TRIP_ID } });
  await prisma.$disconnect();
});

for (const [device, width, height] of [["desktop", 1280, 900], ["phone", 390, 844]] as const) {
  test(device + " interests and decisions refine only new batches", async ({ page }, testInfo) => {
    test.setTimeout(60_000);
    await page.setViewportSize({ width, height });
    await page.goto("/trips/" + DEMO_TRIP_ID + "/discover");
    const nav = page.getByRole("navigation", { name: "Trip navigation" });
    await expect(nav.getByRole("link")).toHaveText(["Home", "Itinerary", "Discover"]);
    await expect(page.locator(".prototype-badge")).toHaveText("Prototype");
    const first = page.getByRole("region", { name: "Batch 1 of 3" });
    await expect(first.getByRole("article")).toHaveCount(4);
    const firstNames = await first.getByRole("heading", { level: 3 }).allTextContents();
    const interests = page.locator("details.trip-interests");
    await interests.locator("summary").click();
    await interests.getByLabel("Architecture & design", { exact: true }).check();
    await interests.getByLabel("Culture & history", { exact: true }).check();
    await interests.getByRole("button", { name: "Save interests" }).click();
    await expect(interests).toContainText("Trip interests saved.");
    await expect(interests.getByRole("button", { name: "Save interests" })).toBeEnabled();
    await expect(first.getByRole("heading", { level: 3 })).toHaveText(firstNames);
    await first.getByRole("button", { name: "Accept Contemporary Design Museum", exact: true }).click();
    await first.getByRole("button", { name: "Deny Old Market Food Hall", exact: true }).click();
    const accepted = page.getByRole("region", { name: "Accepted", exact: true });
    await expect(accepted.getByRole("heading", { level: 3 })).toHaveText(["Contemporary Design Museum"]);
    const screenshot = async (name: string) => {
      expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false);
      await page.evaluate(() => window.scrollTo(0, 0));
      await page.screenshot({ path: testInfo.outputPath(device + "-" + name + ".png"), fullPage: true });
    };
    await screenshot("interests");
    await page.getByRole("button", { name: "Show another batch", exact: true }).click();
    const second = page.getByRole("region", { name: "Batch 2 of 3" });
    const secondNames = ["Brickwork Design Studio", "Railway History Gallery", "Courtyard Architecture Gallery", "City Garden Pavilion"];
    await expect(second.getByRole("heading", { level: 3 })).toHaveText(secondNames);
    await page.reload();
    await expect(second.getByRole("heading", { level: 3 })).toHaveText(secondNames);
    await interests.locator("summary").click();
    await expect(interests.getByLabel("Architecture & design", { exact: true })).toBeChecked();
    await interests.getByLabel("Architecture & design", { exact: true }).uncheck();
    await interests.getByLabel("Culture & history", { exact: true }).uncheck();
    await interests.getByLabel("Food & drink", { exact: true }).check();
    await interests.getByRole("button", { name: "Save interests" }).click();
    await expect(interests).toContainText("Trip interests saved.");
    await expect(interests.getByRole("button", { name: "Save interests" })).toBeEnabled();
    await expect(second.getByRole("heading", { level: 3 })).toHaveText(secondNames);
    await expect(interests.getByLabel("Food & drink", { exact: true })).toBeChecked();
    await expect(interests.getByLabel("Architecture & design", { exact: true })).not.toBeChecked();
    await interests.screenshot({ path: testInfo.outputPath(device + "-saved-interest-controls.png") });
    await screenshot("refined-history");
    await page.getByRole("link", { name: "Previous batch" }).click();
    await expect(first.getByRole("heading", { level: 3 })).toHaveText(firstNames);
    await expect(page.getByRole("button", { name: "Show another batch" })).toHaveCount(0);
    await page.getByRole("link", { name: "Next generated batch" }).click();
    await expect(second.getByRole("heading", { level: 3 })).toHaveText(secondNames);
    await page.getByRole("button", { name: "Show another batch", exact: true }).click();
    const third = page.getByRole("region", { name: "Batch 3 of 3" });
    const thirdNames = ["Twilight Food Court", "Craft Street Arcade", "Canal Evening Promenade", "Listening Room Pavilion"];
    await expect(third.getByRole("heading", { level: 3 })).toHaveText(thirdNames);
    await expect(page.getByRole("status")).toHaveText("No more fixture recommendations.");
    await expect(page.getByRole("button", { name: "Show another batch" })).toHaveCount(0);
    await expect(page.getByText(/why this fits you|perfect for you|because you liked|you.ll love|strong match|recommended based on|match score/i)).toHaveCount(0);
    await expect(accepted).toContainText("Accepting an idea does not schedule or book it.");
    await screenshot("exhausted");
    await page.reload();
    await expect(third.getByRole("heading", { level: 3 })).toHaveText(thirdNames);
    await interests.locator("summary").click();
    await interests.getByRole("button", { name: "Clear interests" }).click();
    await expect(interests).toContainText("Trip interests saved.");
    await expect(interests.getByRole("button", { name: "Clear interests" })).toBeEnabled();
    await expect(interests.getByRole("checkbox", { checked: true })).toHaveCount(0);
    await page.reload();
    await interests.locator("summary").click();
    await expect(interests.getByRole("checkbox", { checked: true })).toHaveCount(0);
    await expect(third.getByRole("heading", { level: 3 })).toHaveText(thirdNames);
    await nav.getByRole("link", { name: "Home", exact: true }).click();
    await expect(page.locator(".segment-card")).toHaveCount(4);
    await nav.getByRole("link", { name: "Itinerary", exact: true }).click();
    await expect(page.locator(".day-row")).toHaveCount(15);
    await nav.getByRole("link", { name: "Discover", exact: true }).click();
    await expect(first.getByRole("heading", { level: 3 })).toHaveText(firstNames);
  });
}
