import { expect, test } from "@playwright/test";
import { getPrismaClient } from "@/src/lib/prisma";
import { seedDemoTrip, DEMO_TRIP_ID } from "../../prisma/seed-data";
import { seedDiscoverFixtures } from "../../prisma/discover-seed";
import { openItem, closeDetails } from "./composer-helpers";
const prisma = getPrismaClient();
test.beforeEach(async () => { await seedDemoTrip(prisma); await seedDiscoverFixtures(prisma); });
test.afterAll(async () => { await prisma.trip.deleteMany({ where: { id: DEMO_TRIP_ID } }); await prisma.$disconnect(); });
for (const [device, width, height] of [["desktop",1280,900],["phone",390,844]] as const) {
 test(device + " accepted idea schedules explicitly, persists, and becomes schedulable after removal", async ({page}, testInfo) => {
  test.setTimeout(90_000); await page.setViewportSize({width,height});
  await page.goto("/trips/" + DEMO_TRIP_ID + "/discover");
  const nav=page.getByRole("navigation",{name:"Trip navigation"}), title="Riverside Observation Deck";
  await expect(nav.getByRole("link")).toHaveText(["Home","Itinerary","Discover"]);
  await page.getByRole("button",{name:"Accept "+title,exact:true}).click();
  const accepted=page.getByRole("region",{name:"Accepted",exact:true});
  await expect(accepted.getByRole("heading",{name:title})).toBeVisible();
  expect(await prisma.itineraryItem.count({where:{tripId:DEMO_TRIP_ID}})).toBe(0);
  await nav.getByRole("link",{name:"Itinerary",exact:true}).click();
  const idea=page.locator(".idea-card").filter({has:page.getByRole("heading",{name:title,exact:true})});
  await expect(idea).toContainText("45 min");
  await expect(page.locator(".timeline-item")).toHaveCount(0);
  const add=idea.getByRole("button",{name:"Add to Day 1",exact:true});
  await add.focus(); await expect(add).toBeFocused(); await add.press("Enter");
  const row=page.locator(".timeline-item").filter({has:page.getByRole("heading",{name:title,exact:true})});
  await expect(row).toContainText("Any time");
  await expect(row).toContainText("45 min");
  expect(await prisma.reservation.count({where:{tripId:DEMO_TRIP_ID}})).toBe(0);
  const item=await openItem(page,title);
  await expect(item).toContainText("From a recommendation");
  await item.getByRole("button",{name:"Edit "+title,exact:true}).click();
  const form=item.getByRole("form",{name:"Edit "+title,exact:true});
  await form.getByLabel("Planned start — optional",{exact:true}).fill("09:30");
  await form.getByLabel("Planning flexibility",{exact:true}).selectOption("FIXED");
  await form.getByRole("button",{name:"Save changes",exact:true}).click();
  // Changing flexibility to Fixed is material and follows the existing preview contract.
  const confirm=form.getByRole("button",{name:"Confirm changes",exact:true});
  if(await confirm.count()) await confirm.click();
  await closeDetails(page); await expect(row).toContainText("09:30"); await expect(row).toContainText("Fixed");
  await page.reload(); await expect(row).toContainText("09:30");
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false);
  await page.screenshot({path:testInfo.outputPath(device+"-timeline.png"),fullPage:true});
  await nav.getByRole("link",{name:"Discover",exact:true}).click(); await expect(accepted.getByRole("heading",{name:title})).toBeVisible();
  await nav.getByRole("link",{name:"Home",exact:true}).click();
  await page.getByLabel("Start date",{exact:true}).fill("2030-04-02");
  await page.getByRole("button",{name:"Save trip details"}).click();
  await expect(page.getByText(/These dates still have scheduled itinerary items/)).toBeVisible();
  await page.reload(); await expect(page.getByLabel("Start date",{exact:true})).toHaveValue("2030-04-01");
  await nav.getByRole("link",{name:"Itinerary",exact:true}).click();
  await expect(page.getByLabel("Selected day").locator("option")).toHaveCount(15);
  await openItem(page,title); const remove=item.getByRole("button",{name:"Remove "+title+" from itinerary"});
  await remove.focus(); await expect(remove).toBeFocused(); await remove.press("Enter");
  await expect(row).toHaveCount(0); await expect(add).toBeEnabled();
  await nav.getByRole("link",{name:"Discover",exact:true}).click(); await expect(accepted.getByRole("heading",{name:title})).toBeVisible();
  await nav.getByRole("link",{name:"Itinerary",exact:true}).click(); await add.click();
  await expect(row).toContainText("Any time");
  const saved=await prisma.itineraryItem.findFirstOrThrow({where:{tripId:DEMO_TRIP_ID}});
  expect(saved).toMatchObject({startMinute:null,flexibility:"FLEXIBLE",progress:"PENDING"});
  expect(await prisma.reservation.count({where:{tripId:DEMO_TRIP_ID}})).toBe(0);
 });
}
