import { expect, test } from "@playwright/test";
import { getPrismaClient } from "@/src/lib/prisma";
import { seedDemoTrip, DEMO_TRIP_ID } from "../../prisma/seed-data";
import { seedDiscoverFixtures } from "../../prisma/discover-seed";
const db = getPrismaClient();
test.use({ actionTimeout: 10_000 });
test.beforeEach(async () => { await seedDemoTrip(db); await seedDiscoverFixtures(db); });
test.afterAll(async () => { await db.trip.deleteMany({ where: { id: DEMO_TRIP_ID } }); await db.$disconnect(); });
for (const [device, width, height] of [["desktop", 1280, 900], ["phone", 390, 844]] as const) {
  test(device + " planning blocks reorder, preview, cancel, confirm and explain conflicts", async ({ page }, testInfo) => {
    test.setTimeout(90_000);
    await page.setViewportSize({ width, height });
    await page.goto("/trips/" + DEMO_TRIP_ID + "/itinerary");
    const nav = page.getByRole("navigation", { name: "Trip navigation" });
    await expect(nav.getByRole("link")).toHaveText(["Home", "Itinerary", "Discover"]);
    const creator = page.getByRole("form", { name: "Add planning block" });
    const dayOne = page.locator(".timeline-day").filter({ has: page.locator("header").getByText("2030-04-01", { exact: true }) });
    const dayTwo = page.locator(".timeline-day").filter({ has: page.locator("header").getByText("2030-04-02", { exact: true }) });
    const order = () => dayOne.locator(".timeline-item h4");
    const free = dayOne.getByRole("article", { name: "Free time", exact: true });
    const rest = dayOne.getByRole("article", { name: "Hotel / Rest", exact: true });
    const transportTitle = "Train · Tokyo → Kyoto";
    const transport = dayOne.getByRole("article", { name: transportTitle, exact: true });
    await page.locator(".planning-block-creator > summary").click();
    const add = async (type: string, time: string, duration: string) => {
      await creator.getByLabel("Block type", { exact: true }).selectOption(type);
      await creator.getByLabel("Block day", { exact: true }).selectOption({ label: "2030-04-01 · Tokyo" });
      await creator.getByLabel("Block time — optional", { exact: true }).fill(time);
      await creator.getByLabel(/Duration in minutes/).fill(duration);
    };
    await add("FREE_TIME", "09:00", "60");
    await creator.getByRole("button", { name: "Add block", exact: true }).click();
    await expect(free).toBeVisible();
    await expect(free).toContainText("09:00");
    await add("HOTEL_REST", "10:00", "60");
    await creator.getByRole("button", { name: "Add block", exact: true }).click();
    await expect(rest).toBeVisible();
    await expect(dayOne.getByRole("region", { name: "Time warnings for 2030-04-01" })).toHaveCount(0);
    await add("TRANSPORTATION", "09:30", "30");
    await creator.getByLabel("Mode", { exact: true }).selectOption("TRAIN");
    await creator.getByLabel("Origin Segment — optional").selectOption("cmg00000000000000000000011");
    await creator.getByLabel("Destination Segment — optional").selectOption("cmg00000000000000000000012");
    await creator.getByLabel("Block flexibility", { exact: true }).selectOption("FIXED");
    await creator.getByLabel("Block notes — optional").fill("Synthetic transfer plan");
    expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false);
    await creator.screenshot({ path: testInfo.outputPath(device + "-transport-form.png") });
    await creator.getByRole("button", { name: "Add block", exact: true }).click();
    await expect(transport).toBeVisible();
    await expect(transport).toContainText("Mode: Train");
    await expect(transport).toContainText("Fixed");
    await expect(order()).toHaveText(["Free time", "Hotel / Rest", transportTitle]);
    const warnings = dayOne.getByRole("region", { name: "Time warnings for 2030-04-01" });
    await expect(warnings).toContainText("Free time (09:00–10:00) overlaps Train · Tokyo → Kyoto (09:30–10:00)");
    await page.reload();
    await expect(order()).toHaveText(["Free time", "Hotel / Rest", transportTitle]);
    await expect(free.getByRole("button", { name: "Move Free time earlier", exact: true })).toBeDisabled();
    await expect(transport.getByRole("button", { name: "Move " + transportTitle + " later", exact: true })).toBeDisabled();
    const later = free.getByRole("button", { name: "Move Free time later", exact: true });
    await later.focus(); await later.press("Enter");
    await expect(order()).toHaveText(["Hotel / Rest", "Free time", transportTitle]);
    await page.reload();
    await expect(order()).toHaveText(["Hotel / Rest", "Free time", transportTitle]);
    const earlier = free.getByRole("button", { name: "Move Free time earlier", exact: true });
    await earlier.focus(); await earlier.press("Enter");
    await expect(order()).toHaveText(["Free time", "Hotel / Rest", transportTitle]);
    await page.reload();
    await expect(order()).toHaveText(["Free time", "Hotel / Rest", transportTitle]);
    await expect(free).toContainText("09:00"); await expect(rest).toContainText("10:00");
    await transport.getByRole("button", { name: "Move " + transportTitle + " earlier", exact: true }).click();
    const fixedPreview = transport.getByRole("region", { name: "Preview move: " + transportTitle });
    await expect(fixedPreview).toContainText("This item is marked Fixed.");
    await expect(order()).toHaveText(["Free time", "Hotel / Rest", transportTitle]);
    await fixedPreview.getByRole("button", { name: "Cancel", exact: true }).click();
    await expect(fixedPreview).toHaveCount(0);
    await transport.locator("summary").click();
    await expect(transport.getByLabel("Target day for " + transportTitle).locator("option")).toHaveText(["Choose a day", ...[2, 3, 4, 5].map(day => "2030-04-0" + day + " · Tokyo")]);
    await transport.getByLabel("Target day for " + transportTitle).selectOption({ label: "2030-04-02 · Tokyo" });
    await transport.getByRole("button", { name: "Preview move", exact: true }).click();
    await expect(fixedPreview).toContainText("From: 2030-04-01");
    await expect(fixedPreview).toContainText("To: 2030-04-02");
    await expect(fixedPreview).toContainText("This item is marked Fixed.");
    await expect(fixedPreview).toContainText("No known time conflicts.");
    await expect(dayTwo.locator(".timeline-item")).toHaveCount(0);
    expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false);
    await fixedPreview.screenshot({ path: testInfo.outputPath(device + "-fixed-preview.png") });
    await fixedPreview.getByRole("button", { name: "Cancel", exact: true }).click();
    await expect(transport).toBeVisible();
    await expect(dayTwo.locator(".timeline-item")).toHaveCount(0);
    await transport.locator("summary").click();
    await transport.getByLabel("Target day for " + transportTitle).selectOption({ label: "2030-04-02 · Tokyo" });
    await transport.getByRole("button", { name: "Preview move", exact: true }).click();
    await fixedPreview.getByRole("button", { name: "Confirm move", exact: true }).click();
    await expect(transport).toHaveCount(0);
    await page.reload();
    const movedTransport = dayTwo.getByRole("article", { name: transportTitle, exact: true });
    await expect(movedTransport).toContainText("09:30"); await expect(movedTransport).toContainText("Fixed");
    await expect(dayOne.locator(".timeline-item")).toHaveCount(2);
    await free.locator("summary").click();
    await free.getByLabel("Target day for Free time").selectOption({ label: "2030-04-02 · Tokyo" });
    await free.getByRole("button", { name: "Preview move", exact: true }).click();
    const overlap = free.getByRole("region", { name: "Preview move: Free time" });
    await expect(overlap).toContainText("overlaps");
    await expect(dayTwo.locator(".timeline-item")).toHaveCount(1);
    await overlap.getByRole("button", { name: "Confirm move", exact: true }).click();
    await expect(dayTwo.locator(".timeline-item h4")).toHaveText([transportTitle, "Free time"]);
    await expect(dayTwo.getByRole("region", { name: "Time warnings for 2030-04-02" })).toContainText("overlaps");
    await page.reload();
    await expect(dayTwo.locator(".timeline-item h4")).toHaveText([transportTitle, "Free time"]);
    for (const card of await page.locator(".timeline-item").all()) await expect(card).not.toContainText(/Booked|Paid|Completed/);
    expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false);
    await dayTwo.screenshot({ path: testInfo.outputPath(device + "-conflict-timeline.png") });
  });
}
