import { expect, test } from "@playwright/test";
import { getPrismaClient } from "@/src/lib/prisma";
import { seedDemoTrip, DEMO_TRIP_ID } from "../../prisma/seed-data";
import { seedDiscoverFixtures } from "../../prisma/discover-seed";
import { openItem, closeDetails, chooseDay } from "./composer-helpers";
const db=getPrismaClient();
test.beforeEach(async()=>{await seedDemoTrip(db);await seedDiscoverFixtures(db);});
test.afterAll(async()=>{await db.trip.deleteMany({where:{id:DEMO_TRIP_ID}});await db.$disconnect();});
for(const [device,width,height] of [["desktop",1280,900],["phone",390,844]] as const) {
 test(device+" planning blocks reorder, preview, cancel, confirm and explain conflicts",async({page},testInfo)=>{
  test.setTimeout(120_000);await page.setViewportSize({width,height});await page.goto("/trips/"+DEMO_TRIP_ID+"/itinerary");
  await expect(page.getByRole("navigation",{name:"Trip navigation"}).getByRole("link")).toHaveText(["Home","Itinerary","Discover"]);
  await page.getByRole("button",{name:"+ Rest, free time or transport",exact:true}).click();
  const creator=page.getByRole("form",{name:"Add planning block"}), drawer=page.getByRole("dialog");
  const add=async(type:string,time:string,duration:string)=>{
    await creator.getByLabel("Block type",{exact:true}).selectOption(type);
    await expect(creator.getByLabel("Block day",{exact:true}).locator("option:checked")).toHaveText("2030-04-01 · Tokyo");
    await creator.getByLabel("Block time — optional",{exact:true}).fill(time);
    await creator.getByLabel(/Duration in minutes/).fill(duration);
  };
  await add("FREE_TIME","09:00","60");await creator.getByRole("button",{name:"Add block",exact:true}).click();
  await expect(page.locator(".timeline-item")).toHaveCount(1);
  await add("HOTEL_REST","10:00","60");await creator.getByRole("button",{name:"Add block",exact:true}).click();
  await expect(page.locator(".timeline-item")).toHaveCount(2);
  await expect(page.getByRole("region",{name:"Time warnings for 2030-04-01"})).toHaveCount(0);
  await add("TRANSPORTATION","09:30","30");await creator.getByLabel("Mode",{exact:true}).selectOption("TRAIN");
  await creator.getByLabel("Origin Segment — optional").selectOption("cmg00000000000000000000011");
  await creator.getByLabel("Destination Segment — optional").selectOption("cmg00000000000000000000012");
  await creator.getByLabel("Block flexibility",{exact:true}).selectOption("FIXED");await creator.getByLabel("Block notes — optional").fill("Synthetic transfer plan");
  await creator.getByRole("button",{name:"Add block",exact:true}).click();await expect(page.locator(".timeline-item")).toHaveCount(3);
  const persistedTransport=await db.itineraryItem.findFirstOrThrow({where:{tripId:DEMO_TRIP_ID,type:"TRANSPORTATION"}});
  expect(persistedTransport).toMatchObject({transportationMode:"TRAIN",notes:"Synthetic transfer plan",flexibility:"FIXED",originSegmentId:"cmg00000000000000000000011",destinationSegmentId:"cmg00000000000000000000012"});
  await closeDetails(page);
  const title="Train · Tokyo → Kyoto",order=page.locator(".timeline-item h3");
  await expect(order).toHaveText(["Free time","Hotel / Rest",title]);
  await expect(page.getByRole("region",{name:"Time warnings for 2030-04-01"})).toContainText("Free time (09:00–10:00) overlaps Train · Tokyo → Kyoto (09:30–10:00)");
  await page.reload();await expect(order).toHaveText(["Free time","Hotel / Rest",title]);
  await openItem(page,"Free time");await expect(drawer.getByRole("button",{name:"Move Free time earlier",exact:true})).toBeDisabled();
  await drawer.getByRole("button",{name:"Move Free time later",exact:true}).focus();await page.keyboard.press("Enter");
  await expect(order).toHaveText(["Hotel / Rest","Free time",title]);await page.reload();
  await expect(order).toHaveText(["Hotel / Rest","Free time",title]);
  await drawer.getByRole("button",{name:"Move Free time earlier",exact:true}).focus();await page.keyboard.press("Enter");
  await expect(order).toHaveText(["Free time","Hotel / Rest",title]);await closeDetails(page);await page.reload();
  await expect(page.locator(".timeline-item").filter({hasText:"Free time"})).toContainText("09:00");
  await expect(page.locator(".timeline-item").filter({hasText:"Hotel / Rest"})).toContainText("10:00");
  await openItem(page,title);await expect(drawer.getByRole("button",{name:"Move "+title+" later",exact:true})).toBeDisabled();
  await drawer.getByRole("button",{name:"Move "+title+" earlier",exact:true}).click();
  const preview=drawer.getByRole("region",{name:"Preview move: "+title});
  await expect(preview).toContainText("This item is marked Fixed.");await expect(order).toHaveText(["Free time","Hotel / Rest",title]);
  await preview.getByRole("button",{name:"Cancel",exact:true}).click();await expect(preview).toHaveCount(0);
  const startMove=async()=>{await drawer.getByLabel("Move "+title+" to another day",{exact:true}).click();
    await expect(drawer.getByLabel("Target day for "+title).locator("option")).toHaveText(["Choose a day",...[2,3,4,5].map(d=>"2030-04-0"+d+" · Tokyo")]);
    await drawer.getByLabel("Target day for "+title).selectOption({label:"2030-04-02 · Tokyo"});
    await drawer.getByRole("button",{name:"Preview move",exact:true}).click();};
  await startMove();await expect(preview).toContainText("From: 2030-04-01");await expect(preview).toContainText("To: 2030-04-02");
  await expect(preview).toContainText("No known time conflicts.");
  await preview.getByRole("button",{name:"Cancel",exact:true}).click();
  expect(await db.itineraryItem.count({where:{tripId:DEMO_TRIP_ID,day:{date:new Date("2030-04-02T00:00:00Z")}}})).toBe(0);
  await startMove();await preview.getByRole("button",{name:"Confirm move",exact:true}).click();
  await expect.poll(()=>db.itineraryItem.count({where:{tripId:DEMO_TRIP_ID,day:{date:new Date("2030-04-01T00:00:00Z")}}})).toBe(2);await chooseDay(page,2);
  await expect(order).toHaveText([title]);await expect(page.locator(".timeline-item")).toContainText("09:30");
  await expect(page.locator(".timeline-item")).toContainText("Fixed");await chooseDay(page,1);
  await openItem(page,"Free time");await drawer.getByLabel("Move Free time to another day",{exact:true}).click();
  await drawer.getByLabel("Target day for Free time").selectOption({label:"2030-04-02 · Tokyo"});
  await drawer.getByRole("button",{name:"Preview move",exact:true}).click();
  const overlap=drawer.getByRole("region",{name:"Preview move: Free time"});await expect(overlap).toContainText("overlaps");
  await overlap.getByRole("button",{name:"Confirm move",exact:true}).click();await expect.poll(()=>db.itineraryItem.count({where:{tripId:DEMO_TRIP_ID,day:{date:new Date("2030-04-01T00:00:00Z")}}})).toBe(1);
  await chooseDay(page,2);await expect(order).toHaveText([title,"Free time"]);
  await expect(page.getByRole("region",{name:"Time warnings for 2030-04-02"})).toContainText("overlaps");await page.reload();
  await expect(order).toHaveText([title,"Free time"]);expect(await db.reservation.count({where:{tripId:DEMO_TRIP_ID}})).toBe(0);
  for(const row of await page.locator(".timeline-item").all()) await expect(row).not.toContainText(/Booked|Paid|Completed/);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false);
  await page.screenshot({path:testInfo.outputPath(device+"-conflict-timeline.png"),fullPage:true});
 });
}
