import { test,expect } from "@playwright/test";
import { createTrip } from "../../src/modules/trips/service";
import { getPrismaClient } from "../../src/lib/prisma";
const db=getPrismaClient();const fixtureTrips:string[]=[];const fixtureLists:string[]=[];

test("supported outing remains readable after saving, moving and reopening with providers disabled",async({page})=>{
 const r=await createTrip({destinationLabel:"Cedar Borough",destinationScope:"CITY_BASE",startDate:"2033-06-01",endDate:"2033-06-05",travelerCount:1});if(!r.ok)throw Error("Fixture failed");const id=r.data!.trip.id;fixtureTrips.push(id);
 const providerRequests:string[]=[];page.on("request",request=>{if(/places\.googleapis|maps\.googleapis|api\.openai|api\.search\.brave/.test(request.url()))providerRequests.push(request.url());});
 await page.goto(`/trips/${id}/itinerary`);const app=page.getByRole("region",{name:"Paste-first trip organizer"});
 await app.getByRole("button",{name:"Paste activities",exact:true}).click();await app.getByLabel("Original planning text").fill("Cedar Borough:\n- Market\nOuting: River outing\nSequence: 1\nDescription: Browse the supplied food stalls.\n- Gallery\nOuting: River outing\nSequence: 2\nDescription: View the supplied collection.\nDecision: Choose the gallery ticket\n- Coast or hills\n");
 await app.getByRole("button",{name:"Review paste"}).click();await expect(app.getByText("Import review · 3 items")).toBeVisible();await app.getByRole("button",{name:"Save ideas to Not scheduled"}).click();await app.getByRole("button",{name:/^Organize my list/}).click();await app.getByRole("button",{name:"Confirm and save arrangement"}).click();
 const day=app.getByRole("region",{name:"Plan 2033-06-02",exact:true});await expect(day.getByRole("heading",{name:"River outing",exact:true})).toBeVisible();await expect(day).toContainText("Browse the supplied food stalls.");await expect(day).toContainText("Suggested period");await expect(day).toContainText("Choose the gallery ticket");await expect(app.getByRole("region",{name:"Not scheduled",exact:true})).toContainText("Coast or hills");
 const gallery=await db.itineraryItem.findFirstOrThrow({where:{tripId:id,title:"Gallery"}}),target=await db.day.findFirstOrThrow({where:{tripId:id,date:new Date("2033-06-03T00:00:00Z")}});
 await day.getByRole("article").filter({has:page.getByRole("heading",{name:"Gallery",exact:true})}).getByRole("button",{name:"Move to",exact:true}).click();const move=app.getByRole("region",{name:"Move activity",exact:true});await move.getByRole("combobox",{name:"Move to",exact:true}).selectOption(target.id);await move.getByRole("button",{name:"Move activity",exact:true}).click();await expect(app.getByRole("region",{name:"Plan 2033-06-03",exact:true})).toContainText("Only Gallery from");await page.reload();await expect(day).not.toContainText("Choose the gallery ticket");await expect(app.getByRole("region",{name:"Plan 2033-06-03",exact:true})).toContainText("Choose the gallery ticket");expect((await db.itineraryItem.findUniqueOrThrow({where:{id:gallery.id}})).dayId).toBe(target.id);expect(providerRequests).toEqual([]);
});
test.afterAll(async()=>{await db.organizerIdea.deleteMany({where:{tripId:{in:fixtureTrips}}});await db.importBatch.deleteMany({where:{tripId:{in:fixtureTrips}}});await db.trip.deleteMany({where:{id:{in:fixtureTrips}}});await db.importBatch.deleteMany({where:{id:{in:fixtureLists},tripId:null}});await db.$disconnect();});
test("synthetic organizer: durable import, lock, incremental apply and same-list gap",async({page})=>{
 const r=await createTrip({destinationLabel:"Harbor Town",destinationScope:"CITY_BASE",startDate:"2032-05-01",endDate:"2032-05-06",travelerCount:1});if(!r.ok)throw Error("Trip setup failed");const id=r.data!.trip.id;fixtureTrips.push(id);
 await page.goto(`/trips/${id}/itinerary`);const app=page.getByRole("region",{name:"Paste-first trip organizer"});
 await expect(app.getByRole("button",{name:"Lock itinerary",exact:true})).toBeVisible();
 await app.getByRole("button",{name:"Paste activities",exact:true}).click();await app.getByLabel("Original planning text").fill("Harbor Town:\n- Maritime museum — full day\n- Riverside market\n- Garden or gallery");await app.getByRole("button",{name:"Review paste",exact:true}).click();await expect(app.getByText("Import review · 3 items")).toBeVisible();await app.getByRole("button",{name:"Save ideas to Not scheduled"}).click();
 await expect.poll(()=>db.itineraryItem.count({where:{tripId:id}})).toBe(3);
 await app.getByRole("button",{name:/^Organize my list/}).click();await expect(app.getByRole("region",{name:"Arrangement preview"})).toBeVisible();await app.getByRole("button",{name:"Apply & lock"}).click();await expect(app.getByRole("button",{name:"Unlock itinerary",exact:true})).toBeVisible();
 const before=await db.itineraryItem.findMany({where:{tripId:id,dayId:{not:null}},orderBy:{id:"asc"}});expect(before.length).toBe(2);
 await app.getByRole("button",{name:"Paste activities",exact:true}).click();await app.getByLabel("Original planning text").fill("Harbor Town:\n- Lighthouse\n- Pottery studio");await app.getByRole("button",{name:"Review paste"}).click();await app.getByRole("button",{name:"Save ideas to Not scheduled"}).click();await expect(app.getByRole("button",{name:"Resync new activities (2 waiting)"})).toBeEnabled();await page.reload();await expect(app.getByRole("button",{name:"Unlock itinerary",exact:true})).toBeVisible();await expect(app.getByRole("button",{name:"Resync new activities (2 waiting)"})).toBeVisible();
 await app.getByRole("button",{name:/Resync new activities/}).click();await expect(app.getByRole("button",{name:"Apply & lock"})).toBeDisabled();expect(await db.itineraryItem.findMany({where:{tripId:id,dayId:{not:null}},orderBy:{id:"asc"}})).toEqual(before);await app.getByRole("button",{name:"Cancel preview"}).click();
 await app.getByRole("button",{name:"Unlock itinerary",exact:true}).click();await app.getByRole("button",{name:/Resync new activities/}).click();await app.getByRole("button",{name:"Apply & lock"}).click();await expect(app.getByRole("button",{name:"Unlock itinerary",exact:true})).toBeEnabled();await page.reload();await expect(app.getByRole("button",{name:"Unlock itinerary",exact:true})).toBeVisible();expect(await db.itineraryItem.count({where:{tripId:id}})).toBe(5);
 const day=await db.day.findFirstOrThrow({where:{tripId:id},orderBy:{position:"asc"}});await page.goto(`/trips/${id}/discover?gap=${day.id}`);await page.getByLabel("Confirm your starting point").fill("Owner-entered hotel");await page.getByRole("button",{name:"Find ideas",exact:true}).click();await expect(page.getByRole("heading",{name:"From your list"})).toBeVisible();await expect(page.getByRole("heading",{name:"Other ideas"})).toBeVisible();expect(await db.itineraryItem.count({where:{tripId:id}})).toBe(5);
});
test("synthetic booked activity: moving preserves its confirmation and association",async({page})=>{
 const r=await createTrip({destinationLabel:"Estuary City",destinationScope:"CITY_BASE",startDate:"2032-08-01",endDate:"2032-08-04",travelerCount:1});if(!r.ok)throw Error("Fixture failed");const id=r.data!.trip.id;fixtureTrips.push(id);
 await page.goto(`/trips/${id}/itinerary`);const app=page.getByRole("region",{name:"Paste-first trip organizer"});await app.getByRole("button",{name:"Paste activities",exact:true}).click();await app.getByLabel("Original planning text").fill("Estuary City:\n2032-08-02\n- Synthetic concert 19:30 booked");await app.getByRole("button",{name:"Review paste"}).click();await app.getByRole("checkbox",{name:/I confirm any explicit/}).check();await app.getByRole("button",{name:"Save ideas to Not scheduled"}).click();await app.getByRole("button",{name:/^Organize my list/}).click();await app.getByRole("button",{name:"Confirm and save arrangement"}).click();
 await expect(app.getByRole("region",{name:"Plan 2032-08-02"})).toContainText("Synthetic concert");
 const booking=await db.reservation.findFirstOrThrow({where:{tripId:id}});const saved=await db.itineraryItem.findFirstOrThrow({where:{tripId:id}});const day=await db.day.findFirstOrThrow({where:{tripId:id,date:new Date("2032-08-03T00:00:00Z")}});
 await app.getByRole("region",{name:"Plan 2032-08-02"}).getByRole("button",{name:"Move to",exact:true}).click();const move=app.getByRole("region",{name:"Move activity",exact:true});await move.getByRole("combobox",{name:"Move to",exact:true}).selectOption(day.id);await move.getByRole("button",{name:"Move activity",exact:true}).click();await expect(app.getByRole("region",{name:"Arrangement preview"})).toContainText("confirmed booking date");await app.getByRole("button",{name:"Confirm and save arrangement"}).click();await expect(app.getByRole("region",{name:"Plan 2032-08-03"})).toContainText("confirmed date conflicts with this Day");await page.reload();await expect(app.getByRole("region",{name:"Plan 2032-08-03"})).toContainText("confirmed date conflicts with this Day");expect(await db.reservation.findUnique({where:{id:booking.id}})).toEqual(booking);expect((await db.itineraryItem.findUniqueOrThrow({where:{id:saved.id}})).dayId).toBe(day.id);
});
test("synthetic undated list: persists city groups without inventing a Trip",async({page})=>{
 const text="Cedar Borough:\n- Pottery studio\n- Gallery or garden";
 const tripCount=await db.trip.count();
 await page.goto("/organize");await page.getByLabel("Planning text").fill(text);await page.getByRole("button",{name:"Organize by city",exact:true}).click();await expect(page.getByText("2 retained items · all Not scheduled")).toBeVisible();await page.getByRole("button",{name:"Save list without dates",exact:true}).click();await expect(page.getByRole("status")).toHaveText("List saved without dates.");
 const saved=await db.importBatch.findFirstOrThrow({where:{tripId:null,originalText:text}});fixtureLists.push(saved.id);expect(await db.trip.count()).toBe(tripCount);
 await page.reload();await page.getByRole("button",{name:"Cedar Borough · 2 items",exact:true}).click();await expect(page.getByLabel("Planning text")).toHaveValue(text);await expect(page.getByText("2 retained items · all Not scheduled")).toBeVisible();expect(await db.importBatch.count({where:{tripId:null,originalText:text}})).toBe(1);
});

test("ordinary dated paste preserves source sequences and protection after accepted save and reload",async({page})=>{
 const r=await createTrip({destinationLabel:"Cedar Borough",destinationScope:"CITY_BASE",startDate:"2033-06-01",endDate:"2033-06-05",travelerCount:1});if(!r.ok)throw Error("Fixture failed");const id=r.data!.trip.id;fixtureTrips.push(id);
 await page.goto(`/trips/${id}/itinerary`);const app=page.getByRole("region",{name:"Paste-first trip organizer"});await app.getByRole("button",{name:"Paste activities",exact:true}).click();const text="Cedar Borough: June 1–5\nPlaces to go:\nThu, Jun. 2\tMarket -> Gallery -> Shops\nJun. 3\n- Keep afternoon and evening free; no venue booked";await app.getByLabel("Original planning text").fill(text);await app.getByRole("button",{name:"Review paste",exact:true}).click();await expect(app.getByText("Import review · 4 items")).toBeVisible();await expect(app.getByRole("heading",{name:"Gallery",exact:true})).toBeVisible();expect(await db.itineraryItem.count({where:{tripId:id}})).toBe(0);
 await app.getByRole("button",{name:"Save ideas to Not scheduled",exact:true}).click();await expect(app.getByRole("button",{name:"Organize my list (4 waiting)",exact:true})).toBeVisible();await page.reload();await app.getByRole("button",{name:/^Organize my list/}).click();await app.getByRole("button",{name:"Apply & lock",exact:true}).click();await page.reload();await expect(app.getByRole("button",{name:"Unlock itinerary",exact:true})).toBeVisible();await expect(app.getByRole("region",{name:"Plan 2033-06-02",exact:true})).toContainText("Gallery");expect(await db.reservation.count({where:{tripId:id}})).toBe(0);expect((await db.importBatch.findFirstOrThrow({where:{tripId:id}})).originalText).toBe(text);
});

test("long multi-version text reviews one active version and retries without duplicates",async({page})=>{
 const r=await createTrip({destinationLabel:"Cedar Borough",destinationScope:"CITY_BASE",startDate:"2033-06-01",endDate:"2033-06-05",travelerCount:1});if(!r.ok)throw Error("Fixture failed");const id=r.data!.trip.id;fixtureTrips.push(id);const text="Original plan\nCedar Borough:\n- Earlier Museum\n"+"Historical reference. ".repeat(2300)+"\nRevised plan\nCedar Borough:\n- Revised Gallery";
 await page.goto(`/trips/${id}/itinerary`);const app=page.getByRole("region",{name:"Paste-first trip organizer"});for(let i=0;i<2;i++){await app.getByRole("button",{name:"Paste activities",exact:true}).click();await app.getByLabel("Original planning text").fill(text);await app.getByRole("button",{name:"Review paste",exact:true}).click();await expect(app.getByRole("heading",{name:"Revised Gallery",exact:true})).toBeVisible();await expect(app.getByRole("heading",{name:"Earlier Museum",exact:true})).toHaveCount(0);await app.getByRole("button",{name:"Save ideas to Not scheduled",exact:true}).click();await expect(app.getByRole("button",{name:"Organize my list (1 waiting)",exact:true})).toBeVisible();}expect(await db.itineraryItem.count({where:{tripId:id}})).toBe(1);expect(await db.importBatch.count({where:{tripId:id}})).toBe(1);
});
