import { expect, test } from "@playwright/test";
import { getPrismaClient } from "@/src/lib/prisma";
import { seedDemoTrip, DEMO_TRIP_ID } from "../../prisma/seed-data";
import { seedDiscoverFixtures } from "../../prisma/discover-seed";
const prisma = getPrismaClient();
test.beforeEach(async () => { await seedDemoTrip(prisma); await seedDiscoverFixtures(prisma); });
test.afterAll(async () => { await prisma.trip.deleteMany({ where: { id: DEMO_TRIP_ID } }); await prisma.$disconnect(); });
for (const [device, width, height] of [["desktop", 1280, 900], ["phone", 390, 844]] as const) {
  test(device + " reservation stays Check back through external handoff until explicit booking", async ({ page, context }, testInfo) => {
    test.setTimeout(90_000);
    await page.setViewportSize({ width, height });
    await page.goto("/trips/" + DEMO_TRIP_ID + "/discover");
    const nav = page.getByRole("navigation", { name: "Trip navigation" });
    const title = "Riverside Observation Deck";
    await page.getByRole("button", { name: "Accept " + title, exact: true }).click();
    await expect(page.getByRole("region", { name: "Accepted", exact: true }).getByRole("heading", { name: title })).toBeVisible();
    expect(await prisma.reservation.count({ where: { tripId: DEMO_TRIP_ID } })).toBe(0);
    await nav.getByRole("link", { name: "Itinerary", exact: true }).click();
    const idea = page.getByRole("region", { name: "Accepted ideas not scheduled" }).getByRole("article", { name: title });
    await idea.getByLabel("Day for " + title).selectOption({ label: "2030-04-01 · 1. Tokyo" });
    await idea.getByLabel("Time for " + title).fill("09:30");
    await idea.getByLabel("Flexibility for " + title).selectOption("FIXED");
    await idea.getByRole("button", { name: "Add " + title + " to itinerary" }).click();
    const item = page.locator(".timeline-item").filter({ has: page.getByRole("heading", { name: title, exact: true }) });
    await expect(item.locator(".item-time")).toHaveText("09:30");
    await expect(item.locator(".item-flexibility")).toHaveText("Fixed");
    expect(await prisma.reservation.count({ where: { tripId: DEMO_TRIP_ID } })).toBe(0);
    await item.getByText("Add reservation tracking", { exact: true }).click();
    const form = item.getByRole("form", { name: "Save reservation tracking" });
    await expect(form.getByLabel("Desired date")).toHaveValue("2030-04-01");
    await expect(form.getByLabel("Desired time")).toHaveValue("09:30");
    await expect(form.getByLabel("Reservation state").locator("option")).toHaveText(["Book now", "Opens later", "Check back", "Optional reservation", "No reservation needed", "Needs attention"]);
    await form.getByLabel("Reservation state").selectOption("CHECK_BACK");
    await form.getByLabel("Booking source label").fill("Development fixture");
    await form.getByLabel("Booking URL").fill("https://example.com/booking");
    await form.getByLabel("Reservation notes").fill("Synthetic reservation example");
    const noOverflow = async () => expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false);
    await noOverflow(); await form.screenshot({ style: ".brand-bar { visibility: hidden; }", path: testInfo.outputPath(device + "-reservation-form.png") });
    const save = form.getByRole("button", { name: "Save reservation tracking" });
    await save.focus(); await save.press("Enter");
    await expect(item.locator(".reservation-state")).toHaveText("Reservation: Check back");
    await page.reload();
    await expect(item.locator(".reservation-state")).toHaveText("Reservation: Check back");
    await expect(item).toContainText("Desired: 2030-04-01 · 09:30");
    await item.getByText("Availability and release evidence", { exact: true }).click();
    await item.getByText("Link availability evidence", { exact: true }).click();
    const evidenceForm = item.getByRole("form", { name: "Link evidence" });
    await evidenceForm.getByLabel("Availability evidence").selectOption({ label: "Ticket availability · Development Fixture Catalog · 2026-09-22" });
    await evidenceForm.getByRole("button", { name: "Link evidence", exact: true }).click();
    await expect(item.locator(".evidence-record")).toContainText("Development fixture · Not live");
    await expect(item.locator(".evidence-record")).toContainText("Ticket availability");
    const beforeHandoff = await prisma.reservation.findFirstOrThrow({ where: { tripId: DEMO_TRIP_ID } });
    expect(beforeHandoff.state).toBe("CHECK_BACK");
    await context.route("https://example.com/booking", route => route.fulfill({ status: 200, contentType: "text/html", body: "<h1>Controlled external booking fixture</h1>" }));
    const link = item.getByRole("link", { name: "Open booking site" });
    await expect(link).toHaveAttribute("target", "_blank"); await expect(link).toHaveAttribute("rel", "noopener noreferrer");
    const popupPromise = page.waitForEvent("popup"); await link.click(); const popup = await popupPromise;
    await expect(popup.getByRole("heading")).toHaveText("Controlled external booking fixture"); await popup.close();
    expect(await prisma.reservation.findUniqueOrThrow({ where: { id: beforeHandoff.id } })).toEqual(beforeHandoff);
    await page.reload(); await expect(item.locator(".reservation-state")).toHaveText("Reservation: Check back");
    await item.locator("summary").filter({ hasText: /^Mark booked$/ }).click();
    const confirmation = item.getByRole("form", { name: "Mark booked", exact: true });
    await confirmation.getByLabel("Confirmed date").fill("2030-04-01");
    await confirmation.getByLabel("Confirmed time").fill("10:30");
    await confirmation.getByLabel("Confirmation reference").fill("SYNTHETIC-ABC123");
    await confirmation.getByLabel("Booking note").fill("Synthetic confirmed booking");
    await noOverflow(); await confirmation.screenshot({ style: ".brand-bar { visibility: hidden; }", path: testInfo.outputPath(device + "-mark-booked-form.png") });
    await confirmation.getByRole("button", { name: "Mark booked", exact: true }).click();
    await expect(item.locator(".reservation-state")).toHaveText("Reservation: Booked");
    await page.reload();
    await expect(item.locator(".reservation-state")).toHaveText("Reservation: Booked");
    await expect(item).toContainText("Desired: 2030-04-01 · 09:30");
    await expect(item).toContainText("Confirmed: 2030-04-01 · 10:30");
    await expect(item).toContainText("Confirmation: SYNTHETIC-ABC123");
    await expect(item).toContainText("Confirmed reservation time differs from itinerary time");
    await expect(item).toContainText("Removing this Activity keeps its reservation and booking details");
    await expect(item.locator(".item-time")).toHaveText("09:30");
    await expect(item.getByText("Change reservation state", { exact: true })).toHaveCount(0);
    await expect(item.locator(".evidence-record")).toContainText("Development fixture · Not live");
    await expect(nav.getByRole("link")).toHaveText(["Home", "Itinerary", "Discover"]);
    const saved = await prisma.reservation.findUniqueOrThrow({ where: { id: beforeHandoff.id } });
    expect(saved).toMatchObject({ state: "BOOKED", desiredStartMinute: 570, confirmedStartMinute: 630, confirmationReference: "SYNTHETIC-ABC123" });
    expect(saved.desiredDate).toEqual(beforeHandoff.desiredDate);
    await noOverflow(); await item.screenshot({ style: ".brand-bar { visibility: hidden; }", path: testInfo.outputPath(device + "-booked-reservation.png") });
  });
}
