import { openItem, closeDetails } from "./composer-helpers";
import { expect, test } from "@playwright/test";
import { getPrismaClient } from "@/src/lib/prisma";
import { seedDemoTrip, DEMO_TRIP_ID } from "../../prisma/seed-data";
import { seedDiscoverFixtures } from "../../prisma/discover-seed";
import { decideRecommendation } from "@/src/modules/discover/service";
import { scheduleAcceptedRecommendation } from "@/src/modules/itinerary/service";
import { createActivityReservation } from "@/src/modules/reservations/service";
const db = getPrismaClient(), tripId = DEMO_TRIP_ID;
let reservationId: string, itemId: string;
const title = "Riverside Observation Deck";
test.beforeEach(async () => {
  await seedDemoTrip(db); await seedDiscoverFixtures(db);
  await db.evidenceRecord.deleteMany({ where: { source: { name: { startsWith: "S2 Synthetic" } } } });
  await db.source.deleteMany({ where: { name: { startsWith: "S2 Synthetic" } } });
  const rec = await db.recommendation.findFirstOrThrow({ where: { tripId }, orderBy: { displayRank: "asc" } });
  await decideRecommendation({ tripId, tripSegmentId: rec.tripSegmentId, recommendationId: rec.id, outcome: "ACCEPTED" });
  const day = await db.day.findFirstOrThrow({ where: { tripId }, orderBy: { date: "asc" } });
  const item = await scheduleAcceptedRecommendation({ tripId, recommendationId: rec.id, dayId: day.id, startMinute: 570, flexibility: "FIXED" });
  if (!item.ok) throw Error(item.error.message); itemId = item.data.id;
  const r = await createActivityReservation({ tripId, itineraryItemId: itemId, state: "CHECK_BACK", desiredDate: "2030-04-01", desiredStartMinute: 570, bookingUrl: "https://example.com/booking" });
  if (!r.ok) throw Error(r.error.message); reservationId = r.data.id;
});
test.afterAll(async () => {
  await db.trip.deleteMany({ where: { id: tripId } });
  await db.evidenceRecord.deleteMany({ where: { source: { name: { startsWith: "S2 Synthetic" } } } });
  await db.source.deleteMany({ where: { name: { startsWith: "S2 Synthetic" } } });
  await db.$disconnect();
});
for (const [device, width, height] of [["desktop", 1280, 900], ["phone", 390, 844]] as const) {
  test(device + " Home follow-up, release precision, retained cancellation and Transportation", async ({ page, context }, testInfo) => {
    test.setTimeout(180_000); await page.setViewportSize({ width, height });
    const nav = page.getByRole("navigation", { name: "Trip navigation" });
    const row = page.getByRole("article", { name: title, exact: true });
    const noOverflow = async () => expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false);
    const capture = async (name: string) => { await noOverflow(); await page.screenshot({ style: ".brand-bar { visibility: hidden; }", path: testInfo.outputPath(device + "-" + name + ".png"), fullPage: true }); };
    await page.goto("/trips/" + tripId);
    await expect(nav.getByRole("link")).toHaveText(["Home", "Itinerary", "Discover"]);
    const utility = page.getByRole("region", { name: "Trip utilities" }).getByRole("link", { name: "Reservations", exact: true });
    await utility.focus(); await utility.press("Enter");
    await expect(page.getByRole("heading", { name: "Reservations", exact: true })).toBeVisible();
    await expect(row).toContainText("No release information recorded"); await expect(row).toContainText("Check back");
    await expect(row.getByRole("link", { name: "View itinerary details" })).toHaveAttribute("href", "/trips/" + tripId + "/itinerary#item-" + itemId);
    await row.getByRole("link", { name: "View itinerary details" }).click();
    await expect(page).toHaveURL(new RegExp("#item-" + itemId + "$"));
    const item = page.getByRole("dialog");
    await revealBooking(item); await item.getByText("Availability and release evidence", { exact: true }).click();
    await expect(item.getByText("No release information recorded. Availability unknown.", { exact: true })).toBeVisible();
    await item.getByText("Record release observation", { exact: true }).click();
    const form = item.getByRole("form", { name: "Save release observation" });
    const addObservation = async (precision: string, name: string, fields: Record<string, string>) => {
      const count = await db.reservationEvidence.count({ where: { reservationId } });
      await form.getByLabel("Source name", { exact: true }).fill("S2 Synthetic " + name);
      await form.getByLabel("Source attribution").selectOption("DEVELOPMENT_FIXTURE");
      await form.getByLabel("Source URL — optional").fill("https://example.com/release");
      await form.getByLabel("Observation", { exact: true }).fill("Synthetic " + name + " observation. Not live.");
      await form.getByLabel("Availability observation").selectOption("UNAVAILABLE");
      await form.getByLabel("Release precision").selectOption(precision);
      await form.getByLabel("Observed date/time with UTC offset", { exact: true }).fill("2020-01-01T10:00+09:00");
      for (const [label, value] of Object.entries(fields)) await form.getByLabel(label, { exact: true }).fill(value);
      await noOverflow(); await form.getByRole("button", { name: "Save release observation" }).click();
      await expect.poll(() => db.reservationEvidence.count({ where: { reservationId } })).toBe(count + 1);
      await expect(form.getByLabel("Release precision")).toHaveValue("UNKNOWN");
      await expect(form.locator("[name=releaseDate], [name=releaseAt], [name=windowDescription], [name=windowStartDate], [name=windowEndDate]")).toHaveCount(0);
      await expect(item.locator(".reservation-state")).toHaveText("Reservation: Check back");
    };
    await addObservation("EXACT", "exact", { "Exact release date/time with UTC offset": "2099-03-01T10:00+09:00" });
    await expect(item.locator(".evidence-record").first()).toContainText("2099-03-01 · 10:00 UTC+09:00");
    await addObservation("DATE_ONLY", "date", { "Release date": "2099-03-02" });
    await expect(item.locator(".evidence-record").nth(1)).toContainText("Time not announced");
    await addObservation("UNKNOWN", "unknown", {});
    await expect(item.locator(".evidence-record").nth(2)).toContainText("Release timing unknown");
    await addObservation("NOT_ANNOUNCED", "not announced", {});
    await expect(item.locator(".evidence-record").nth(3)).toContainText("Source reports: release not announced");
    await addObservation("WINDOW", "window", { "Reported window description": "Sometime in early spring" });
    await expect(item.locator(".evidence-record").nth(4)).toContainText("Reported window: Sometime in early spring");
    await expect(item.locator(".evidence-record").first()).toContainText("Stale observation");
    await expect(item.locator(".evidence-record").first()).toContainText("Development fixture · Not live");
    await expect(item.locator(".reservation-attention")).toContainText("Conflicting evidence");
    await capture("release-evidence");
    await item.locator(".evidence-record").first().screenshot({ path: testInfo.outputPath(device + "-exact-observation.png") });
    await form.screenshot({ path: testInfo.outputPath(device + "-reset-observation-form.png") });
    const beforeHandoff = await db.reservation.findUniqueOrThrow({ where: { id: reservationId } });
    await context.route("https://example.com/booking", route => route.fulfill({ status: 200, contentType: "text/html", body: "<h1>Controlled booking fixture</h1>" }));
    const popupPromise = page.waitForEvent("popup"); await item.getByRole("link", { name: "Open booking site" }).click(); const popup = await popupPromise; await popup.close();
    expect(await db.reservation.findUniqueOrThrow({ where: { id: reservationId } })).toEqual(beforeHandoff);
    await revealBooking(item); await item.locator("summary").filter({ hasText: /^Mark booked$/ }).click();
    const booking = item.getByRole("form", { name: "Mark booked", exact: true });
    await booking.getByLabel("Confirmed date").fill("2030-04-01"); await booking.getByLabel("Confirmed time").fill("10:30");
    await booking.getByLabel("Confirmation reference").fill("SYNTHETIC-S2"); await booking.getByRole("button", { name: "Mark booked", exact: true }).click();
    await expect(item.locator(".reservation-state")).toHaveText("Reservation: Booked");
    await expect(item.locator(".reservation-attention")).toContainText("Confirmed time differs"); await expect(item.locator(".item-time")).toHaveText("09:30");
    await page.reload(); await expect(item.locator(".reservation-state")).toHaveText("Reservation: Booked");
    const history = await db.reservation.findUniqueOrThrow({ where: { id: reservationId } });
    await item.getByRole("button", { name: "Remove " + title + " from itinerary" }).click(); await expect(item).toHaveCount(0);
    await closeDetails(page); await nav.getByRole("link", { name: "Home", exact: true }).click(); await page.getByRole("link", { name: "Reservations", exact: true }).click();
    await expect(row).toContainText(title); await expect(row).toContainText("Not attached to an itinerary item"); await expect(row).toContainText("Booked");
    await row.getByText("Manage retained reservation", { exact: true }).click();
    const details = row.getByRole("region", { name: "Reservation details" });
    await expect(details).toContainText("SYNTHETIC-S2"); await expect(details).toContainText("Desired: 2030-04-01 · 09:30");
    await details.getByText("Edit reservation notes", { exact: true }).click();
    await details.getByLabel("Reservation notes", { exact: true }).fill("Retained and manageable"); await details.getByRole("button", { name: "Save reservation notes" }).click();
    await expect.poll(async () => (await db.reservation.findUniqueOrThrow({ where: { id: reservationId } })).notes).toBe("Retained and manageable");
    await details.getByText("Availability and release evidence", { exact: true }).click();
    await expect(details).toContainText("No eligible source Place"); await expect(details.locator(".evidence-record")).toHaveCount(5);
    await details.getByText("Availability and release evidence", { exact: true }).click();
    await details.getByText("Record cancellation", { exact: true }).click(); await details.getByRole("button", { name: "Review cancellation", exact: true }).click();
    const confirm = details.getByRole("form", { name: "Confirm cancellation record" });
    await expect(confirm.getByRole("checkbox")).toBeVisible();
    const beforeCancel = await db.reservation.findUniqueOrThrow({ where: { id: reservationId } });
    await confirm.getByRole("button", { name: "Cancel", exact: true }).click(); expect(await db.reservation.findUniqueOrThrow({ where: { id: reservationId } })).toEqual(beforeCancel);
    await details.getByRole("button", { name: "Review cancellation", exact: true }).click();
    await confirm.getByRole("checkbox").check(); await confirm.getByLabel("Cancellation note").fill("Synthetic external cancellation confirmed");
    await capture("cancellation-confirmation");
    await confirm.getByRole("button", { name: "Confirm cancellation record" }).click();
    await expect(page.locator(".cancelled-reservations > summary")).toHaveText("Cancelled reservations (1)");
    await page.locator(".cancelled-reservations > summary").click(); await row.getByText("Manage retained reservation", { exact: true }).click();
    await expect(details.locator(".reservation-state")).toHaveText("Reservation: Cancelled"); await expect(details).toContainText("SYNTHETIC-S2"); await expect(details).toContainText("Synthetic external cancellation confirmed");
    const cancelled = await db.reservation.findUniqueOrThrow({ where: { id: reservationId } });
    expect(cancelled).toMatchObject({ desiredDate: history.desiredDate, confirmedDate: history.confirmedDate, confirmedStartMinute: history.confirmedStartMinute, confirmationReference: history.confirmationReference, state: "CANCELLED", itineraryItemId: null });
    await capture("retained-cancelled");
    await page.getByRole("link", { name: "Back to Home" }).click(); await nav.getByRole("link", { name: "Itinerary", exact: true }).click();
    await page.getByRole("button",{name:"+ Rest, free time or transport",exact:true}).click(); const block = page.getByRole("form", { name: "Add planning block" });
    await block.getByLabel("Block type", { exact: true }).selectOption("TRANSPORTATION"); await block.getByLabel("Block day", { exact: true }).selectOption({ label: "2030-04-01 · Tokyo" });
    await block.getByLabel("Block time — optional", { exact: true }).fill("12:00"); await block.getByLabel("Mode", { exact: true }).selectOption("TRAIN");
    await block.getByRole("button", { name: "Add block", exact: true }).click();
    await expect(page.locator(".timeline-item").filter({hasText:"Train transportation"})).toHaveCount(1); await closeDetails(page); const transport = await openItem(page,"Train transportation");
    await transport.getByText("Add reservation tracking", { exact: true }).click();
    await expect(transport).toContainText("departure context"); const tracking = transport.getByRole("form", { name: "Save reservation tracking" });
    await tracking.getByRole("button", { name: "Save reservation tracking" }).click(); await expect(transport.locator(".reservation-state")).toHaveText("Reservation: Check back");
    await revealBooking(transport); await transport.getByText("Availability and release evidence", { exact: true }).click(); await expect(transport).toContainText("No release information recorded. Availability unknown."); await expect(transport.getByText("Record release observation", { exact: true })).toHaveCount(0);
    await transport.locator("summary").filter({ hasText: /^Mark booked$/ }).click(); const departure = transport.getByRole("form", { name: "Mark booked", exact: true });
    await departure.getByLabel("Confirmed date").fill("2030-04-01"); await departure.getByLabel("Confirmed time").fill("12:30"); await departure.getByRole("button", { name: "Mark booked", exact: true }).click();
    await expect(transport.locator(".reservation-state")).toHaveText("Reservation: Booked"); await expect(transport.locator(".item-time")).toHaveText("12:00");
    await expect(nav.getByRole("link")).toHaveText(["Home", "Itinerary", "Discover"]); await capture("transportation-booked");
    await transport.screenshot({ path: testInfo.outputPath(device + "-transportation-details.png") });
  });
}

async function revealBooking(item: import("@playwright/test").Locator) {
  const section = item.locator(".item-booking");
  if (await section.getAttribute("open") === null) await section.locator(":scope > summary").click();
}
