import { closeDetails } from "./composer-helpers";
import { expect, test } from "@playwright/test";
import { getPrismaClient } from "@/src/lib/prisma";
import { seedDemoTrip, DEMO_TRIP_ID } from "../../prisma/seed-data";
import { seedDiscoverFixtures } from "../../prisma/discover-seed";
import { decideRecommendation } from "@/src/modules/discover/service";
import { scheduleAcceptedRecommendation } from "@/src/modules/itinerary/service";
import { createPlanningBlock } from "@/src/modules/itinerary/builder-service";
import { createActivityReservation, markReservationBooked } from "@/src/modules/reservations/service";
const db = getPrismaClient(), tripId = DEMO_TRIP_ID;
let dayId: string, secondDayId: string, freeId: string, activityId: string, reservationId: string;
const title = "Riverside Observation Deck";
test.beforeEach(async () => {
  await seedDemoTrip(db); await seedDiscoverFixtures(db);
  const days = await db.day.findMany({ where: { tripId }, orderBy: { position: "asc" } });
  dayId = days[0].id; secondDayId = days[1].id;
  const free = await createPlanningBlock({ tripId, dayId, type: "FREE_TIME", durationMinutes: 45 });
  if (!free.ok) throw Error(free.error.message); freeId = free.data.id;
  const rec = await db.recommendation.findFirstOrThrow({ where: { tripId }, orderBy: { displayRank: "asc" } });
  await decideRecommendation({ tripId, tripSegmentId: rec.tripSegmentId, recommendationId: rec.id, outcome: "ACCEPTED" });
  const item = await scheduleAcceptedRecommendation({ tripId, recommendationId: rec.id, dayId, startMinute: 570, flexibility: "FIXED" });
  if (!item.ok) throw Error(item.error.message); activityId = item.data.id;
  const reservation = await createActivityReservation({ tripId, itineraryItemId: activityId, state: "CHECK_BACK" });
  if (!reservation.ok) throw Error(reservation.error.message); reservationId = reservation.data.id;
  const booked = await markReservationBooked({ tripId, reservationId, confirmedDate: "2030-04-01", confirmedStartMinute: 630, confirmationReference: "SYNTHETIC-TODAY" });
  if (!booked.ok) throw Error(booked.error.message);
  const rest = await createPlanningBlock({ tripId, dayId, type: "HOTEL_REST", startMinute: 60 });
  if (!rest.ok) throw Error(rest.error.message);
});
test.afterAll(async () => { await db.trip.deleteMany({ where: { id: tripId } }); await db.$disconnect(); });
for (const [device, width, height] of [["desktop",1280,900],["phone",390,844]] as const) {
  test(device + " explicit Day, progress, reversible booked skip and preserved context", async ({ page }, testInfo) => {
    test.setTimeout(120_000); page.setDefaultTimeout(15_000); await page.setViewportSize({ width, height });
    const nav = page.getByRole("navigation", { name: "Trip navigation" });
    const next = page.getByRole("region", { name: "Next in your plan", exact: true });
    const item = page.getByRole("article", { name: title, exact: true });
    const capture = async (name: string) => {
      expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false);
      await page.screenshot({ path: testInfo.outputPath(device + "-" + name + ".png"), fullPage: true, style: ".brand-bar { visibility: hidden; }" });
    };
    await page.goto("/trips/" + tripId);
    await expect(nav.getByRole("link")).toHaveText(["Home", "Itinerary", "Discover"]);
    const mode = page.getByRole("link", { name: "Today / Day view", exact: true });
    await mode.focus(); await mode.press("Enter");
    await expect(page.getByRole("heading", { name: "Choose a day", exact: true })).toBeVisible();
    await expect(next).toHaveCount(0);
    await page.getByLabel("Trip day", { exact: true }).selectOption(dayId);
    await page.getByRole("button", { name: "Show day", exact: true }).focus(); await page.keyboard.press("Enter");
    await expect(page.getByRole("heading", { name: "Day view · 2030-04-01", exact: true })).toBeVisible();
    await expect(next).toContainText("Free time"); await expect(next).toContainText("Time not set");
    await expect(page.getByRole("region", { name: "Remaining plan", exact: true }).getByRole("heading", { level: 3 })).toHaveText([title,"Hotel / Rest"]);
    const bookingBefore = await db.reservation.findUniqueOrThrow({ where: { id: reservationId } });
    const activityBefore = await db.itineraryItem.findUniqueOrThrow({ where: { id: activityId } });
    await item.getByText("Private trip booking details", { exact: true }).click();
    await expect(item).toContainText("SYNTHETIC-TODAY"); await expect(item).toContainText("Confirmed: 2030-04-01 · 10:30");
    await expect(item).toContainText("Planned: 2030-04-01 · 09:30"); await expect(item).toContainText("Confirmed time differs");
    await capture("selected-day");
    expect(await db.itineraryItem.findUniqueOrThrow({ where: { id: activityId } })).toEqual(activityBefore);
    await next.getByRole("button", { name: "Mark completed", exact: true }).focus(); await page.keyboard.press("Enter");
    await expect(next).toContainText(title); await page.reload(); await expect(next).toContainText(title);
    expect((await db.itineraryItem.findUniqueOrThrow({ where: { id: freeId } })).progress).toBe("COMPLETED");
    await item.getByRole("button", { name: "Skip item", exact: true }).click();
    const preview = item.getByRole("region", { name: "Skip preview: " + title, exact: true });
    await expect(preview).toContainText("This item is Fixed."); await expect(preview).toContainText("The reservation remains Booked.");
    await expect(preview).toContainText("contact a provider, or create a refund");
    await capture("skip-preview");
    await preview.getByRole("button", { name: "Cancel", exact: true }).focus(); await page.keyboard.press("Enter");
    await expect(preview).toHaveCount(0); expect(await db.itineraryItem.findUniqueOrThrow({ where: { id: activityId } })).toEqual(activityBefore);
    expect(await db.reservation.findUniqueOrThrow({ where: { id: reservationId } })).toEqual(bookingBefore);
    await item.getByRole("button", { name: "Skip item", exact: true }).click();
    await expect(preview.getByRole("checkbox")).toHaveAttribute("required", "");
    await preview.getByRole("checkbox").focus(); await page.keyboard.press("Space");
    await preview.getByRole("button", { name: "Confirm skip", exact: true }).click();
    await expect(next).toContainText("Hotel / Rest");
    await page.getByText("Completed / Skipped (2)", { exact: true }).click();
    await expect(item.locator(".progress-label")).toHaveText("Skipped"); await expect(item.locator(".reservation-state")).toHaveText("Reservation: Booked");
    await capture("processed");
    await item.getByRole("button", { name: "Restore to remaining plan", exact: true }).click();
    await expect(next).toContainText(title);
    const restored = await db.itineraryItem.findUniqueOrThrow({ where: { id: activityId } });
    expect(restored).toEqual({ ...activityBefore, progressChangedAt: expect.any(Date), progressActionKey: expect.any(String), revision: activityBefore.revision + 2, updatedAt: expect.any(Date) });
    expect(await db.reservation.findUniqueOrThrow({ where: { id: reservationId } })).toEqual(bookingBefore);
    await page.getByLabel("Trip day", { exact: true }).selectOption(secondDayId); await page.getByRole("button", { name: "Show day", exact: true }).click();
    await expect(page.getByRole("heading", { name: "Day view · 2030-04-02", exact: true })).toBeVisible();
    await expect(page.getByText("Nothing scheduled for this day.", { exact: false })).toBeVisible();
    await page.goBack(); await page.reload(); await expect(page.getByLabel("Trip day", { exact: true })).toHaveValue(dayId); await expect(next).toContainText(title);
    await item.getByRole("link", { name: "Manage this item in Itinerary", exact: true }).click();
    await expect(page).toHaveURL(new RegExp("#item-" + activityId + "$"));
    await expect(page.getByRole("dialog")).toContainText("Progress: Pending");
    await closeDetails(page); await nav.getByRole("link", { name: "Home", exact: true }).click(); await expect(next).toContainText(title); await expect(page.getByLabel("Trip day", { exact: true })).toHaveValue(dayId);
    await nav.getByRole("link", { name: "Discover", exact: true }).click();
    await page.getByRole("button", { name: "Show another batch", exact: true }).click();
    await page.getByRole("link", { name: "Previous batch", exact: true }).click();
    await page.getByLabel("Trip Segment").selectOption({ index: 1 });

    await closeDetails(page); await nav.getByRole("link", { name: "Home", exact: true }).click(); await expect(next).toContainText(title);
    await page.getByRole("link", { name: "Planning", exact: true }).click();
    await expect(page.getByRole("heading", { name: "Destination sequence", exact: true })).toBeVisible(); await expect(page.getByRole("link", { name: "Reservations", exact: true })).toBeVisible();
    await capture("planning-home");
    await page.getByRole("link", { name: "Reservations", exact: true }).click();
    await page.getByRole("link", { name: "View itinerary details", exact: true }).click();
    await closeDetails(page); await nav.getByRole("link", { name: "Home", exact: true }).click();
    await page.getByRole("link", { name: "Reservations", exact: true }).click();
    await page.getByRole("link", { name: "Back to Home", exact: true }).click();
    await page.getByRole("link", { name: "Today / Day view", exact: true }).click(); await expect(next).toContainText(title);
    await next.getByRole("button", { name: "Mark completed", exact: true }).click(); await expect(next).toContainText("Hotel / Rest");
    await next.getByRole("button", { name: "Skip item", exact: true }).click(); await next.getByRole("button", { name: "Confirm skip", exact: true }).click();
    await expect(page.getByText("No pending items for this day.", { exact: true })).toBeVisible(); await expect(page.getByText("Everything completed", { exact: true })).toHaveCount(0); await capture("no-pending");
  });
}
