"use client";
import Link from "next/link";
import { useState,useTransition } from "react";
import { gapIdeas, saveOtherIdea } from "@/src/modules/organizer/actions";
import { PERIODS } from "@/src/modules/organizer/domain";
export function FreeTimeIdeas({tripId,dayId}:{tripId:string;dayId:string}) {
 const [start,setStart]=useState(""),[minutes,setMinutes]=useState(120),[period,setPeriod]=useState("Afternoon"),[protectedTime,setProtected]=useState(false),[result,setResult]=useState<Extract<Awaited<ReturnType<typeof gapIdeas>>,{ok:true}>["data"]|null>(null),[status,setStatus]=useState(""),[pending,run]=useTransition();
 return <section className="card stack"><h2>Find something for this gap</h2><p>Stored ideas only. Your plan and bookings stay unchanged.</p><label>Confirm your starting point<input value={start} onChange={e=>setStart(e.target.value)} placeholder="Where will you start?"/></label><label>Available minutes<input type="number" min={1} max={1440} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><label>Period<select value={period} onChange={e=>setPeriod(e.target.value)}>{PERIODS.map(p=><option key={p} value={p}>{p||"Unspecified"}</option>)}</select></label><label><input type="checkbox" checked={protectedTime} onChange={e=>setProtected(e.target.checked)}/>I explicitly want ideas for this protected period (the protection stays unchanged).</label><button disabled={pending||!start.trim()} onClick={()=>run(async()=>{const r=await gapIdeas(tripId,dayId,start,minutes,period,protectedTime);if(r.ok){setResult(r.data);setStatus("Suggestions only · nothing added");}else{setResult(null);setStatus(r.error);}})}>Find ideas</button><p role="status">{pending?"Checking stored data…":status}</p>{result?<><p>{result.warning}</p><p>Known commitments: {result.commitments.join("; ")||"None recorded for this Day"}</p><h3>From your list</h3>{!result.own.length?<p>No eligible unscheduled items with a matching supplied city.</p>:result.own.map(i=><article className="card" key={i.id}><h4>{i.title}</h4><p>{i.notes}</p><p>Duration and transport fit remain uncertain. {i.booking?`Booking: ${i.booking.state}`:"Check whether tickets are needed."}</p><Link href={`/trips/${tripId}/itinerary`}>{result.locked?"Saved idea · unlock in itinerary to place":"Review Move to in itinerary"}</Link></article>)}<h3>Other ideas</h3>{result.others.map(i=><article className="card" key={i.id}><h4>{i.title}</h4><p>{i.description}</p><p>{i.warning}</p><button disabled={pending} onClick={()=>run(async()=>{const r=await saveOtherIdea(tripId,i.id);setStatus(r.ok?"Saved idea to Not scheduled. No placement or booking changed.":r.error);})}>Save idea</button></article>)}{!result.others.length?<p>No suitable independent stored recommendations with adequate matching data.</p>:null}</>:null}<Link href={`/trips/${tripId}/itinerary`}>Return to itinerary</Link></section>;
}
