"use client";
import Link from "next/link";
import { useEffect, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { parsePaste, PERIODS, type InputItem, type Placement } from "@/src/modules/organizer/domain";
import type { OrganizerWorkspace } from "@/src/modules/organizer/service";
import { applyOrganization, chooseIdea, importActivities, loadOrganizer, lockItinerary, moveActivity, organizeActivities, undoOrganization, updateIdeaNotes, ideaBookings } from "@/src/modules/organizer/actions";

import { ActivityReservation } from "./activity-reservation";
import type { ActivityReservationContext } from "@/src/modules/reservations/types";
type Proposal={placements:Placement[];token:string;warnings:string[]};
export function TripOrganizer({tripId,revision}:{tripId:string;revision:string}) {
  const [bookingContext,setBookingContext]=useState<ActivityReservationContext|null>(null); const [noteItem,setNoteItem]=useState<string>(""),[noteText,setNoteText]=useState("");
  const router=useRouter();const [w,setW]=useState<OrganizerWorkspace|null>(null),[text,setText]=useState(""),[review,setReview]=useState<InputItem[]|null>(null),[paste,setPaste]=useState(false),[selected,setSelected]=useState<string[]>([]),[proposal,setProposal]=useState<Proposal|null>(null),[undo,setUndo]=useState(""),[status,setStatus]=useState("Loading organizer…"),[pending,start]=useTransition(),[confirmBooked,setConfirmBooked]=useState(false),[repeat,setRepeat]=useState(false),[moveId,setMoveId]=useState(""),[target,setTarget]=useState(""),[period,setPeriod]=useState("");
  async function refresh(){const r=await loadOrganizer(tripId);if(r.ok){setW(r.data);setSelected(r.data.items.filter(i=>i.pending&&!i.dayId).map(i=>i.id));}else setStatus(r.error);}
  useEffect(()=>{let active=true;loadOrganizer(tripId).then(r=>{if(!active)return;if(r.ok){setW(r.data);setSelected(r.data.items.filter(i=>i.pending&&!i.dayId).map(i=>i.id));setStatus("Saved");}else setStatus(r.error);});return()=>{active=false;};},[tripId,revision]);
  const act=(fn:()=>Promise<void>)=>start(async()=>{setStatus("Saving…");try{await fn();}catch(e){setStatus("Failed: "+(e instanceof Error?e.message:"Please retry. Previous positions were retained."));}});
  const saved=async()=>{await refresh();router.refresh();setStatus("Saved");};
  async function apply(p:Proposal,relock=false){const r=await applyOrganization(tripId,p,relock);if(!r.ok)throw Error(r.error);setUndo(r.data.undo);setProposal(null);setMoveId("");await saved();}
  async function move(id:string,dayId:string|null,chosenPeriod:string,index?:number){const r=await moveActivity(tripId,id,dayId,chosenPeriod,index);if(!r.ok)throw Error(r.error);if(r.data.warnings.length){setProposal(r.data);setStatus("Review the scheduling consequence before applying.");}else await apply(r.data);}
  if(!w)return <section className="card"><p role="status">{status}</p></section>;
  const waiting=w.items.filter(i=>i.pending&&!i.dayId).length;
  const patch=(index:number,value:Partial<InputItem>)=>setReview(review!.map((item,i)=>i===index?{...item,...value}:item));
  return <section className="organizer stack" aria-label="Paste-first trip organizer">
    <header className="row row-between"><div><span className="eyebrow">Your choices, your itinerary</span><h2>Organize my list</h2></div><button aria-label={w.locked?"Unlock itinerary":"Lock itinerary"} disabled={pending} onClick={()=>act(async()=>{const r=await lockItinerary(tripId,w.token,!w.locked);if(!r.ok)throw Error(r.error);setProposal(null);await saved();})}>{w.locked?"Locked · Unlock":"Unlocked · Lock"}</button></header>
    <p>{w.locked?"The saved schedule is protected. Keep collecting ideas and tracking bookings.":"Paste your activities, review an arrangement, then save it. Nothing is booked for you."}</p>
    <div className="row"><button onClick={()=>setPaste(!paste)}>Paste activities</button><button className="secondary" disabled={pending||!waiting} onClick={()=>act(async()=>{const r=await organizeActivities(tripId,selected);if(!r.ok)throw Error(r.error);setProposal(r.data);setStatus("Preview only · saved itinerary unchanged");})}>{w.items.some(i=>i.dayId)?"Resync new activities":"Organize my list"} ({waiting} waiting)</button><Link href={`/trips/${tripId}/reservations`}>Trip bookings</Link>{undo&&!w.locked?<button className="secondary" disabled={pending} onClick={()=>act(async()=>{const r=await undoOrganization(tripId,undo);if(!r.ok)throw Error(r.error);setUndo("");await saved();})}>Undo recent change</button>:null}</div>
    <p role="status" aria-live="polite">{pending?"Saving…":status}</p>
    {paste?<section className="card stack"><h3>Paste activities</h3><p>City headings, one activity per line, ISO dates or month/day headings, 24-hour times, full-day intentions and “A or B” alternatives. Longer prose stays a note. Links are not fetched.</p><label>Original planning text<textarea rows={8} value={text} maxLength={40000} onChange={e=>setText(e.target.value)}/></label><button disabled={!text.trim()} onClick={()=>{try{setReview(parsePaste(text,[...new Set(w.days.map(d=>d.city))],Number(w.days[0]?.date.slice(0,4))||undefined));setStatus("Review every extracted line before saving.");}catch(e){setStatus(String(e));}}}>Review paste</button>
      {review?<><h3>Import review · {review.length} items</h3><p>Edit this list together. Blank means unknown. “Booked” is a supplied statement requiring your confirmation.</p><div className="import-review">{review.map((i,n)=><article className="card stack" key={n}><label>Name / retained note<input value={i.name} onChange={e=>patch(n,{name:e.target.value})}/></label><div className="organizer-fields"><label>City / area<input value={i.city} onChange={e=>patch(n,{city:e.target.value})}/></label><label>Supplied date<input type="date" value={i.date} onChange={e=>patch(n,{date:e.target.value})}/></label><label>Supplied time<input type="time" value={i.time} onChange={e=>patch(n,{time:e.target.value})}/></label><label>Period<select value={i.period} onChange={e=>patch(n,{period:e.target.value})}>{PERIODS.map(p=><option key={p} value={p}>{p||"Unknown"}</option>)}</select></label><label>Kind<select value={i.kind} onChange={e=>patch(n,{kind:e.target.value as InputItem["kind"]})}><option>ACTIVITY</option><option>NOTE</option><option>PROTECTED</option></select></label></div><label>Notes<textarea value={i.notes} onChange={e=>patch(n,{notes:e.target.value})}/></label><div className="row"><label><input type="checkbox" checked={i.priority} onChange={e=>patch(n,{priority:e.target.checked})}/>Priority</label><label><input type="checkbox" checked={i.alternative} onChange={e=>patch(n,{alternative:e.target.checked})}/>Optional alternative</label><label><input type="checkbox" checked={i.excluded} onChange={e=>patch(n,{excluded:e.target.checked})}/>Exclude explicitly</label></div><label>Booking interpretation<select value={i.booking} onChange={e=>patch(n,{booking:e.target.value as InputItem["booking"]})}><option value="">No booking record</option><option value="NEED_TICKETS">Not booked / need tickets</option><option value="BOOKED_STATEMENT">User-reported booked statement</option></select></label><details><summary>Original source fragment</summary><p>{i.fragment}</p></details>{w.items.some(x=>x.title.toLowerCase()===i.name.toLowerCase())?<p className="issue warning">Possible duplicate: retained for review unless you explicitly allow a repeat.</p>:null}</article>)}</div>
      <label><input type="checkbox" checked={confirmBooked} onChange={e=>setConfirmBooked(e.target.checked)}/>I confirm any explicit “booked” statements as my own reported bookings. This does not contact a supplier.</label><label><input type="checkbox" checked={repeat} onChange={e=>setRepeat(e.target.checked)}/>This is an intentional repeat visit/import.</label><button disabled={pending} onClick={()=>act(async()=>{const r=await importActivities(tripId,text,review,repeat?crypto.randomUUID():"",confirmBooked);if(!r.ok)throw Error(r.error);setReview(null);setPaste(false);await saved();if(r.data.alreadySaved)setStatus("This batch was already saved. No duplicate import was created.");})}>Save ideas to Not scheduled</button></>:null}</section>:null}
    {proposal?<section className="card stack" aria-label="Arrangement preview"><h3>Review arrangement · not saved</h3>{proposal.warnings.map(s=><p className="issue warning" key={s}>{s}</p>)}<ul>{proposal.placements.map(p=><li key={p.id}><strong>{w.items.find(i=>i.id===p.id)?.title}</strong> → {p.dayId?`${w.days.find(d=>d.id===p.dayId)?.date} · ${p.period}`:"Not scheduled"}<p>{p.reason}</p></li>)}</ul><p>Existing bookings remain unchanged. Previewing does not lock or save the itinerary.</p><div className="row"><button disabled={pending||w.locked} onClick={()=>act(()=>apply(proposal))}>Confirm and save arrangement</button><button disabled={pending||w.locked} onClick={()=>act(()=>apply(proposal,true))}>Apply &amp; lock</button><button className="secondary" onClick={()=>{setProposal(null);setStatus("Preview cancelled. Saved itinerary and ideas are unchanged.");}}>Cancel preview</button></div>{w.locked?<p>Unlock, then preview again against the unlocked plan before applying.</p>:null}</section>:null}
    <div className="organizer-days">{w.days.map(d=><section key={d.id} className="card stack" aria-label={`Plan ${d.date}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData("text/plain");if(w.items.some(i=>i.id===id)&&!w.locked)act(()=>move(id,d.id,w.items.find(i=>i.id===id)!.period));}}><h3>{d.date} · {d.city||"Unassigned"}</h3>{d.transfer?<p className="muted">Arrival, departure or transfer boundary: retain space for travel.</p>:null}{w.items.filter(i=>i.dayId===d.id).sort((a,b)=>a.position-b.position).map((i,index)=><article key={i.id} className="organizer-item" draggable={!w.locked} onDragStart={e=>e.dataTransfer.setData("text/plain",i.id)}><h4>{i.title}</h4><p>{i.period||"Period unspecified"}{i.time?` · ${i.time}`:""}{i.fixed?" · Fixed":""}</p><p>{i.notes}</p>{i.reason?<p className="muted">{i.reason}</p>:null}{i.booking?<p>Booking: {i.booking.state} · {i.booking.date??"date unknown"}{i.booking.date&&i.booking.date!==d.date?" — conflicts with planned Day":""}</p>:null}<div className="row"><button className="secondary" disabled={w.locked||pending} onClick={()=>{setMoveId(i.id);setTarget(i.dayId??"");setPeriod(i.period);}}>Move to</button><button className="text-button" disabled={w.locked||pending||index===0} onClick={()=>act(()=>move(i.id,d.id,i.period,index-1))}>Earlier</button><Link href={`?planDay=${d.id}#item-${i.id}`}>Details / booking</Link></div></article>)}{!w.items.some(i=>i.dayId===d.id)?<p>Open space. No activity added automatically.</p>:null}<Link href={`/trips/${tripId}/discover?gap=${d.id}`}>Find something for this gap</Link></section>)}</div>
    <section className="card stack" aria-label="Not scheduled"><h3>Not scheduled · {w.items.filter(i=>!i.dayId).length}</h3>{w.items.filter(i=>!i.dayId).map(i=><article key={i.id} className="organizer-item"><div className="row">{i.pending?<label><input type="checkbox" checked={selected.includes(i.id)} onChange={e=>setSelected(e.target.checked?[...selected,i.id]:selected.filter(id=>id!==i.id))}/>Include in resync</label>:null}<strong>{i.title}</strong></div><p>{i.city||"City unknown"} · {i.date||"Date undecided"} · {i.period||"Duration unknown"} · {i.alternative?"Optional alternative":i.excluded?"Explicitly excluded":i.pending?"Awaiting resync":"Retained idea / duplicate review"}</p><p>{i.notes}</p>{i.reason?<p className="muted">{i.reason}</p>:null}{i.booking?<p>Booking: {i.booking.state} · {i.booking.date??"date unknown"} · not scheduled</p>:null}<div className="row"><button disabled={w.locked||pending} className="secondary" onClick={()=>{setMoveId(i.id);setTarget("");setPeriod(i.period);}}>Move to</button>{i.imported&&!i.pending?(i.alternative&&/\sor\s/i.test(i.title)?i.title.split(/\s+or\s+/i):[""]).map(choice=><button key={choice} className="secondary" onClick={()=>act(async()=>{const r=await chooseIdea(tripId,i.id,w.token,"INCLUDED",choice||undefined);if(!r.ok)throw Error(r.error);await saved();})}>{choice?"Choose "+choice:"Choose for resync"}</button>):null}<button className="secondary" onClick={()=>act(async()=>{const r=await ideaBookings(tripId);if(!r.ok)throw Error(r.error.message);setBookingContext(r.data.find(x=>x.itemId===i.id)??null);setStatus("Booking information loaded. Schedule unchanged.");})}>Booking information</button><button className="secondary" onClick={()=>{setNoteItem(i.id);setNoteText(i.notes);}}>Edit notes</button></div><details><summary>Source fragment</summary><p>{i.fragment||"Saved in this trip"}</p></details></article>)}</section>
    {noteItem?<section className="card stack"><label>Activity notes<textarea value={noteText} onChange={e=>setNoteText(e.target.value)}/></label><button disabled={pending} onClick={()=>act(async()=>{const i=w.items.find(i=>i.id===noteItem)!;const r=await updateIdeaNotes(tripId,i.id,i.revision,noteText);if(!r.ok)throw Error(r.error);setNoteItem("");await saved();})}>Save notes</button></section>:null}
    {bookingContext?<section className="card stack"><h3>Booking information</h3><ActivityReservation tripId={tripId} context={bookingContext} date={w.items.find(i=>i.id===bookingContext.itemId)?.date??""} startMinute={null}/><button className="secondary" onClick={()=>{setBookingContext(null);act(saved);}}>Close booking</button></section>:null}
    {moveId?<section className="card stack" aria-label="Move activity"><h3>Move {w.items.find(i=>i.id===moveId)?.title}</h3><label>Move to<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Not scheduled</option>{w.days.map(d=><option key={d.id} value={d.id}>{d.date} · {d.city}</option>)}</select></label><label>Period<select value={period} onChange={e=>setPeriod(e.target.value)}>{PERIODS.map(p=><option key={p} value={p}>{p||"Unspecified"}</option>)}</select></label><button disabled={w.locked||pending} onClick={()=>act(()=>move(moveId,target||null,period))}>Move activity</button><button className="secondary" onClick={()=>setMoveId("")}>Cancel move</button></section>:null}
  </section>;
}
