"use client";
import Link from "next/link";
import { useEffect, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { PERIODS, type InputItem, type Placement } from "@/src/modules/organizer/domain";
import type { OrganizerWorkspace } from "@/src/modules/organizer/service";
import { applyOrganization, chooseIdea, importActivities, loadOrganizer, lockItinerary, moveActivity, organizeActivities, undoOrganization, updateIdeaNotes, ideaBookings } from "@/src/modules/organizer/actions";

import { SourceImportReview } from "./source-import-review";
import { parseDocument, type ImportDocument } from "@/src/modules/organizer/import-document";
import { IMPORT_LIMITS } from "@/src/modules/organizer/import-types";
import { OrganizerDay } from "./organizer-day";
import { ActivityReservation } from "./activity-reservation";
import type { ActivityReservationContext } from "@/src/modules/reservations/types";
type Proposal={placements:Placement[];token:string;warnings:string[]};
export function TripOrganizer({tripId,revision}:{tripId:string;revision:string}) {
  const [document,setDocument]=useState<ImportDocument|null>(null);
  const [bookingContext,setBookingContext]=useState<ActivityReservationContext|null>(null); const [noteItem,setNoteItem]=useState<string>(""),[noteText,setNoteText]=useState("");
  const router=useRouter();const [w,setW]=useState<OrganizerWorkspace|null>(null),[text,setText]=useState(""),[review,setReview]=useState<InputItem[]|null>(null),[paste,setPaste]=useState(false),[selected,setSelected]=useState<string[]>([]),[proposal,setProposal]=useState<Proposal|null>(null),[undo,setUndo]=useState(""),[status,setStatus]=useState("Loading organizer…"),[pending,start]=useTransition(),[confirmBooked,setConfirmBooked]=useState(false),[repeat,setRepeat]=useState(false),[moveId,setMoveId]=useState(""),[target,setTarget]=useState(""),[period,setPeriod]=useState("");
  async function refresh(){const r=await loadOrganizer(tripId);if(r.ok){setW(r.data);setSelected(r.data.items.filter(i=>i.pending&&!i.dayId).map(i=>i.id));}else setStatus(r.error);}
  useEffect(()=>{let active=true;loadOrganizer(tripId).then(r=>{if(!active)return;if(r.ok){setW(r.data);setSelected(r.data.items.filter(i=>i.pending&&!i.dayId).map(i=>i.id));setStatus("Saved");}else setStatus(r.error);});return()=>{active=false;};},[tripId,revision]);
  const act=(fn:()=>Promise<void>)=>start(async()=>{setStatus("Saving…");try{await fn();}catch(e){setStatus("Failed: "+(e instanceof Error?e.message:"Please retry. Previous positions were retained."));}});
  const saved=async()=>{await refresh();router.refresh();setStatus("Saved");};
  async function apply(p:Proposal,relock=false){const r=await applyOrganization(tripId,p,relock);if(!r.ok)throw Error(r.error);setUndo(r.data.undo);setProposal(null);setMoveId("");await saved();}
  async function move(id:string,dayId:string|null,chosenPeriod:string,index?:number){const r=await moveActivity(tripId,id,dayId,chosenPeriod,index);if(!r.ok)throw Error(r.error);if(r.data.warnings.length){setProposal(r.data);setStatus("Review the scheduling consequence before applying.");}else await apply(r.data);}
  if(!w)return <section className="card"><p role="status">{status}</p></section>;
  const waiting=w.items.filter(i=>i.pending&&!i.dayId).length;
  return <section className="organizer stack" aria-label="Paste-first trip organizer">
    <header className="row row-between"><div><span className="eyebrow">Your choices, your itinerary</span><h2>Organize my list</h2></div><button aria-label={w.locked?"Unlock itinerary":"Lock itinerary"} disabled={pending} onClick={()=>act(async()=>{const r=await lockItinerary(tripId,w.token,!w.locked);if(!r.ok)throw Error(r.error);setProposal(null);await saved();})}>{w.locked?"Locked · Unlock":"Unlocked · Lock"}</button></header>
    <p>{w.locked?"The saved schedule is protected. Keep collecting ideas and tracking bookings.":"Paste your activities, review an arrangement, then save it. Nothing is booked for you."}</p>
    <div className="row"><button onClick={()=>setPaste(!paste)}>Paste activities</button><button className="secondary" disabled={pending||!waiting} onClick={()=>act(async()=>{const r=await organizeActivities(tripId,selected);if(!r.ok)throw Error(r.error);setProposal(r.data);setStatus("Preview only · saved itinerary unchanged");})}>{w.items.some(i=>i.dayId)?"Resync new activities":"Organize my list"} ({waiting} waiting)</button><Link href={`/trips/${tripId}/reservations`}>Trip bookings</Link>{undo&&!w.locked?<button className="secondary" disabled={pending} onClick={()=>act(async()=>{const r=await undoOrganization(tripId,undo);if(!r.ok)throw Error(r.error);setUndo("");await saved();})}>Undo recent change</button>:null}</div>
    <p role="status" aria-live="polite">{pending?"Saving…":status}</p>
    {paste?<section className="card stack"><h3>Paste activities</h3><p>Paste notes, a wishlist or a written itinerary. Review sections, source dates and unresolved decisions before saving. Links are never fetched.</p><label>Original planning text<textarea rows={8} value={text} maxLength={IMPORT_LIMITS.characters} onChange={e=>{setText(e.target.value);setReview(null);setDocument(null);}}/></label><p>{text.length.toLocaleString()} / {IMPORT_LIMITS.characters.toLocaleString()} characters</p><button disabled={!text.trim()} onClick={()=>{try{const doc=parseDocument(text,[...new Set(w.days.map(d=>d.city))],Number(w.days[0]?.date.slice(0,4))||undefined);setDocument(doc);setReview(doc.sections.find(s=>s.id===doc.suggested)?.items??[]);setStatus("Review extracted sections and unresolved questions. Nothing saved.");}catch(e){setStatus(String(e));}}}>Review paste</button>
      {review&&document?<><SourceImportReview document={document} items={review} onChange={setReview}/>      <label><input type="checkbox" checked={confirmBooked} onChange={e=>setConfirmBooked(e.target.checked)}/>I confirm any explicit “booked” statements as my own reported bookings. This does not contact a supplier.</label><label><input type="checkbox" checked={repeat} onChange={e=>setRepeat(e.target.checked)}/>This is an intentional repeat visit/import.</label><button disabled={pending} onClick={()=>act(async()=>{const r=await importActivities(tripId,text,review,repeat?crypto.randomUUID():"",confirmBooked);if(!r.ok)throw Error(r.error);setReview(null);setPaste(false);await saved();if(r.data.alreadySaved)setStatus("This batch was already saved. No duplicate import was created.");})}>Save ideas to Not scheduled</button></>:null}</section>:null}
    {proposal?<section className="card stack" aria-label="Arrangement preview"><h3>Review arrangement · not saved</h3>{proposal.warnings.map(s=><p className="issue warning" key={s}>{s}</p>)}<ul>{proposal.placements.map(p=><li key={p.id}><strong>{w.items.find(i=>i.id===p.id)?.title}</strong> → {p.dayId?`${w.days.find(d=>d.id===p.dayId)?.date} · ${p.period}`:"Not scheduled"}<p>{p.reason}</p></li>)}</ul><p>Existing bookings remain unchanged. Previewing does not lock or save the itinerary.</p><div className="row"><button disabled={pending||w.locked} onClick={()=>act(()=>apply(proposal))}>Confirm and save arrangement</button><button disabled={pending||w.locked} onClick={()=>act(()=>apply(proposal,true))}>Apply &amp; lock</button><button className="secondary" onClick={()=>{setProposal(null);setStatus("Preview cancelled. Saved itinerary and ideas are unchanged.");}}>Cancel preview</button></div>{w.locked?<p>Unlock, then preview again against the unlocked plan before applying.</p>:null}</section>:null}
    <p className="muted">Availability, hours and transport have not been verified for this trip. Suggested periods are planning choices, not confirmed times. Source notes and booking records remain separate.</p>
    <div className="organizer-days readable-itinerary">{w.days.map(d=><OrganizerDay key={d.id} day={d} items={w.items.filter(i=>i.dayId===d.id)} tripId={tripId} locked={w.locked} pending={pending} onMove={i=>{setMoveId(i.id);setTarget(i.dayId??"");setPeriod(i.period);}} onEarlier={(i,index)=>act(()=>move(i.id,d.id,i.period,index-1))} onDrop={id=>{const i=w.items.find(i=>i.id===id);if(i)act(()=>move(id,d.id,i.period));}}/>)}</div>
    <section className="card stack" aria-label="Not scheduled"><h3>Not scheduled · {w.items.filter(i=>!i.dayId).length}</h3>{w.items.filter(i=>!i.dayId).map(i=><article key={i.id} className="organizer-item"><div className="row">{i.pending?<label><input type="checkbox" checked={selected.includes(i.id)} onChange={e=>setSelected(e.target.checked?[...selected,i.id]:selected.filter(id=>id!==i.id))}/>Include in resync</label>:null}<strong>{i.title}</strong></div><p>{i.city||"City unknown"} · {i.date||"Date undecided"} · {i.period||"Duration unknown"} · {i.alternative?"Optional alternative":i.excluded?"Explicitly excluded":i.pending?"Awaiting resync":"Retained idea / duplicate review"}</p><p>{i.description||i.notes}</p>{i.decision?<p><strong>Next decision:</strong> {i.decision}</p>:null}{i.reason?<p className="muted">{i.reason.startsWith("No supported space")?"The earlier arrangement left this idea out. Preview a resync to see current placement constraints.":i.reason}</p>:null}{i.booking?<p>Booking: {i.booking.state} · {i.booking.date??"date unknown"} · not scheduled</p>:null}<div className="row"><button disabled={w.locked||pending} className="secondary" onClick={()=>{setMoveId(i.id);setTarget("");setPeriod(i.period);}}>Move to</button>{i.imported&&!i.pending?(i.alternative&&/\sor\s/i.test(i.title)?i.title.split(/\s+or\s+/i):[""]).map(choice=><button key={choice} className="secondary" onClick={()=>act(async()=>{const r=await chooseIdea(tripId,i.id,w.token,"INCLUDED",choice||undefined);if(!r.ok)throw Error(r.error);await saved();})}>{choice?"Choose "+choice:"Choose for resync"}</button>):null}<button className="secondary" onClick={()=>act(async()=>{const r=await ideaBookings(tripId);if(!r.ok)throw Error(r.error.message);setBookingContext(r.data.find(x=>x.itemId===i.id)??null);setStatus("Booking information loaded. Schedule unchanged.");})}>Booking information</button><button className="secondary" onClick={()=>{setNoteItem(i.id);setNoteText(i.notes);}}>Edit notes</button></div><details><summary>Source fragment</summary><p>{i.fragment||"Saved in this trip"}</p></details></article>)}</section>
    {noteItem?<section className="card stack"><label>Activity notes<textarea value={noteText} onChange={e=>setNoteText(e.target.value)}/></label><button disabled={pending} onClick={()=>act(async()=>{const i=w.items.find(i=>i.id===noteItem)!;const r=await updateIdeaNotes(tripId,i.id,i.revision,noteText);if(!r.ok)throw Error(r.error);setNoteItem("");await saved();})}>Save notes</button></section>:null}
    {bookingContext?<section className="card stack"><h3>Booking information</h3><ActivityReservation tripId={tripId} context={bookingContext} date={w.items.find(i=>i.id===bookingContext.itemId)?.date??""} startMinute={null}/><button className="secondary" onClick={()=>{setBookingContext(null);act(saved);}}>Close booking</button></section>:null}
    {moveId?<section className="card stack" aria-label="Move activity"><h3>Move {w.items.find(i=>i.id===moveId)?.title}</h3><label>Move to<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Not scheduled</option>{w.days.map(d=><option key={d.id} value={d.id}>{d.date} · {d.city}</option>)}</select></label><label>Period<select value={period} onChange={e=>setPeriod(e.target.value)}>{PERIODS.map(p=><option key={p} value={p}>{p||"Unspecified"}</option>)}</select></label><button disabled={w.locked||pending} onClick={()=>act(()=>move(moveId,target||null,period))}>Move activity</button><button className="secondary" onClick={()=>setMoveId("")}>Cancel move</button></section>:null}
  </section>;
}
