"use client";
import Link from "next/link";
import {useEffect,useState,useTransition} from "react";
import {type InputItem} from "@/src/modules/organizer/domain";
import {attachUndated,listUndated,saveUndated} from "@/src/modules/organizer/undated-actions";
import {SourceImportReview} from "./source-import-review";
import {parseDocument,type ImportDocument} from "@/src/modules/organizer/import-document";
import {IMPORT_LIMITS} from "@/src/modules/organizer/import-types";
type Lists=Extract<Awaited<ReturnType<typeof listUndated>>,{ok:true}>;
export function UndatedOrganizer(){const [document,setDocument]=useState<ImportDocument|null>(null);const [data,setData]=useState<Lists|null>(null),[text,setText]=useState(""),[items,setItems]=useState<InputItem[]|null>(null),[current,setCurrent]=useState(""),[token,setToken]=useState(""),[trip,setTrip]=useState(""),[status,setStatus]=useState(""),[pending,run]=useTransition();
 const reload=async()=>{const r=await listUndated();if(r.ok)setData(r);else setStatus(r.error);};useEffect(()=>{void listUndated().then(r=>{if(r.ok)setData(r);else setStatus(r.error);});},[]);
 return <main className="travel-dusk stack organizer"><h1>Your list, before the dates</h1><p>Keep ideas by city or area. No calendar dates, bookings or precise fit are invented.</p><label>Planning text<textarea maxLength={IMPORT_LIMITS.characters} rows={10} value={text} onChange={e=>{setText(e.target.value);setItems(null);}} placeholder={"City:\n- Activity\n- A or B — optional"}/></label><button onClick={()=>{try{const doc=parseDocument(text);setDocument(doc);setItems(doc.sections.find(s=>s.id===doc.suggested)?.items??[]);setStatus("Confirm section destinations and source roles. Dates without a year remain unresolved.");}catch(e){setStatus(String(e));}}}>Organize by city</button>{items?<><p>{items.length} retained items · all Not scheduled</p>{document?<SourceImportReview document={document} items={items} onChange={setItems}/>:<p>Saved extraction retained. Review the source again only if you want to reinterpret it.</p>}<button disabled={pending} onClick={()=>run(async()=>{const r=await saveUndated(text,items,current||undefined,token||undefined);if(r.ok){setCurrent(r.id);setStatus("List saved without dates.");await reload();const lists=await listUndated();if(lists.ok)setToken(lists.lists.find(l=>l.id===r.id)?.token??"");}else setStatus(r.error);})}>Save list without dates</button></>:null}<p role="status">{pending?"Saving…":status}</p><h2>Saved lists</h2>{data?.lists.map(l=><button className="secondary" key={l.id} onClick={()=>{setCurrent(l.id);setToken(l.token);setText(l.text);setItems(l.items);setDocument(null);}}>{l.items[0]?.city||"Unassigned"} · {l.items.length} items</button>)}{current?<><label>Use in an existing dated trip<select value={trip} onChange={e=>setTrip(e.target.value)}><option value="">Choose trip</option>{data?.trips.map(t=><option value={t.id} key={t.id}>{t.name||t.destinationLabel}</option>)}</select></label><button disabled={!trip||pending} onClick={()=>run(async()=>{const r=await attachUndated(current,trip,token);setStatus(r.ok?"Ideas saved to that trip’s Not scheduled list. Booked statements still require confirmation.":r.error);})}>Save ideas to chosen trip</button>{trip?<Link href={`/trips/${trip}/itinerary`}>Open chosen itinerary</Link>:null}</>:null}<Link href="/">Trips / add dates</Link></main>;
}
