import { afterAll, beforeEach, describe, expect, it } from "vitest";
import { getPrismaClient } from "@/src/lib/prisma";
import { createTrip, removeSegment, updateTrip } from "@/src/modules/trips/service";
import { createManualActivity, editItineraryItem, confirmItineraryEdit, manualActivityToken, type EditRequest } from "@/src/modules/itinerary/details-service";
import { getItineraryBuilder, removeItineraryItem, scheduleAcceptedRecommendation } from "@/src/modules/itinerary/service";
import { createPlanningBlock, previewMoveItineraryItem, confirmMoveItineraryItem, reorderItineraryItem } from "@/src/modules/itinerary/builder-service";
import { getTravelPlanning, saveTravelPlan, reconfirmTravelPlan } from "@/src/modules/itinerary/travel/service";
import { getTodayView } from "@/src/modules/today/service";
import { markItineraryItemCompleted, previewSkipItineraryItem, skipItineraryItem } from "@/src/modules/itinerary/progress-service";
import { createActivityReservation, markReservationBooked, getItineraryReservationContext, linkReservationEvidence } from "@/src/modules/reservations/service";
import { previewReservationCancellation, recordReservationCancellation, updateReservationNotes } from "@/src/modules/reservations/followup-service";
import { decideRecommendation } from "@/src/modules/discover/service";
import { seedDemoTrip, DEMO_TRIP_ID } from "../prisma/seed-data";
import { seedDiscoverFixtures } from "../prisma/discover-seed";
const enabled=Boolean(process.env.DATABASE_URL),integration=enabled?describe:describe.skip,db=enabled?getPrismaClient():null;
let tripId:string,dayId:string,nextDay:string;
function ok<T>(r:{ok:true;data:T}|{ok:false;error:unknown}):T{if(!r.ok)throw Error(JSON.stringify(r.error));return r.data;}
async function fresh(){const r=await createTrip({destinationLabel:"Synthetic Bay",destinationScope:"CITY_BASE",startDate:"2030-04-01",endDate:"2030-04-02",travelerCount:2});expect(r.ok).toBe(true);return r.data!.trip.id;}
async function days(){const d=await db!.day.findMany({where:{tripId},orderBy:{position:"asc"}});dayId=d[0].id;nextDay=d[1].id;}
async function create(details:Record<string,unknown>={},token=manualActivityToken(tripId),targetDay=dayId){return createManualActivity({tripId,dayId:targetDay,token,details:{title:"Synthetic walk",...details}});}
async function request(id:string,details:Record<string,unknown>={}):Promise<EditRequest>{const b=ok(await getItineraryBuilder(tripId));const i=b.days.flatMap(d=>d.items).find(i=>i.id===id)!;return {tripId,itemId:id,token:i.editToken,details};}
async function edit(id:string,details:Record<string,unknown>){return editItineraryItem(await request(id,details));}
async function apply(id:string,details:Record<string,unknown>){const q=await request(id,details),r=ok(await editItineraryItem(q));if(r.preview)ok(await confirmItineraryEdit({...q,token:r.preview.token}));}
async function travel(id:string){return ok(await getTravelPlanning(tripId)).find(i=>i.itemId===id)!;}
async function plan(id:string,extra={}){ok(await saveTravelPlan({tripId,itemId:id,token:(await travel(id)).token,originKind:"ENTERED",originLabel:"Demo meeting point",travelMinutes:25,bufferMinutes:10,basis:"PLANNED",clockContext:"SAME_LOCAL_CLOCK",...extra}));}
async function booking(id:string,booked=true){const r=ok(await createActivityReservation({tripId,itineraryItemId:id,state:"CHECK_BACK",desiredDate:"2030-04-01",desiredStartMinute:600}));if(booked)ok(await markReservationBooked({tripId,reservationId:r.id,confirmedDate:"2030-04-01",confirmedStartMinute:600,confirmationReference:"SYNTHETIC-BUILDER"}));return r.id;}
async function progress(id:string){const v=ok(await getTodayView(tripId,dayId));return [v.plan.next,...v.plan.remaining,...v.plan.processed].find(i=>i?.id===id)!;}
async function snapshot(){return {items:await db!.itineraryItem.findMany({orderBy:{id:"asc"}}),receipts:await db!.manualActivitySubmission.findMany({orderBy:{id:"asc"}}),plans:await db!.itineraryTravelPlan.findMany({orderBy:{itemId:"asc"}}),bookings:await db!.reservation.findMany({orderBy:{id:"asc"}}),decisions:await db!.recommendationDecision.findMany({orderBy:{id:"asc"}}),places:await db!.place.findMany({orderBy:{id:"asc"}}),evidence:await db!.evidenceRecord.findMany({orderBy:{id:"asc"}}),days:await db!.day.findMany({orderBy:{id:"asc"}})};}
integration("Itinerary manual creation and in-place editing",()=>{
 beforeEach(async()=>{await db!.trip.deleteMany();await db!.prototypeUser.deleteMany();await db!.evidenceRecord.deleteMany();await db!.place.deleteMany();await db!.source.deleteMany();tripId=await fresh();await days();});afterAll(async()=>{await db?.$disconnect();});
 it("creates a fresh-trip manual Activity with honest unknowns and no catalog/decision/booking dependency",async()=>{expect((await removeSegment(tripId,(await db!.day.findUniqueOrThrow({where:{id:dayId}})).primarySegmentId!)).ok).toBe(true);const id=ok(await create()).id;expect(await db!.itineraryItem.findUniqueOrThrow({where:{id}})).toMatchObject({type:"ACTIVITY",enteredManually:true,title:"Synthetic walk",sourceRecommendationId:null,startMinute:null,durationMinutes:null,locationLabel:null,referenceUrl:null,flexibility:"FLEXIBLE",position:0,progress:"PENDING"});for(const n of [await db!.recommendation.count(),await db!.place.count(),await db!.recommendationDecision.count(),await db!.reservation.count()])expect(n).toBe(0);expect(ok(await getItineraryBuilder(tripId)).days[0].base).toBeNull();});
 it("permits deliberately repeated titles with different submissions",async()=>{const a=ok(await create()).id,b=ok(await create()).id;expect(a).not.toBe(b);expect(await db!.itineraryItem.count()).toBe(2);});
 it("serializes identical create retries and never recreates a subsequently removed item",async()=>{const token=manualActivityToken(tripId),results=await Promise.all([create({},token),create({},token)]);expect(results.every(r=>r.ok)).toBe(true);const id=ok(results[0]).id;expect(ok(results[1]).id).toBe(id);const before=await snapshot();ok(await create({},token));expect(await snapshot()).toEqual(before);await apply(id,{title:"Edited after creation"});expect(ok(await create({},token)).id).toBe(id);expect((await db!.itineraryItem.findUniqueOrThrow({where:{id}})).title).toBe("Edited after creation");ok(await removeItineraryItem(tripId,id));expect(await create({},token)).toMatchObject({ok:false,error:{code:"ITEM_REMOVED"}});expect(await db!.itineraryItem.count()).toBe(0);expect((await db!.manualActivitySubmission.findFirstOrThrow()).itemId).toBeNull();});
 it("rejects conflicting payloads reusing a creation receipt",async()=>{const token=manualActivityToken(tripId);const r=await Promise.all([create({title:"One"},token),create({title:"Two"},token)]);expect(r.filter(x=>x.ok)).toHaveLength(1);expect(await db!.manualActivitySubmission.count()).toBe(1);});
 it("appends concurrently and normalizes a noncontiguous Day atomically",async()=>{const ids=await Promise.all(Array.from({length:4},()=>create()));expect(ids.every(r=>r.ok)).toBe(true);const first=ok(ids[0]).id;await db!.itineraryItem.update({where:{id:first},data:{position:10}});ok(await create());expect((await db!.itineraryItem.findMany({orderBy:{position:"asc"}})).map(i=>i.position)).toEqual([0,1,2,3,4]);});
 it("rejects wrong Day/Trip, tampering, expiry and foreign ownership without writes",async()=>{const other=await fresh(),foreign=await db!.day.findFirstOrThrow({where:{tripId:other}}),token=manualActivityToken(tripId);expect((await create({},token,foreign.id)).ok).toBe(false);expect((await create({},token+"x")).ok).toBe(false);expect((await create({},manualActivityToken(other))).ok).toBe(false);expect((await createManualActivity({tripId,dayId,token,details:{title:"Expired"}},new Date(Date.now()+31*60000))).ok).toBe(false);const id=ok(await create()).id,q=await request(id,{title:"No"}),owner=await db!.prototypeUser.create({data:{displayName:"Other"}});await db!.trip.update({where:{id:tripId},data:{ownerId:owner.id}});expect((await create()).ok).toBe(false);expect((await editItineraryItem(q)).ok).toBe(false);expect((await getItineraryBuilder(tripId)).ok).toBe(false);expect(await db!.itineraryItem.count()).toBe(1);});
 it("rejects invalid creation fields without leaving a receipt",async()=>{for(const details of [{title:" "},{durationMinutes:0},{startMinute:1440},{referenceUrl:"javascript:alert(1)"},{type:"FREE_TIME"},{locationLabel:"x".repeat(301)}])expect((await create(details)).ok).toBe(false);expect(await db!.manualActivitySubmission.count()).toBe(0);expect(await db!.itineraryItem.count()).toBe(0);});
 it("edits the same ID, retains omitted values and explicitly clears optional fields",async()=>{const id=ok(await create({startMinute:600,durationMinutes:45,locationLabel:"North gate",referenceUrl:"https://example.com/",notes:"Original"})).id;ok(await edit(id,{title:"New name"}));expect(await db!.itineraryItem.findUniqueOrThrow({where:{id}})).toMatchObject({title:"New name",notes:"Original",locationLabel:"North gate",startMinute:600});ok(await edit(id,{startMinute:null,durationMinutes:null,notes:null,locationLabel:null,referenceUrl:null}));expect(await db!.itineraryItem.findUniqueOrThrow({where:{id}})).toMatchObject({startMinute:null,durationMinutes:null,locationLabel:null,referenceUrl:null,notes:null});expect(await db!.itineraryItem.count()).toBe(1);});
 it("keeps type/Day/progress immutable and enforces Free Time duration on edit",async()=>{const id=ok(await createPlanningBlock({tripId,dayId,type:"FREE_TIME",durationMinutes:30})).id;for(const details of [{type:"ACTIVITY"},{dayId:nextDay},{progress:"COMPLETED"},{durationMinutes:null},{durationMinutes:0},{locationLabel:"Not allowed"}])expect((await edit(id,details)).ok).toBe(false);ok(await edit(id,{title:"Quiet time",durationMinutes:60}));expect(await db!.itineraryItem.findUniqueOrThrow({where:{id}})).toMatchObject({id,type:"FREE_TIME",dayId,durationMinutes:60});});
 it.each([{startMinute:630},{durationMinutes:75},{locationLabel:"South gate"},{flexibility:"FLEXIBLE"}])("previews Fixed material change %s without writing and confirms explicitly",async details=>{const id=ok(await create({startMinute:600,durationMinutes:45,flexibility:"FIXED"})).id,q=await request(id,details),before=await snapshot(),r=ok(await editItineraryItem(q));expect(r.preview).not.toBeNull();expect(await snapshot()).toEqual(before);expect(r.preview!.before.startMinute).toBe(600);ok(await confirmItineraryEdit({...q,token:r.preview!.token}));expect(await db!.itineraryItem.findUniqueOrThrow({where:{id}})).toMatchObject({...details,id});});
 it("previews Booked material edits even when Flexible and preserves all booking details",async()=>{const id=ok(await create({startMinute:600})).id;await booking(id);const before=await snapshot(),q=await request(id,{startMinute:660}),r=ok(await editItineraryItem(q));expect(r.preview).toMatchObject({booked:true,fixed:false});expect(await snapshot()).toEqual(before);ok(await confirmItineraryEdit({...q,token:r.preview!.token}));expect((await snapshot()).bookings).toEqual(before.bookings);});
 it("allows ordinary Fixed title/note/reference corrections without a material preview",async()=>{const id=ok(await create({flexibility:"FIXED"})).id;await booking(id);expect(ok(await edit(id,{title:"Corrected title",notes:"Corrected note",referenceUrl:"https://example.com/new"})).preview).toBeNull();});
 it("binds confirmation to exact changes and invalidates it after booking changes",async()=>{const id=ok(await create({startMinute:600,flexibility:"FIXED"})).id,rid=await booking(id),q=await request(id,{startMinute:660}),r=ok(await editItineraryItem(q)),before=await snapshot();expect((await confirmItineraryEdit({...q,token:r.preview!.token,details:{startMinute:700}})).ok).toBe(false);expect(await snapshot()).toEqual(before);ok(await updateReservationNotes({tripId,reservationId:rid,notes:"Other session"}));expect((await confirmItineraryEdit({...q,token:r.preview!.token})).ok).toBe(false);expect((await db!.itineraryItem.findUniqueOrThrow({where:{id}})).startMinute).toBe(600);});
 it("serializes conflicting tabs and makes exact edit/confirm retries metadata-stable",async()=>{const id=ok(await create({startMinute:600})).id,q=await request(id,{notes:"First"});const results=await Promise.all([editItineraryItem(q),editItineraryItem({...q,details:{notes:"Other"}})]);expect(results.filter(r=>r.ok)).toHaveLength(1);const won=results[0].ok?q:{...q,details:{notes:"Other"}},before=await snapshot();ok(await editItineraryItem(won));expect(await snapshot()).toEqual(before);await apply(id,{flexibility:"FIXED"});const next=await request(id,{startMinute:660}),p=ok(await editItineraryItem(next));const confirmed={...next,token:p.preview!.token};ok(await confirmItineraryEdit(confirmed));const saved=await snapshot();ok(await confirmItineraryEdit(confirmed));expect(await snapshot()).toEqual(saved);expect((await editItineraryItem(q)).ok).toBe(false);});
 it("rejects old edit forms after movement, reorder and progress actions",async()=>{const id=ok(await create()).id;ok(await create());const q=await request(id,{notes:"Old"});ok(await reorderItineraryItem({tripId,itemId:id,direction:"LATER"}));expect((await editItineraryItem(q)).ok).toBe(false);const moved=await request(id,{notes:"Old move"}),p=ok(await previewMoveItineraryItem({tripId,itemId:id,targetDayId:nextDay}));ok(await confirmMoveItineraryItem(tripId,p.token));expect((await editItineraryItem(moved)).ok).toBe(false);});
 it.each(["COMPLETED","SKIPPED"])("preserves %s progress and occupied-Day protection after edits",async state=>{const id=ok(await create()).id,p=await progress(id);if(state==="COMPLETED")ok(await markItineraryItemCompleted({tripId,itemId:id,token:p.token}));else{const s=ok(await previewSkipItineraryItem({tripId,itemId:id,token:p.token}));ok(await skipItineraryItem({tripId,itemId:id,token:s.token}));}const before=await db!.itineraryItem.findUniqueOrThrow({where:{id}});ok(await edit(id,{title:"Revised while processed",startMinute:600}));expect(await db!.itineraryItem.findUniqueOrThrow({where:{id}})).toMatchObject({progress:state,progressChangedAt:before.progressChangedAt,progressActionKey:before.progressActionKey});expect((await updateTrip({tripId,startDate:"2030-04-02",endDate:"2030-04-02",travelerCount:2})).ok).toBe(false);});
 it("preserves recommendation, Place, Decision, evidence, reservation and scheduling constraint",async()=>{await seedDemoTrip(db!);await seedDiscoverFixtures(db!);tripId=DEMO_TRIP_ID;await days();const rec=await db!.recommendation.findFirstOrThrow({where:{tripId},orderBy:{displayRank:"asc"}});ok(await decideRecommendation({tripId,tripSegmentId:rec.tripSegmentId,recommendationId:rec.id,outcome:"ACCEPTED"}));const id=ok(await scheduleAcceptedRecommendation({tripId,recommendationId:rec.id,dayId,startMinute:600,flexibility:"FIXED"})).id;await booking(id);await plan(id);const before=await snapshot();await apply(id,{title:"My planned visit",startMinute:630,durationMinutes:75,locationLabel:"Entered meeting gate",notes:"My plan"});const after=await snapshot();for(const key of ["bookings","decisions","places","evidence","plans","days"] as const)expect(after[key]).toEqual(before[key]);expect((await db!.itineraryItem.findUniqueOrThrow({where:{id}}))).toMatchObject({sourceRecommendationId:rec.id,progress:"PENDING",enteredManually:false});expect((await scheduleAcceptedRecommendation({tripId,recommendationId:rec.id,dayId})).ok).toBe(false);const wrong=await db!.day.findFirstOrThrow({where:{tripId,primarySegmentId:{not:rec.tripSegmentId}}});expect((await previewMoveItineraryItem({tripId,itemId:id,targetDayId:wrong.id})).ok).toBe(false);expect((await travel(id)).status).toBe("NEEDS_REVIEW");expect(ok(await getItineraryReservationContext(tripId)).find(i=>i.itemId===id)!.reservation!.attention.join(" ")).toContain("Confirmed time differs");});
 it.each([{locationLabel:"Changed starting point"},{startMinute:570},{durationMinutes:50}])("invalidates referenced source context after %s without changing travel inputs",async fields=>{const source=ok(await create({startMinute:540,durationMinutes:20})).id,id=ok(await create({startMinute:600})).id;await plan(id,{originKind:"EARLIER_ITEM",sourceItemId:source});const before=await db!.itineraryTravelPlan.findUniqueOrThrow({where:{itemId:id}});ok(await edit(source,fields));expect(await db!.itineraryTravelPlan.findUniqueOrThrow({where:{itemId:id}})).toEqual(before);expect(await travel(id)).toMatchObject({status:"NEEDS_REVIEW",departure:null});ok(await reconfirmTravelPlan({tripId,itemId:id,token:(await travel(id)).token}));expect((await travel(id)).status).toBe("READY");});
 it("invalidates target location while notes/reference corrections keep reviewed travel ready",async()=>{const source=ok(await create({startMinute:500,durationMinutes:20})).id,id=ok(await create({startMinute:600})).id;await plan(id,{originKind:"EARLIER_ITEM",sourceItemId:source});for(const itemId of [source,id])ok(await edit(itemId,{notes:"Unrelated note",referenceUrl:"https://example.com/corrected"}));expect((await travel(id)).status).toBe("READY");ok(await edit(id,{locationLabel:"New destination entrance"}));expect(await travel(id)).toMatchObject({status:"NEEDS_REVIEW",departure:null});});
 it("source removal retains target/history; target removal preserves booking and creation receipts",async()=>{const source=ok(await create({startMinute:500})).id,id=ok(await create({startMinute:600})).id;await booking(id);await plan(id,{originKind:"EARLIER_ITEM",sourceItemId:source});ok(await removeItineraryItem(tripId,source));expect(await travel(id)).toMatchObject({status:"NEEDS_REVIEW",inputs:{sourceItemId:null,originKind:"EARLIER_ITEM"}});ok(await removeItineraryItem(tripId,id));expect(await db!.itineraryTravelPlan.count()).toBe(0);expect((await db!.reservation.findFirstOrThrow()).itineraryItemId).toBeNull();expect(await db!.manualActivitySubmission.count()).toBe(2);await db!.trip.delete({where:{id:tripId}});expect(await db!.manualActivitySubmission.count()).toBe(0);});
 it("manual Activities support reservation tracking while source-specific evidence stays unavailable",async()=>{const id=ok(await create()).id,rid=await booking(id);const context=ok(await getItineraryReservationContext(tripId)).find(i=>i.itemId===id)!;expect(context.reservation?.state).toBe("BOOKED");expect(context.reservation?.sourceAvailable).toBe(false);expect(context.availableEvidence).toEqual([]);expect((await linkReservationEvidence({tripId,reservationId:rid,evidenceRecordId:"missing"})).ok).toBe(false);});
 it("intervening edits invalidate progress, movement and reservation cancellation previews",async()=>{const id=ok(await create({startMinute:600})).id,rid=await booking(id),p=await progress(id),move=ok(await previewMoveItineraryItem({tripId,itemId:id,targetDayId:nextDay})),cancel=ok(await previewReservationCancellation({tripId,reservationId:rid}));ok(await edit(id,{notes:"Revised plan"}));expect((await markItineraryItemCompleted({tripId,itemId:id,token:p.token})).ok).toBe(false);expect((await confirmMoveItineraryItem(tripId,move.token)).ok).toBe(false);expect((await recordReservationCancellation({tripId,reservationId:rid,token:cancel.token,externalCancellationConfirmed:true})).ok).toBe(false);});
 it("repeat seed preserves manual fields, receipts, travel, progress and bookings exactly",async()=>{await seedDemoTrip(db!);await seedDiscoverFixtures(db!);const id=ok(await create({startMinute:600,locationLabel:"User gate",referenceUrl:"https://example.com/",notes:"Private synthetic note"})).id;await booking(id);await plan(id);ok(await markItineraryItemCompleted({tripId,itemId:id,token:(await progress(id)).token}));const before=await snapshot();await seedDemoTrip(db!,{preserveExisting:true});await seedDiscoverFixtures(db!);await seedDemoTrip(db!,{preserveExisting:true});await seedDiscoverFixtures(db!);expect(await snapshot()).toEqual(before);});
});
