import { afterAll,beforeEach,describe,expect,it } from "vitest";
import { getPrismaClient } from "@/src/lib/prisma";
import { createTrip } from "@/src/modules/trips/service";
import { parsePaste } from "@/src/modules/organizer/domain";
import { dayContent } from "@/src/modules/organizer/content";
import { includeIdea } from "@/src/modules/organizer/service";
import { acceptImport,applyProposal,getOrganizer,previewOrganization,setLock,previewPlacement,undoChange,findGapIdeas } from "@/src/modules/organizer/service";
import { createPlanningBlock,reorderItineraryItem } from "@/src/modules/itinerary/builder-service";
import { createManualActivity,manualActivityToken } from "@/src/modules/itinerary/details-service";
import { removeItineraryItem } from "@/src/modules/itinerary/service";
const enabled=Boolean(process.env.DATABASE_URL),suite=enabled?describe:describe.skip,db=enabled?getPrismaClient():null;
let id:string;const fixtureTrips:string[]=[];
async function add(text="Port City:\n- Museum\n- Park",booked=false){return acceptImport(id,text,parsePaste(text,["Port City"],2031),"",booked);}
async function proposal(){const w=await getOrganizer(id);return previewOrganization(id,w.items.filter(i=>i.pending&&!i.dayId).map(i=>i.id));}
suite("durable organizer and lock transactions",()=>{
 beforeEach(async()=>{const r=await createTrip({destinationLabel:"Port City",destinationScope:"CITY_BASE",startDate:"2031-06-01",endDate:"2031-06-05",travelerCount:1});if(!r.ok)throw Error("Fixture creation failed");id=r.data!.trip.id;fixtureTrips.push(id);});
 afterAll(async()=>{if(db){await db.organizerIdea.deleteMany({where:{tripId:{in:fixtureTrips}}});await db.importBatch.deleteMany({where:{tripId:{in:fixtureTrips}}});await db.trip.deleteMany({where:{id:{in:fixtureTrips}}});await db.$disconnect();}});
 it("retains original text, retries imports exactly once and preserves IDs on unscheduling",async()=>{const text="Port City:\n- Museum";await add(text);await add(text);expect(await db!.importBatch.count({where:{tripId:id}})).toBe(1);const w=await getOrganizer(id);expect(w.items).toHaveLength(1);await applyProposal(id,await proposal(),false);const saved=(await getOrganizer(id)).items[0];expect(saved.dayId).not.toBeNull();await applyProposal(id,await previewPlacement(id,saved.id,null,saved.period),false);expect((await getOrganizer(id)).items[0]).toMatchObject({id:saved.id,dayId:null});});
 it("lock survives new imports, permits previews, blocks all legacy scheduling paths",async()=>{await add();const w=await getOrganizer(id);await setLock(id,w.token,true);await add("Port City:\n- New gallery");expect((await getOrganizer(id)).locked).toBe(true);const p=await proposal();await expect(applyProposal(id,p,false)).rejects.toThrow("locked");const dayId=w.days[0].id;expect((await createPlanningBlock({tripId:id,dayId,type:"HOTEL_REST"})).ok).toBe(false);expect((await createManualActivity({tripId:id,dayId,token:manualActivityToken(id),details:{title:"Blocked"}})).ok).toBe(false);expect((await removeItineraryItem(id,w.items[0].id)).ok).toBe(false);expect((await reorderItineraryItem({tripId:id,itemId:w.items[0].id,direction:"EARLIER"})).ok).toBe(false);});
 it("rejects a stale proposal after a lock/unlock transition",async()=>{await add();const p=await proposal();let w=await getOrganizer(id);await setLock(id,w.token,true);w=await getOrganizer(id);await setLock(id,w.token,false);await expect(applyProposal(id,p,false)).rejects.toThrow("changed");expect((await getOrganizer(id)).items.every(i=>!i.dayId)).toBe(true);});
 it("applies atomically, relocks and safely repeats without duplicate placements",async()=>{await add();const p=await proposal();await applyProposal(id,p,true);const before=await db!.itineraryItem.findMany({where:{tripId:id}});await applyProposal(id,p,true);expect(await db!.itineraryItem.findMany({where:{tripId:id}})).toEqual(before);expect((await getOrganizer(id)).locked).toBe(true);});
 it("rejects tampering and stale inputs without partial updates",async()=>{await add();const p=await proposal();p.placements[0].period="Full day";await expect(applyProposal(id,p,false)).rejects.toThrow("proposal was changed");expect((await getOrganizer(id)).items.every(i=>!i.dayId)).toBe(true);});
 it("incremental resync preserves old placements and IDs",async()=>{await add();await applyProposal(id,await proposal(),false);const before=(await getOrganizer(id)).items;await add("Port City:\n- New gallery");await applyProposal(id,await proposal(),false);const after=(await getOrganizer(id)).items;for(const i of before)expect(after.find(x=>x.id===i.id)).toMatchObject({dayId:i.dayId,position:i.position});});
 it("booked dates and references survive a consequential move and removal from schedule",async()=>{await add("Port City:\n2031-06-02\n- Concert 19:30 booked",true);await applyProposal(id,await proposal(),false);const w=await getOrganizer(id),i=w.items[0],booking=await db!.reservation.findFirstOrThrow({where:{tripId:id}});const p=await previewPlacement(id,i.id,w.days[2].id,"Evening");expect(p.warnings.join()).toContain("confirmed booking");await applyProposal(id,p,false);await applyProposal(id,await previewPlacement(id,i.id,null,"Evening"),false);expect(await db!.reservation.findUnique({where:{id:booking.id}})).toEqual(booking);});
 it("ordinary undo is revision checked",async()=>{await add();const result=await applyProposal(id,await proposal(),false);await undoChange(id,result.undo);expect((await getOrganizer(id)).items.every(i=>!i.dayId)).toBe(true);await expect(undoChange(id,result.undo)).rejects.toThrow("stale");});
 it("unconfirmed booked text does not produce a confirmed reservation",async()=>{await add("Port City:\n- Museum booked");expect((await db!.reservation.findFirstOrThrow({where:{tripId:id}})).state).toBe("BOOK_NOW");});
 it("gap search is read only and respects protected time",async()=>{await add("Port City:\n2031-06-02\n- Keep afternoon free\n- Museum");await applyProposal(id,await proposal(),false);const w=await getOrganizer(id),d=w.days.find(x=>x.date==="2031-06-02")!;const before=await db!.itineraryItem.findMany({where:{tripId:id}});await expect(findGapIdeas(id,d.id,"Hotel",90,"Afternoon",false)).rejects.toThrow("protected");await findGapIdeas(id,d.id,"Hotel",90,"Afternoon",true);expect(await db!.itineraryItem.findMany({where:{tripId:id}})).toEqual(before);});
 it("saves grouped source context, moves one item and derives content from reopened state",async()=>{
  await add("Port City:\n- Market\nOuting: River outing\nSequence: 1\nDescription: Browse the supplied food stalls.\n- Gallery\nOuting: River outing\nSequence: 2\nDecision: Choose the gallery ticket");
  const before=await getOrganizer(id),p=await proposal();expect((await getOrganizer(id)).items).toEqual(before.items);expect(p.placements[0].dayId).toBe(p.placements[1].dayId);
  await applyProposal(id,p,false);const w=await getOrganizer(id),gallery=w.items.find(i=>i.title==="Gallery")!,original=gallery.dayId!;
  expect(gallery).toMatchObject({period:"Afternoon",sourcePeriod:"",outing:"River outing"});
  await applyProposal(id,await previewPlacement(id,gallery.id,w.days[3].id,"Afternoon"),false);
  const reopened=await getOrganizer(id);expect(reopened.items.find(i=>i.id===gallery.id)?.fragment).toContain("Decision: Choose the gallery ticket");
  expect(dayContent(reopened.days.find(d=>d.id===original)!,reopened.items.filter(i=>i.dayId===original)).next).toBe("");
  expect(dayContent(reopened.days[3],reopened.items.filter(i=>i.dayId===w.days[3].id)).next).toBe("Choose the gallery ticket");
 });
 it("rejects invalid source-context fields before any durable import",async()=>{const values=parsePaste("Port City:\n- Walk");values[0].sequence="not a number";await expect(acceptImport(id,"Source",values,"",false)).rejects.toThrow("sequence");expect(await db!.itineraryItem.count({where:{tripId:id}})).toBe(0);});
 it("resolves one alternative in place without adding both or changing its source fragment",async()=>{await add("Port City:\n- Coast or Hills");const w=await getOrganizer(id),i=w.items[0];await expect(includeIdea(id,i.id,w.token,"INCLUDED")).rejects.toThrow("Choose one");await includeIdea(id,i.id,w.token,"INCLUDED","Hills");const after=await getOrganizer(id);expect(after.items).toHaveLength(1);expect(after.items[0]).toMatchObject({id:i.id,title:"Hills",fragment:i.fragment,pending:true,alternative:false});});
});
