import { afterAll, afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@/src/generated/prisma/client";
import { getPrismaClient } from "@/src/lib/prisma";
import * as travelReads from "@/src/modules/itinerary/travel/service";
import { saveTravelPlan, clearTravelPlan, reconfirmTravelPlan, getTravelPlanning } from "@/src/modules/itinerary/travel/service";
import { getTodayView } from "@/src/modules/today/service";
import { markItineraryItemCompleted, restoreItineraryItemToPending, previewSkipItineraryItem, skipItineraryItem, type ProgressResult } from "@/src/modules/itinerary/progress-service";
import { createPlanningBlock, previewMoveItineraryItem, confirmMoveItineraryItem } from "@/src/modules/itinerary/builder-service";
import { removeItineraryItem, scheduleAcceptedRecommendation } from "@/src/modules/itinerary/service";
import { createActivityReservation, createTransportationReservation, markReservationBooked, setReservationWorkflowState } from "@/src/modules/reservations/service";
import { updateReservationNotes, previewReservationCancellation, recordReservationCancellation, recordReleaseEvidence } from "@/src/modules/reservations/followup-service";
import { decideRecommendation } from "@/src/modules/discover/service";
import { createTrip, removeSegment, updateTrip } from "@/src/modules/trips/service";
import { seedDemoTrip, DEMO_TRIP_ID as tripId } from "../prisma/seed-data";
import { seedDiscoverFixtures } from "../prisma/discover-seed";
const enabled=Boolean(process.env.DATABASE_URL), integration=enabled?describe:describe.skip, db=enabled?getPrismaClient():null;
const now=new Date("2030-04-01T20:00Z");
function ok<T>(r:ProgressResult<T>):T{if(!r.ok)throw Error(r.error.message);return r.data;}
async function day(index=0){return (await db!.day.findMany({where:{tripId},orderBy:{position:"asc"}}))[index];}
async function block(type="TRANSPORTATION",extra={}){return ok(await createPlanningBlock({tripId,dayId:(await day()).id,type,startMinute:600,durationMinutes:90,...extra})).id;}
async function activity(){const rec=await db!.recommendation.findFirstOrThrow({where:{tripId},orderBy:{displayRank:"asc"}});expect((await decideRecommendation({tripId,tripSegmentId:rec.tripSegmentId,recommendationId:rec.id,outcome:"ACCEPTED"})).ok).toBe(true);return ok(await scheduleAcceptedRecommendation({tripId,recommendationId:rec.id,dayId:(await day()).id,startMinute:600,flexibility:"FIXED"})).id;}
async function read(itemId:string){return ok(await getTravelPlanning(tripId,now)).find(t=>t.itemId===itemId)!;}
async function request(itemId:string){return {tripId,itemId,token:(await read(itemId)).token};}
async function save(itemId:string,extra={}){return saveTravelPlan({...await request(itemId),originKind:"ENTERED",originLabel:"Demo meeting point",travelMinutes:25,bufferMinutes:10,basis:"PLANNED",clockContext:"SAME_LOCAL_CLOCK",...extra},now);}
async function booking(itemId:string,booked=true){const item=await db!.itineraryItem.findUniqueOrThrow({where:{id:itemId}});const r=ok(await (item.type==="ACTIVITY"?createActivityReservation:createTransportationReservation)({tripId,itineraryItemId:itemId,state:"CHECK_BACK"}));if(booked)ok(await markReservationBooked({tripId,reservationId:r.id,confirmedDate:"2030-04-01",confirmedStartMinute:630}));return r.id;}
async function progressRequest(itemId:string){const v=ok(await getTodayView(tripId,(await day()).id,now));const item=[v.plan.next,...v.plan.remaining,...v.plan.processed].find(i=>i?.id===itemId)!;return {tripId,itemId,token:item.token};}
async function snapshot(){return {items:await db!.itineraryItem.findMany({orderBy:{id:"asc"}}),plans:await db!.itineraryTravelPlan.findMany({orderBy:{itemId:"asc"}}),reservations:await db!.reservation.findMany({orderBy:{id:"asc"}}),decisions:await db!.recommendationDecision.findMany({orderBy:{id:"asc"}}),evidence:await db!.evidenceRecord.findMany({orderBy:{id:"asc"}}),release:await db!.releaseObservation.findMany({orderBy:{evidenceRecordId:"asc"}})};}
integration("Canonical known-context departure planning",()=>{
 beforeEach(async()=>{await db!.trip.deleteMany();await db!.prototypeUser.deleteMany();await db!.evidenceRecord.deleteMany();await db!.place.deleteMany();await db!.source.deleteMany();await seedDemoTrip(db!);await seedDiscoverFixtures(db!);});
 afterEach(()=>vi.restoreAllMocks());afterAll(async()=>{await db?.$disconnect();});
 it("saves, edits and persists one owned plan through a fresh client without changing business fields",async()=>{
  const id=await activity(),r=await booking(id),before=await snapshot();ok(await save(id,{plannedAcknowledged:true}));expect((await read(id)).departure?.time).toBe("09:25");
  const fresh=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.TEST_DATABASE_URL!})});try{expect(await fresh.itineraryTravelPlan.findUnique({where:{itemId:id}})).toMatchObject({travelMinutes:25,bufferMinutes:10,originKind:"ENTERED"});}finally{await fresh.$disconnect();}
  ok(await save(id,{travelMinutes:30,plannedAcknowledged:true}));const after=await snapshot();expect(after.plans).toHaveLength(1);expect(after.items[0]).toEqual({...before.items[0],revision:before.items[0].revision+2,travelPlanActionKey:expect.any(String),updatedAt:expect.any(Date)});expect(after.reservations).toEqual(before.reservations);expect(after.decisions).toEqual(before.decisions);expect(after.evidence).toEqual(before.evidence);expect(after.reservations[0].id).toBe(r);
 });
 it("clear is idempotent and preserves the item and reservation",async()=>{const id=await activity();await booking(id);ok(await save(id,{plannedAcknowledged:true}));const before=await snapshot(),q=await request(id);ok(await clearTravelPlan(q,now));const cleared=await snapshot();ok(await clearTravelPlan(q,now));expect(await snapshot()).toEqual(cleared);expect(cleared.plans).toEqual([]);expect(cleared.reservations).toEqual(before.reservations);expect(cleared.items[0]).toMatchObject({id,progress:"PENDING",startMinute:600});});
 it("same saves serialize into one plan and conflicting edits cannot overwrite each other",async()=>{const id=await block(),q={...await request(id),originKind:"ENTERED",originLabel:"Station entrance",travelMinutes:25,bufferMinutes:10,basis:"PLANNED",clockContext:"SAME_LOCAL_CLOCK"};expect((await Promise.all([saveTravelPlan(q,now),saveTravelPlan(q,now)])).every(r=>r.ok)).toBe(true);const before=await snapshot();ok(await saveTravelPlan(q,now));expect(await snapshot()).toEqual(before);const token=(await request(id)).token;const results=await Promise.all([saveTravelPlan({...q,token,travelMinutes:30},now),saveTravelPlan({...q,token,travelMinutes:40},now)]);expect(results.filter(r=>r.ok)).toHaveLength(1);expect(await db!.itineraryTravelPlan.count()).toBe(1);expect((await clearTravelPlan({...q,token},now)).ok).toBe(false);});
 it("old save/clear requests cannot resurrect or remove a newer plan after clear and recreation",async()=>{const id=await block(),old=await request(id);ok(await save(id));const clear=await request(id);ok(await clearTravelPlan(clear,now));ok(await save(id,{travelMinutes:99}));expect((await clearTravelPlan(clear,now)).ok).toBe(false);expect((await saveTravelPlan({...old,originKind:"ENTERED",originLabel:"Old point",travelMinutes:1,bufferMinutes:0,basis:"PLANNED",clockContext:"SAME_LOCAL_CLOCK"},now)).ok).toBe(false);expect((await read(id)).inputs?.travelMinutes).toBe(99);});
 it("rejects cross-Trip IDs and enforces composite target and source FKs",async()=>{const id=await block(),source=await block("HOTEL_REST"),other=await createTrip({destinationLabel:"Other",destinationScope:"CITY_BASE",startDate:"2030-04-01",endDate:"2030-04-02",travelerCount:1});expect(other.ok).toBe(true);const otherId=other.data!.trip.id,otherDay=await db!.day.findFirstOrThrow({where:{tripId:otherId}});const foreign=ok(await createPlanningBlock({tripId:otherId,dayId:otherDay.id,type:"TRANSPORTATION",startMinute:600})).id;expect((await save(id,{originKind:"EARLIER_ITEM",sourceItemId:foreign})).ok).toBe(false);ok(await save(id));const plan=await db!.itineraryTravelPlan.findUniqueOrThrow({where:{itemId:id}});await expect(db!.itineraryTravelPlan.update({where:{itemId:id},data:{tripId:otherId}})).rejects.toThrow();await expect(db!.itineraryTravelPlan.update({where:{itemId:id},data:{sourceItemId:foreign}})).rejects.toThrow();expect(await db!.itineraryTravelPlan.findUniqueOrThrow({where:{itemId:id}})).toEqual(plan);expect((await clearTravelPlan({...await request(id),tripId:otherId},now)).ok).toBe(false);expect(source).toBeTruthy();});
 it("rejects invalid target types, missing values and unsuitable origin choices",async()=>{const free=await block("FREE_TIME"),later=await block(),id=await block();for(const sourceItemId of [id,"missing"]){expect((await save(id,{originKind:"EARLIER_ITEM",sourceItemId})).ok).toBe(false);}expect((await save(later,{originKind:"EARLIER_ITEM",sourceItemId:id})).ok).toBe(false);expect(ok(await getTravelPlanning(tripId,now)).some(t=>t.itemId===free)).toBe(false);ok(await save(id));await db!.itineraryItem.update({where:{id},data:{type:"FREE_TIME"}});const unsupported=await save(id);expect(unsupported).toMatchObject({ok:false,error:{code:"TRAVEL_CONTEXT_UNAVAILABLE"}});ok(await clearTravelPlan(await request(id),now));await db!.itineraryItem.update({where:{id},data:{type:"TRANSPORTATION"}});for(const extra of [{travelMinutes:""},{travelMinutes:-1},{travelMinutes:1.5},{bufferMinutes:241},{basis:""}])expect((await save(id,extra)).ok).toBe(false);expect(await db!.itineraryTravelPlan.count()).toBe(0);});
 it("requires known matching Segment context for an earlier origin but allows an entered point on Unassigned Days",async()=>{const source=await block("HOTEL_REST"),id=await block();await removeSegment(tripId,(await day()).primarySegmentId!);expect((await save(id,{originKind:"EARLIER_ITEM",sourceItemId:source})).ok).toBe(false);ok(await save(id));expect((await read(id)).status).toBe("READY");});
 it("retains detached origin label/durations and target when the referenced source is deleted",async()=>{const source=await block("HOTEL_REST"),id=await block();ok(await save(id,{originKind:"EARLIER_ITEM",sourceItemId:source}));ok(await removeItineraryItem(tripId,source));const v=await read(id);expect(v).toMatchObject({status:"NEEDS_REVIEW",departure:null,inputs:{originKind:"EARLIER_ITEM",sourceItemId:null,originLabel:"Hotel / Rest",travelMinutes:25}});expect((await reconfirmTravelPlan(await request(id),now)).ok).toBe(false);expect(await db!.itineraryItem.findUnique({where:{id}})).not.toBeNull();});
 it("source movement or skipping invalidates the reference without deleting travel inputs",async()=>{const source=await block("HOTEL_REST"),id=await block();ok(await save(id,{originKind:"EARLIER_ITEM",sourceItemId:source}));const p=ok(await previewSkipItineraryItem(await progressRequest(source),now));ok(await skipItineraryItem({tripId,itemId:source,token:p.token},now));expect((await read(id)).departure).toBeNull();ok(await restoreItineraryItemToPending(await progressRequest(source),now));const move=ok(await previewMoveItineraryItem({tripId,itemId:source,targetDayId:(await day(1)).id}));ok(await confirmMoveItineraryItem(tripId,move.token));expect((await read(id))).toMatchObject({status:"NEEDS_REVIEW",departure:null,inputs:{sourceItemId:source,travelMinutes:25}});});
 it("changed source timing requires explicit reconfirmation and then warns on infeasibility",async()=>{const source=await block("HOTEL_REST",{startMinute:500,durationMinutes:30}),id=await block();ok(await save(id,{originKind:"EARLIER_ITEM",sourceItemId:source}));await db!.itineraryItem.update({where:{id:source},data:{startMinute:540,durationMinutes:40}});expect((await read(id))).toMatchObject({status:"NEEDS_REVIEW",departure:null});const q=await request(id);ok(await reconfirmTravelPlan(q,now));const before=await snapshot();ok(await reconfirmTravelPlan(q,now));expect(await snapshot()).toEqual(before);expect((await read(id)).warnings.join(" ")).toContain("09:40");expect((await read(id)).departure?.time).toBe("09:25");});
 it("target movement retains inputs/progress but requires review of the new Day",async()=>{const id=await block();ok(await save(id));const old=await request(id),p=ok(await previewMoveItineraryItem({tripId,itemId:id,targetDayId:(await day(1)).id}));ok(await confirmMoveItineraryItem(tripId,p.token));expect((await read(id))).toMatchObject({status:"NEEDS_REVIEW",departure:null,inputs:{travelMinutes:25}});expect((await clearTravelPlan(old,now)).ok).toBe(false);ok(await reconfirmTravelPlan(await request(id),now));expect((await read(id)).departure).toMatchObject({date:"2030-04-02",time:"09:25"});expect((await db!.itineraryItem.findUniqueOrThrow({where:{id}})).progress).toBe("PENDING");});
 it("target time changes stale both the estimate and old form without overwriting entered duration",async()=>{const id=await block();ok(await save(id));const old=await request(id);await db!.itineraryItem.update({where:{id},data:{startMinute:615}});expect((await read(id)).departure).toBeNull();expect((await saveTravelPlan({...old,originKind:"ENTERED",originLabel:"Point",travelMinutes:1,bufferMinutes:0,basis:"PLANNED",clockContext:"SAME_LOCAL_CLOCK"},now)).ok).toBe(false);ok(await reconfirmTravelPlan(await request(id),now));expect((await read(id)).departure?.time).toBe("09:40");});
 it("requires deliberate planned mismatch acknowledgement and keeps basis fixed",async()=>{const id=await activity();await booking(id);expect((await save(id)).ok).toBe(false);ok(await save(id,{basis:"CONFIRMED"}));expect((await read(id)).departure?.time).toBe("09:55");ok(await save(id,{plannedAcknowledged:true}));expect((await read(id))).toMatchObject({inputs:{basis:"PLANNED"},departure:{time:"09:25"}});});
 it("booked time changes invalidate confirmed basis and reconfirm uses current known time",async()=>{const id=await activity(),r=await booking(id);ok(await save(id,{basis:"CONFIRMED"}));await db!.reservation.update({where:{id:r},data:{confirmedStartMinute:660}});expect((await read(id))).toMatchObject({status:"NEEDS_REVIEW",departure:null,inputs:{basis:"CONFIRMED"}});ok(await reconfirmTravelPlan(await request(id),now));expect((await read(id)).departure?.time).toBe("10:25");});
 it("never substitutes desired, cancelled, missing or different-Day confirmed timing",async()=>{const id=await activity(),r=await booking(id,false);expect((await save(id,{basis:"CONFIRMED"})).ok).toBe(false);ok(await markReservationBooked({tripId,reservationId:r,confirmedDate:"2030-04-02",confirmedStartMinute:600}));expect((await save(id,{basis:"CONFIRMED"})).ok).toBe(false);expect((await save(id,{basis:"PLANNED",plannedAcknowledged:true})).ok).toBe(false);await db!.reservation.update({where:{id:r},data:{confirmedDate:new Date("2030-04-01T12:00Z")}});ok(await save(id,{basis:"CONFIRMED"}));const p=ok(await previewReservationCancellation({tripId,reservationId:r},now));ok(await recordReservationCancellation({tripId,reservationId:r,token:p.token,externalCancellationConfirmed:true},now));expect((await read(id))).toMatchObject({status:"INACTIVE",departure:null,inputs:{basis:"CONFIRMED"}});});
 it("planning booking state changes stale the estimate; unrelated notes/evidence do not",async()=>{const id=await activity(),r=await booking(id,false);ok(await save(id));ok(await updateReservationNotes({tripId,reservationId:r,notes:"Unrelated notes"}));ok(await recordReleaseEvidence({tripId,reservationId:r,sourceName:"Synthetic travel evidence",factualText:"Not live",precision:"UNKNOWN",attribution:"DEVELOPMENT_FIXTURE",observedAt:"2020-01-01T00:00Z"},now));await db!.itineraryItem.update({where:{id},data:{notes:"Unrelated item notes"}});expect((await read(id)).status).toBe("READY");ok(await setReservationWorkflowState({tripId,reservationId:r,state:"OPENS_LATER"}));expect((await read(id)).status).toBe("NEEDS_REVIEW");});
 it("an ambiguous-clock plan retains inputs but never presents a departure or reconfirms ambiguity away",async()=>{const id=await block();ok(await save(id,{clockContext:"REQUIRES_REVIEW"}));expect((await read(id))).toMatchObject({status:"NEEDS_REVIEW",departure:null});expect((await reconfirmTravelPlan(await request(id),now)).ok).toBe(false);ok(await save(id,{travelMinutes:0,bufferMinutes:0}));expect((await read(id)).departure?.time).toBe("10:00");});
 it.each(["COMPLETED","SKIPPED"] as const)("%s targets retain inputs, suppress departure and still occupy their Day",async progress=>{const id=await activity();await booking(id);ok(await save(id,{plannedAcknowledged:true}));const before=await snapshot();if(progress==="COMPLETED")ok(await markItineraryItemCompleted(await progressRequest(id),now));else{const p=ok(await previewSkipItineraryItem(await progressRequest(id),now));ok(await skipItineraryItem({tripId,itemId:id,token:p.token,bookingAcknowledged:true},now));}expect((await read(id))).toMatchObject({status:"INACTIVE",departure:null});expect((await snapshot()).plans).toEqual(before.plans);expect((await snapshot()).reservations).toEqual(before.reservations);expect((await updateTrip({tripId,startDate:"2030-04-02",endDate:"2030-04-15",travelerCount:2})).ok).toBe(false);ok(await restoreItineraryItemToPending(await progressRequest(id),now));expect((await read(id)).departure?.time).toBe("09:25");});
 it("target deletion removes owned inputs but detaches retained booking; Trip deletion cascades reference plans",async()=>{const source=await block("HOTEL_REST"),id=await activity(),r=await booking(id);ok(await save(id,{originKind:"EARLIER_ITEM",sourceItemId:source,plannedAcknowledged:true}));const reservation=await db!.reservation.findUniqueOrThrow({where:{id:r}});ok(await removeItineraryItem(tripId,id));expect(await db!.itineraryTravelPlan.count()).toBe(0);expect(await db!.reservation.findUniqueOrThrow({where:{id:r}})).toEqual({...reservation,itineraryItemId:null});const another=await block();ok(await save(another,{originKind:"EARLIER_ITEM",sourceItemId:source}));await db!.trip.delete({where:{id:tripId}});expect(await db!.itineraryTravelPlan.count()).toBe(0);});
 it("repeat seed and reads preserve travel inputs/progress/bookings/decisions/evidence exactly",async()=>{const id=await activity(),r=await booking(id);ok(await save(id,{basis:"CONFIRMED"}));ok(await markItineraryItemCompleted(await progressRequest(id),now));ok(await recordReleaseEvidence({tripId,reservationId:r,sourceName:"Synthetic travel seed evidence",factualText:"Not live",precision:"UNKNOWN",attribution:"DEVELOPMENT_FIXTURE",observedAt:"2020-01-01T00:00Z"},now));const before=await snapshot();await seedDemoTrip(db!,{preserveExisting:true});await seedDiscoverFixtures(db!);await seedDemoTrip(db!,{preserveExisting:true});await seedDiscoverFixtures(db!);await read(id);await getTodayView(tripId,(await day()).id,now);expect(await snapshot()).toEqual(before);});
 it("failed travel read is unavailable in Today rather than a missing/zero travel plan",async()=>{await block();vi.spyOn(travelReads,"getTravelPlanning").mockResolvedValue({ok:false,error:{code:"PERSISTENCE_FAILURE",message:"Synthetic unavailable"}});const v=ok(await getTodayView(tripId,(await day()).id,now));expect(v.plan.next!.travelUnavailable).toBe(true);expect(v.plan.next!.travel).toBeNull();});
 it("validates ownership, item identity, tampering and expiry on all actions",async()=>{const id=await block();ok(await save(id));const q=await request(id),before=await snapshot();for(const bad of [{...q,itemId:"wrong"},{...q,tripId:"wrong"},{...q,token:q.token+"bad"}]){expect((await clearTravelPlan(bad,now)).ok).toBe(false);expect((await reconfirmTravelPlan(bad,now)).ok).toBe(false);}expect((await clearTravelPlan(q,new Date(now.getTime()+31*60000))).ok).toBe(false);expect(await snapshot()).toEqual(before);const owner=await db!.prototypeUser.create({data:{displayName:"Other owner"}});await db!.trip.update({where:{id:tripId},data:{ownerId:owner.id}});expect((await getTravelPlanning(tripId,now)).ok).toBe(false);expect((await clearTravelPlan(q,now)).ok).toBe(false);expect((await reconfirmTravelPlan(q,now)).ok).toBe(false);expect((await saveTravelPlan({...q,originKind:"ENTERED",originLabel:"Point",travelMinutes:25,bufferMinutes:10,basis:"PLANNED",clockContext:"SAME_LOCAL_CLOCK"},now)).ok).toBe(false);});
});
