import {afterEach,describe,it,expect,vi} from "vitest";
import {DetailSession} from "./detail-session";
import type {Enrichment,GoogleInput,PlaceIdentity} from "./types";
const identity:PlaceIdentity={placeId:"synthetic-venue",revision:"revision-a"};
const content=(extra:Partial<Enrichment>={}):Enrichment=>({status:"ready",matched:true,identity,place:{id:identity.placeId,formattedAddress:"Synthetic address",rating:4.3},message:"",...extra});
const pending=<T>()=>{let resolve!:(value:T)=>void;const promise=new Promise<T>(r=>{resolve=r;});return {promise,resolve};};
function fixture(linked=true,override?:(i:GoogleInput)=>Promise<Enrichment>|undefined){
 const send=vi.fn(async(i:GoogleInput):Promise<Enrichment>=>{
  const other=override?.(i);if(other)return other;
  if(i.purpose==="open")return linked?content({place:undefined}):{status:"needs_confirmation",message:""};
  if(i.purpose==="identity")return {status:"needs_confirmation",message:"",candidates:[{place:{id:identity.placeId},eligible:true,reason:"Synthetic verification",token:"signed-fixture"}]};
  if(i.purpose==="confirm")return content({place:undefined});
  if(i.purpose==="photo")return content({photo:{data:"data:image/png;base64,synthetic",authors:[]}});
  return content();
 });return {send,session:new DetailSession({tripId:"trip",recommendationId:"rec"},send)};
}
afterEach(()=>vi.useRealTimers());
describe("explicit transient activity detail flow",()=>{
 it("construction, subscriptions and ordinary remounts never dispatch",async()=>{const {session,send}=fixture();expect(session.matches("trip","rec")).toBe(true);expect(session.matches("trip","other")).toBe(false);const off=session.subscribe(()=>{});session.snapshot();off();session.subscribe(()=>{});expect(send).not.toHaveBeenCalled();session.close();});
 it("linked opening revalidates overview then photo, without matching or confirmation",async()=>{const {session,send}=fixture();await session.open();await session.open();expect(send.mock.calls.map(c=>c[0].purpose)).toEqual(["open","context","photo"]);expect(session.snapshot().overview?.place?.rating).toBe(4.3);expect(session.snapshot().photo?.photo).toBeDefined();session.close();});
 it("unlinked opening searches once and waits for deliberate confirmation",async()=>{const {session,send}=fixture(false);await session.open();expect(send.mock.calls.map(c=>c[0].purpose)).toEqual(["open","identity"]);expect(session.snapshot().identity).toBeUndefined();await session.confirm("signed-fixture");expect(send.mock.calls.map(c=>c[0].purpose)).toEqual(["open","identity","confirm","context","photo"]);await session.confirm("signed-fixture");expect(send).toHaveBeenCalledTimes(5);session.close();});
 it("ambiguous choices do not auto-link; conflicting candidates cannot be overridden",async()=>{const {session,send}=fixture(false,i=>i.purpose==="identity"?Promise.resolve({status:"ambiguous",message:"",candidates:[{place:{id:"one"},eligible:true,reason:"",token:"one"},{place:{id:"two"},eligible:true,reason:"",token:"two"},{place:{id:"bad"},eligible:false,reason:"",token:"bad"}]}):undefined);await session.open();await session.confirm("bad");expect(send).toHaveBeenCalledTimes(2);expect(session.snapshot().status).toBe("ambiguous");session.close();});
 it("rapid open and confirmation clicks are single-flight",async()=>{const gate=pending<Enrichment>();const {session,send}=fixture(false,i=>i.purpose==="confirm"?gate.promise:undefined);await Promise.all([session.open(),session.open()]);const first=session.confirm("signed-fixture");await session.confirm("signed-fixture");expect(send.mock.calls.filter(c=>c[0].purpose==="confirm")).toHaveLength(1);gate.resolve(content({place:undefined}));await first;session.close();});
 it("reviews loading/failure never clears overview or photo",async()=>{const gate=pending<Enrichment>();const {session}=fixture(true,i=>i.purpose==="reviews"?gate.promise:undefined);await session.open();const before=session.snapshot();const request=session.reviews();expect(session.snapshot().overview).toBe(before.overview);expect(session.snapshot().photo).toBe(before.photo);gate.resolve({status:"unavailable",message:""});await request;expect(session.snapshot().overview).toBe(before.overview);expect(session.snapshot().photo).toBe(before.photo);expect(session.snapshot().sections.reviews).toBe("unavailable");session.close();});
 it("tab switches and rapid reviews clicks dispatch only once per session",async()=>{const {session,send}=fixture();await session.open();await Promise.all([session.reviews(),session.reviews()]);await session.reviews();expect(send.mock.calls.filter(c=>c[0].purpose==="reviews")).toHaveLength(1);session.close();});
 it.each(["disabled","unavailable","budget_exhausted"] as const)("%s availability never calls a provider purpose",async status=>{const {session,send}=fixture(true,i=>i.purpose==="open"?Promise.resolve({status,message:""}):undefined);await session.open();expect(send).toHaveBeenCalledTimes(1);expect(session.snapshot().status).toBe(status);session.close();});
 it("failed overview stops photo continuation",async()=>{const {session,send}=fixture(true,i=>i.purpose==="context"?Promise.resolve({status:"budget_exhausted",message:""}):undefined);await session.open();expect(send.mock.calls.map(c=>c[0].purpose)).toEqual(["open","context"]);expect(session.snapshot().status).toBe("budget_exhausted");session.close();});
 it("photo failure preserves overview and retries only after explicit refresh",async()=>{const {session,send}=fixture(true,i=>i.purpose==="photo"?Promise.resolve({status:"unavailable",message:""}):undefined);await session.open();expect(session.snapshot().overview).toBeDefined();expect(session.snapshot().sections.photo).toBe("unavailable");await session.open();expect(send).toHaveBeenCalledTimes(3);await session.refresh();expect(send).toHaveBeenCalledTimes(6);session.close();});
 it("image-load failure retains rating and location",async()=>{const {session}=fixture();await session.open();session.photoFailed();expect(session.snapshot().photo).toBeUndefined();expect(session.snapshot().overview?.place?.rating).toBe(4.3);session.close();});
 it.each([{placeId:"other",revision:identity.revision},{placeId:identity.placeId,revision:"other"}])("does not mix changed place/revision %j",async changed=>{const {session}=fixture(true,i=>i.purpose==="reviews"?Promise.resolve(content({identity:changed})):undefined);await session.open();await session.reviews();expect(session.snapshot().overview).toBeUndefined();expect(session.snapshot().photo).toBeUndefined();expect(session.snapshot().status).toBe("unavailable");session.close();});
 it("changed reference reported before payload clears old data",async()=>{const {session}=fixture(true,i=>i.purpose==="reviews"?Promise.resolve({status:"unavailable",identityChanged:true,message:""}):undefined);await session.open();await session.reviews();expect(session.snapshot().identity).toBeUndefined();expect(session.snapshot().overview).toBeUndefined();session.close();});
 it("close drops content and ignores late photo/review replies",async()=>{const gate=pending<Enrichment>();const {session,send}=fixture(true,i=>i.purpose==="reviews"?gate.promise:undefined);await session.open();const review=session.reviews();session.close();gate.resolve(content());await review;expect(session.snapshot().overview).toBeUndefined();expect(session.snapshot().reviews).toBeUndefined();await session.open();expect(send).toHaveBeenCalledTimes(4);});
 it("close during open prevents matching and continuation",async()=>{const gate=pending<Enrichment>();const {session,send}=fixture(false,()=>gate.promise);const opening=session.open();session.close();gate.resolve({status:"needs_confirmation",message:""});await opening;expect(send).toHaveBeenCalledTimes(1);});
 it("fixed five-minute expiry clears all sections; tab use never extends it",async()=>{vi.useFakeTimers();const {session,send}=fixture();await session.open();const expiry=session.snapshot().expiresAt;await vi.advanceTimersByTimeAsync(299000);await session.reviews();expect(session.snapshot().expiresAt).toBe(expiry);await vi.advanceTimersByTimeAsync(1000);expect(session.snapshot().status).toBe("expired");expect(session.snapshot().overview).toBeUndefined();expect(session.snapshot().photo).toBeUndefined();const calls=send.mock.calls.length;await session.reviews();expect(send).toHaveBeenCalledTimes(calls);await session.refresh();expect(session.snapshot().status).toBe("ready");session.close();});
 it("no implicit retries after interrupted request; explicit reopening is new intent",async()=>{const first=fixture(true,()=>Promise.reject(Error("transport")));await first.session.open();expect(first.send).toHaveBeenCalledTimes(1);first.session.close();const second=fixture();await second.session.open();expect(second.send).toHaveBeenCalledTimes(3);second.session.close();});
 it("all operations use fresh request IDs and exact linked revision",async()=>{const {session,send}=fixture();await session.open();await session.reviews();const inputs=send.mock.calls.map(c=>c[0]);expect(new Set(inputs.map(i=>i.requestId)).size).toBe(4);expect(inputs.slice(1).every(i=>i.reference?.revision===identity.revision)).toBe(true);session.close();});
});
