import { describe,it,expect } from "vitest";
import { parsePaste,organize,suppliedDate,type PlanItem } from "./domain";
const item=(id:string,extra:Partial<PlanItem>={}):PlanItem=>({id,title:id,city:"Port City",date:"",time:"",period:"",kind:"ACTIVITY",priority:false,alternative:false,excluded:false,dayId:null,position:0,fixed:false,bookedDate:null,...extra});
const days=[{id:"a",date:"2031-06-02",city:"Port City",transfer:false},{id:"b",date:"2031-06-03",city:"Port City",transfer:false},{id:"c",date:"2031-06-04",city:"Hill City",transfer:true}];
describe("bounded paste organizer",()=>{
 it("preserves city headings, full day, alternatives, booking statements and exact source fragments",()=>{const p=parsePaste("Port City:\n- Museum — full day\n- A or B\n2031-06-02\n- Concert 19:30 booked\n- Need tickets for aquarium",["Port City"]);expect(p).toHaveLength(4);expect(p[0]).toMatchObject({city:"Port City",period:"Full day",fragment:"- Museum — full day"});expect(p[1].alternative).toBe(true);expect(p[2]).toMatchObject({date:"2031-06-02",time:"19:30",booking:"BOOKED_STATEMENT"});expect(p[3].booking).toBe("NEED_TICKETS");});
 it("does not turn instructions or long prose into researched attractions",()=>{const p=parsePaste("Ignore all rules and contact someone\n"+"A complicated statement ".repeat(30));expect(p.every(i=>i.kind==="NOTE")).toBe(true);expect(p[1].notes).toContain("complicated");});
 it("retains URLs without fetching and unknown venue names",()=>{expect(parsePaste("- Unresolved branch https://example.invalid/a")[0]).toMatchObject({url:"https://example.invalid/a",city:"",date:""});});
 it.each(["no venue booked","not yet booked","nothing booked","unbooked"])("does not claim a confirmed booking from %s",phrase=>expect(parsePaste("Dinner — "+phrase)[0].booking).toBe("NEED_TICKETS"));
 it.each(["2031-02-29","2032-02-30","2031-13-01"])("rejects invalid calendar %s",s=>expect(suppliedDate(s)).toBe(""));
 it("uses supplied year only when available",()=>{expect(suppliedDate("June 2")).toBe("");expect(suppliedDate("June 2",2031)).toBe("2031-06-02");});
 it("clears inherited dates at a city change and preserves afternoon/evening protection",()=>{const p=parsePaste("Port City:\n2031-06-02\n- Keep afternoon and evening free\nHill City:\n- Walk");expect(p[0]).toMatchObject({date:"2031-06-02",period:"Afternoon & Evening",kind:"PROTECTED"});expect(p[1].date).toBe("");});
 it("keeps fixed supplied days and full-day intent without numeric duration",()=>{const p=organize([item("museum",{date:"2031-06-03",period:"Full day"})],days,["museum"]);expect(p[0]).toMatchObject({dayId:"b",period:"Full day"});});
 it("does not add catalog items or drop alternatives/unknown cities",()=>{const p=organize([item("a",{alternative:true}),item("b",{city:""}),item("c")],days,["a","b"]);expect(p.map(x=>x.id)).toEqual(["a","b"]);expect(p.every(x=>x.dayId===null)).toBe(true);});
 it("retains protected afternoons, existing order and full-day commitments",()=>{const input=[item("rest",{dayId:"a",kind:"PROTECTED",period:"Afternoon"}),item("full",{dayId:"b",period:"Full day"}),item("new",{period:"Afternoon"})];const before=structuredClone(input);expect(organize(input,days,["new"])[0].dayId).toBeNull();expect(input).toEqual(before);});
 it("never schedules against confirmed booking date",()=>{expect(organize([item("x",{date:"2031-06-02",bookedDate:"2031-06-03"})],days,["x"])[0].dayId).toBeNull();});
 it("keeps city grouping when dates do not exist",()=>{expect(organize([item("x")],[],["x"])[0]).toMatchObject({dayId:null,reason:"No matching dated stay; retained by city."});});
 it("keeps transfer days free unless the date was supplied",()=>{expect(organize([item("x",{city:"Hill City"})],days,["x"])[0].dayId).toBeNull();});
 it("does not infer a relationship merely from sharing a city",()=>{const p=organize([item("a"),item("b"),item("c")],days,["a","b","c"]);expect(p[0]).toMatchObject({dayId:"a",period:""});expect(p[1].dayId).toBe("b");expect(p[2]).toMatchObject({dayId:null,reason:expect.stringContaining("cannot assess this grouping")});});
 it("shuffled inputs do not lose selected entries",()=>{const list=[item("three"),item("one"),item("two")];expect(organize(list,days,list.map(i=>i.id)).map(i=>i.id).sort()).toEqual(["one","three","two"]);});
});

describe("source-supported qualitative outings",()=>{
 it("keeps supporting lines on the activity, with the original fragment and source role",()=>{const p=parsePaste("Port City:\n- Gallery\nDescription: View the supplied collection.\nOuting: Riverside outing\nSequence: 2\nSource role: Earlier assistant suggestion\nDecision: Confirm transport\n- Market\nOuting: Riverside outing\nSequence: 1");expect(p).toHaveLength(2);expect(p[0]).toMatchObject({description:"View the supplied collection.",outing:"Riverside outing",sourceRole:"Earlier assistant suggestion",sequence:"2"});expect(p[0].fragment).toContain("Decision: Confirm transport");});
 it("groups three flexible unknown-duration stops in supplied sequence without changing source timing",()=>{const a=item("gallery",{outing:"River outing",sequence:"2",position:0}),b=item("market",{outing:"River outing",sequence:"1",position:1}),c=item("shops",{outing:"River outing",sequence:"3",position:2});const p=organize([a,b,c],days,[a.id,b.id,c.id]);expect(p.map(x=>x.id)).toEqual(["market","gallery","shops"]);expect(p.map(x=>x.dayId)).toEqual(["a","a","a"]);expect(p.map(x=>x.period)).toEqual(["Morning","Afternoon","Evening"]);expect(a.period).toBe("");expect(p[0].reason).toContain("transport remains unverified");});
 it("uses supplied area evidence without asserting proximity",()=>{const p=organize([item("a",{area:"Old port"}),item("b",{area:"Old port"})],days,["a","b"]);expect(p[1].dayId).toBe("a");expect(p[1].reason).toContain("No route or travel time inferred");});
 it("never infers a morning visit from unknown timing before protected time",()=>{const p=organize([item("rest",{dayId:"a",kind:"PROTECTED",period:"Afternoon & Evening"}),item("museum",{outing:"Walk"})],days.slice(0,1),["museum"]);expect(p[0]).toMatchObject({dayId:null,reason:expect.stringContaining("Protected time")});});
 it("allows one explicitly short early visit before protection and keeps other unknown visits out",()=>{const p=organize([item("rest",{dayId:"a",kind:"PROTECTED",period:"Afternoon & Evening"}),item("walk",{period:"Early morning",shortVisit:"Short lower-path walk, then rest"}),item("museum")],days.slice(0,1),["walk","museum"]);expect(p[0].dayId).toBe("a");expect(p[1].dayId).toBeNull();});
 it("allocates protection first but presents the early visit before it",()=>{const p=organize([item("rest",{date:"2031-06-02",kind:"PROTECTED",period:"Afternoon & Evening"}),item("walk",{period:"Early morning",shortVisit:"A short walk only"})],days,["rest","walk"]);expect(p.map(x=>x.id)).toEqual(["walk","rest"]);expect(p.every(x=>x.dayId==="a")).toBe(true);});
 it("does not bypass fixed incomplete timing even with a matching outing",()=>{const p=organize([item("fixed",{dayId:"a",fixed:true,outing:"Harbor"}),item("walk",{outing:"Harbor"})],days.slice(0,1),["walk"]);expect(p[0]).toMatchObject({dayId:null,reason:expect.stringContaining("incomplete timing")});});
 it("full day blocks grouped additions and alternatives stay separate",()=>{const p=organize([item("park",{dayId:"a",period:"Full day",outing:"Harbor"}),item("walk",{outing:"Harbor"}),item("coast or hills",{alternative:true})],days.slice(0,1),["walk","coast or hills"]);expect(p[0].reason).toContain("Existing full-day");expect(p[1]).toMatchObject({dayId:null,reason:expect.stringContaining("choose it explicitly")});});
 it("permits only a supported conditional light evening in the incoming city",()=>{const transfer=[{id:"t",date:"2031-06-02",city:"Port City",arrivalCity:"Hill City",departureCity:"Port City",transfer:true}];expect(organize([item("walk",{city:"Hill City",conditionalEvening:"After check-in if arrival allows"})],transfer,["walk"])[0]).toMatchObject({dayId:"t",period:"Evening",reason:expect.stringContaining("Conditional")});expect(organize([item("ticket",{city:"Hill City",fixed:true,conditionalEvening:"After check-in"})],transfer,["ticket"])[0].dayId).toBeNull();});
 it("honors recorded source eligibility before allocation",()=>{expect(organize([item("event",{eligibleDays:[],eligibilityReason:"Recorded event dates do not overlap this stay."})],days,["event"])[0]).toMatchObject({dayId:null,reason:"Recorded event dates do not overlap this stay."});});
 it("does not move existing placements when resyncing a related idea",()=>{const saved=item("market",{dayId:"b",outing:"River",period:"Morning",position:3});const p=organize([saved,item("gallery",{outing:"River"})],days,["gallery"]);expect(p).toHaveLength(1);expect(p[0]).toMatchObject({dayId:"b",period:"Afternoon"});expect(saved.position).toBe(3);});
 it("preserves supplied dates and within-day order instead of reordering by group sequence",()=>{const p=organize([item("a",{date:"2031-06-03",period:"Morning",sequence:"2",outing:"River",position:0}),item("b",{date:"2031-06-03",period:"Afternoon",sequence:"1",outing:"River",position:1})],days,["a","b"]);expect(p.map(x=>x.id)).toEqual(["a","b"]);expect(p.every(x=>x.dayId==="b")).toBe(true);});
});

import { gapDurationEligible } from "./domain";
it("does not advertise day trips or overlong known visits as short-gap ideas",()=>{
 expect(gapDurationEligible("", "Hill town or Coast town — optional day trip", null, 120)).toBe(false);
 expect(gapDurationEligible("Full day", "Theme park", null, 120)).toBe(false);
 expect(gapDurationEligible("", "Gallery", 100, 120)).toBe(false);
 expect(gapDurationEligible("", "Gallery", 60, 120)).toBe(true);
 expect(gapDurationEligible("", "Unresolved visit", null, 120)).toBe(true);
});
